// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: AI_ACT_P33.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AI_ACT_P33 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AiPos         *CHAPTERCELLPOS_P33    `protobuf:"bytes,1,req,name=ai_pos,json=aiPos" json:"ai_pos,omitempty"`
	StrategyId    *uint32                `protobuf:"varint,2,opt,name=strategy_id,json=strategyId" json:"strategy_id,omitempty"`
	TargetPos     *CHAPTERCELLPOS_P33    `protobuf:"bytes,3,opt,name=target_pos,json=targetPos" json:"target_pos,omitempty"`
	MovePath      []*CHAPTERCELLPOS_P33  `protobuf:"bytes,4,rep,name=move_path,json=movePath" json:"move_path,omitempty"`
	ShipUpdate    []*SHIPINCHAPTER_P33   `protobuf:"bytes,6,rep,name=ship_update,json=shipUpdate" json:"ship_update,omitempty"`
	Type          *uint32                `protobuf:"varint,7,req,name=type" json:"type,omitempty"`
	PosList       []*WORLDPOSINFO        `protobuf:"bytes,8,rep,name=pos_list,json=posList" json:"pos_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AI_ACT_P33) Reset() {
	*x = AI_ACT_P33{}
	mi := &file_AI_ACT_P33_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AI_ACT_P33) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AI_ACT_P33) ProtoMessage() {}

func (x *AI_ACT_P33) ProtoReflect() protoreflect.Message {
	mi := &file_AI_ACT_P33_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AI_ACT_P33.ProtoReflect.Descriptor instead.
func (*AI_ACT_P33) Descriptor() ([]byte, []int) {
	return file_AI_ACT_P33_proto_rawDescGZIP(), []int{0}
}

func (x *AI_ACT_P33) GetAiPos() *CHAPTERCELLPOS_P33 {
	if x != nil {
		return x.AiPos
	}
	return nil
}

func (x *AI_ACT_P33) GetStrategyId() uint32 {
	if x != nil && x.StrategyId != nil {
		return *x.StrategyId
	}
	return 0
}

func (x *AI_ACT_P33) GetTargetPos() *CHAPTERCELLPOS_P33 {
	if x != nil {
		return x.TargetPos
	}
	return nil
}

func (x *AI_ACT_P33) GetMovePath() []*CHAPTERCELLPOS_P33 {
	if x != nil {
		return x.MovePath
	}
	return nil
}

func (x *AI_ACT_P33) GetShipUpdate() []*SHIPINCHAPTER_P33 {
	if x != nil {
		return x.ShipUpdate
	}
	return nil
}

func (x *AI_ACT_P33) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *AI_ACT_P33) GetPosList() []*WORLDPOSINFO {
	if x != nil {
		return x.PosList
	}
	return nil
}

var File_AI_ACT_P33_proto protoreflect.FileDescriptor

const file_AI_ACT_P33_proto_rawDesc = "" +
	"\n" +
	"\x10AI_ACT_P33.proto\x12\abelfast\x1a\x18CHAPTERCELLPOS_P33.proto\x1a\x17SHIPINCHAPTER_P33.proto\x1a\x12WORLDPOSINFO.proto\"\xda\x02\n" +
	"\n" +
	"AI_ACT_P33\x122\n" +
	"\x06ai_pos\x18\x01 \x02(\v2\x1b.belfast.CHAPTERCELLPOS_P33R\x05aiPos\x12\x1f\n" +
	"\vstrategy_id\x18\x02 \x01(\rR\n" +
	"strategyId\x12:\n" +
	"\n" +
	"target_pos\x18\x03 \x01(\v2\x1b.belfast.CHAPTERCELLPOS_P33R\ttargetPos\x128\n" +
	"\tmove_path\x18\x04 \x03(\v2\x1b.belfast.CHAPTERCELLPOS_P33R\bmovePath\x12;\n" +
	"\vship_update\x18\x06 \x03(\v2\x1a.belfast.SHIPINCHAPTER_P33R\n" +
	"shipUpdate\x12\x12\n" +
	"\x04type\x18\a \x02(\rR\x04type\x120\n" +
	"\bpos_list\x18\b \x03(\v2\x15.belfast.WORLDPOSINFOR\aposListB\fZ\n" +
	"./protobuf"

var (
	file_AI_ACT_P33_proto_rawDescOnce sync.Once
	file_AI_ACT_P33_proto_rawDescData []byte
)

func file_AI_ACT_P33_proto_rawDescGZIP() []byte {
	file_AI_ACT_P33_proto_rawDescOnce.Do(func() {
		file_AI_ACT_P33_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AI_ACT_P33_proto_rawDesc), len(file_AI_ACT_P33_proto_rawDesc)))
	})
	return file_AI_ACT_P33_proto_rawDescData
}

var file_AI_ACT_P33_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AI_ACT_P33_proto_goTypes = []any{
	(*AI_ACT_P33)(nil),         // 0: belfast.AI_ACT_P33
	(*CHAPTERCELLPOS_P33)(nil), // 1: belfast.CHAPTERCELLPOS_P33
	(*SHIPINCHAPTER_P33)(nil),  // 2: belfast.SHIPINCHAPTER_P33
	(*WORLDPOSINFO)(nil),       // 3: belfast.WORLDPOSINFO
}
var file_AI_ACT_P33_proto_depIdxs = []int32{
	1, // 0: belfast.AI_ACT_P33.ai_pos:type_name -> belfast.CHAPTERCELLPOS_P33
	1, // 1: belfast.AI_ACT_P33.target_pos:type_name -> belfast.CHAPTERCELLPOS_P33
	1, // 2: belfast.AI_ACT_P33.move_path:type_name -> belfast.CHAPTERCELLPOS_P33
	2, // 3: belfast.AI_ACT_P33.ship_update:type_name -> belfast.SHIPINCHAPTER_P33
	3, // 4: belfast.AI_ACT_P33.pos_list:type_name -> belfast.WORLDPOSINFO
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_AI_ACT_P33_proto_init() }
func file_AI_ACT_P33_proto_init() {
	if File_AI_ACT_P33_proto != nil {
		return
	}
	file_CHAPTERCELLPOS_P33_proto_init()
	file_SHIPINCHAPTER_P33_proto_init()
	file_WORLDPOSINFO_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AI_ACT_P33_proto_rawDesc), len(file_AI_ACT_P33_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AI_ACT_P33_proto_goTypes,
		DependencyIndexes: file_AI_ACT_P33_proto_depIdxs,
		MessageInfos:      file_AI_ACT_P33_proto_msgTypes,
	}.Build()
	File_AI_ACT_P33_proto = out.File
	file_AI_ACT_P33_proto_goTypes = nil
	file_AI_ACT_P33_proto_depIdxs = nil
}
