// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: APPRECIATIONINFO.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APPRECIATIONINFO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gallerys      []uint32               `protobuf:"varint,1,rep,name=gallerys" json:"gallerys,omitempty"`
	Musics        []uint32               `protobuf:"varint,2,rep,name=musics" json:"musics,omitempty"`
	FavorGallerys []uint32               `protobuf:"varint,3,rep,name=favor_gallerys,json=favorGallerys" json:"favor_gallerys,omitempty"`
	FavorMusics   []uint32               `protobuf:"varint,4,rep,name=favor_musics,json=favorMusics" json:"favor_musics,omitempty"`
	MusicNo       *uint32                `protobuf:"varint,5,req,name=music_no,json=musicNo" json:"music_no,omitempty"`
	MusicMode     *uint32                `protobuf:"varint,6,req,name=music_mode,json=musicMode" json:"music_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APPRECIATIONINFO) Reset() {
	*x = APPRECIATIONINFO{}
	mi := &file_APPRECIATIONINFO_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APPRECIATIONINFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APPRECIATIONINFO) ProtoMessage() {}

func (x *APPRECIATIONINFO) ProtoReflect() protoreflect.Message {
	mi := &file_APPRECIATIONINFO_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APPRECIATIONINFO.ProtoReflect.Descriptor instead.
func (*APPRECIATIONINFO) Descriptor() ([]byte, []int) {
	return file_APPRECIATIONINFO_proto_rawDescGZIP(), []int{0}
}

func (x *APPRECIATIONINFO) GetGallerys() []uint32 {
	if x != nil {
		return x.Gallerys
	}
	return nil
}

func (x *APPRECIATIONINFO) GetMusics() []uint32 {
	if x != nil {
		return x.Musics
	}
	return nil
}

func (x *APPRECIATIONINFO) GetFavorGallerys() []uint32 {
	if x != nil {
		return x.FavorGallerys
	}
	return nil
}

func (x *APPRECIATIONINFO) GetFavorMusics() []uint32 {
	if x != nil {
		return x.FavorMusics
	}
	return nil
}

func (x *APPRECIATIONINFO) GetMusicNo() uint32 {
	if x != nil && x.MusicNo != nil {
		return *x.MusicNo
	}
	return 0
}

func (x *APPRECIATIONINFO) GetMusicMode() uint32 {
	if x != nil && x.MusicMode != nil {
		return *x.MusicMode
	}
	return 0
}

var File_APPRECIATIONINFO_proto protoreflect.FileDescriptor

const file_APPRECIATIONINFO_proto_rawDesc = "" +
	"\n" +
	"\x16APPRECIATIONINFO.proto\x12\abelfast\"\xca\x01\n" +
	"\x10APPRECIATIONINFO\x12\x1a\n" +
	"\bgallerys\x18\x01 \x03(\rR\bgallerys\x12\x16\n" +
	"\x06musics\x18\x02 \x03(\rR\x06musics\x12%\n" +
	"\x0efavor_gallerys\x18\x03 \x03(\rR\rfavorGallerys\x12!\n" +
	"\ffavor_musics\x18\x04 \x03(\rR\vfavorMusics\x12\x19\n" +
	"\bmusic_no\x18\x05 \x02(\rR\amusicNo\x12\x1d\n" +
	"\n" +
	"music_mode\x18\x06 \x02(\rR\tmusicModeB\fZ\n" +
	"./protobuf"

var (
	file_APPRECIATIONINFO_proto_rawDescOnce sync.Once
	file_APPRECIATIONINFO_proto_rawDescData []byte
)

func file_APPRECIATIONINFO_proto_rawDescGZIP() []byte {
	file_APPRECIATIONINFO_proto_rawDescOnce.Do(func() {
		file_APPRECIATIONINFO_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_APPRECIATIONINFO_proto_rawDesc), len(file_APPRECIATIONINFO_proto_rawDesc)))
	})
	return file_APPRECIATIONINFO_proto_rawDescData
}

var file_APPRECIATIONINFO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_APPRECIATIONINFO_proto_goTypes = []any{
	(*APPRECIATIONINFO)(nil), // 0: belfast.APPRECIATIONINFO
}
var file_APPRECIATIONINFO_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_APPRECIATIONINFO_proto_init() }
func file_APPRECIATIONINFO_proto_init() {
	if File_APPRECIATIONINFO_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_APPRECIATIONINFO_proto_rawDesc), len(file_APPRECIATIONINFO_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_APPRECIATIONINFO_proto_goTypes,
		DependencyIndexes: file_APPRECIATIONINFO_proto_depIdxs,
		MessageInfos:      file_APPRECIATIONINFO_proto_msgTypes,
	}.Build()
	File_APPRECIATIONINFO_proto = out.File
	file_APPRECIATIONINFO_proto_goTypes = nil
	file_APPRECIATIONINFO_proto_depIdxs = nil
}
