// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ATTRINFO.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ATTRINFO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         *uint32                `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	Exp           *uint32                `protobuf:"varint,2,req,name=exp" json:"exp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ATTRINFO) Reset() {
	*x = ATTRINFO{}
	mi := &file_ATTRINFO_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ATTRINFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ATTRINFO) ProtoMessage() {}

func (x *ATTRINFO) ProtoReflect() protoreflect.Message {
	mi := &file_ATTRINFO_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ATTRINFO.ProtoReflect.Descriptor instead.
func (*ATTRINFO) Descriptor() ([]byte, []int) {
	return file_ATTRINFO_proto_rawDescGZIP(), []int{0}
}

func (x *ATTRINFO) GetLevel() uint32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *ATTRINFO) GetExp() uint32 {
	if x != nil && x.Exp != nil {
		return *x.Exp
	}
	return 0
}

var File_ATTRINFO_proto protoreflect.FileDescriptor

const file_ATTRINFO_proto_rawDesc = "" +
	"\n" +
	"\x0eATTRINFO.proto\x12\abelfast\"2\n" +
	"\bATTRINFO\x12\x14\n" +
	"\x05level\x18\x01 \x02(\rR\x05level\x12\x10\n" +
	"\x03exp\x18\x02 \x02(\rR\x03expB\fZ\n" +
	"./protobuf"

var (
	file_ATTRINFO_proto_rawDescOnce sync.Once
	file_ATTRINFO_proto_rawDescData []byte
)

func file_ATTRINFO_proto_rawDescGZIP() []byte {
	file_ATTRINFO_proto_rawDescOnce.Do(func() {
		file_ATTRINFO_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ATTRINFO_proto_rawDesc), len(file_ATTRINFO_proto_rawDesc)))
	})
	return file_ATTRINFO_proto_rawDescData
}

var file_ATTRINFO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ATTRINFO_proto_goTypes = []any{
	(*ATTRINFO)(nil), // 0: belfast.ATTRINFO
}
var file_ATTRINFO_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ATTRINFO_proto_init() }
func file_ATTRINFO_proto_init() {
	if File_ATTRINFO_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ATTRINFO_proto_rawDesc), len(file_ATTRINFO_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ATTRINFO_proto_goTypes,
		DependencyIndexes: file_ATTRINFO_proto_depIdxs,
		MessageInfos:      file_ATTRINFO_proto_msgTypes,
	}.Build()
	File_ATTRINFO_proto = out.File
	file_ATTRINFO_proto_goTypes = nil
	file_ATTRINFO_proto_depIdxs = nil
}
