// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CELLFLAG.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CELLFLAG struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *CHAPTERCELLPOS        `protobuf:"bytes,1,req,name=pos" json:"pos,omitempty"`
	FlagList      []uint32               `protobuf:"varint,2,rep,name=flag_list,json=flagList" json:"flag_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CELLFLAG) Reset() {
	*x = CELLFLAG{}
	mi := &file_CELLFLAG_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CELLFLAG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CELLFLAG) ProtoMessage() {}

func (x *CELLFLAG) ProtoReflect() protoreflect.Message {
	mi := &file_CELLFLAG_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CELLFLAG.ProtoReflect.Descriptor instead.
func (*CELLFLAG) Descriptor() ([]byte, []int) {
	return file_CELLFLAG_proto_rawDescGZIP(), []int{0}
}

func (x *CELLFLAG) GetPos() *CHAPTERCELLPOS {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *CELLFLAG) GetFlagList() []uint32 {
	if x != nil {
		return x.FlagList
	}
	return nil
}

var File_CELLFLAG_proto protoreflect.FileDescriptor

const file_CELLFLAG_proto_rawDesc = "" +
	"\n" +
	"\x0eCELLFLAG.proto\x12\abelfast\x1a\x14CHAPTERCELLPOS.proto\"R\n" +
	"\bCELLFLAG\x12)\n" +
	"\x03pos\x18\x01 \x02(\v2\x17.belfast.CHAPTERCELLPOSR\x03pos\x12\x1b\n" +
	"\tflag_list\x18\x02 \x03(\rR\bflagListB\fZ\n" +
	"./protobuf"

var (
	file_CELLFLAG_proto_rawDescOnce sync.Once
	file_CELLFLAG_proto_rawDescData []byte
)

func file_CELLFLAG_proto_rawDescGZIP() []byte {
	file_CELLFLAG_proto_rawDescOnce.Do(func() {
		file_CELLFLAG_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CELLFLAG_proto_rawDesc), len(file_CELLFLAG_proto_rawDesc)))
	})
	return file_CELLFLAG_proto_rawDescData
}

var file_CELLFLAG_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CELLFLAG_proto_goTypes = []any{
	(*CELLFLAG)(nil),       // 0: belfast.CELLFLAG
	(*CHAPTERCELLPOS)(nil), // 1: belfast.CHAPTERCELLPOS
}
var file_CELLFLAG_proto_depIdxs = []int32{
	1, // 0: belfast.CELLFLAG.pos:type_name -> belfast.CHAPTERCELLPOS
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CELLFLAG_proto_init() }
func file_CELLFLAG_proto_init() {
	if File_CELLFLAG_proto != nil {
		return
	}
	file_CHAPTERCELLPOS_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CELLFLAG_proto_rawDesc), len(file_CELLFLAG_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CELLFLAG_proto_goTypes,
		DependencyIndexes: file_CELLFLAG_proto_depIdxs,
		MessageInfos:      file_CELLFLAG_proto_msgTypes,
	}.Build()
	File_CELLFLAG_proto = out.File
	file_CELLFLAG_proto_goTypes = nil
	file_CELLFLAG_proto_depIdxs = nil
}
