// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CHAPTERINFO.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CHAPTERINFO struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Progress         *uint32                `protobuf:"varint,2,req,name=progress" json:"progress,omitempty"`
	KillBossCount    *uint32                `protobuf:"varint,3,req,name=kill_boss_count,json=killBossCount" json:"kill_boss_count,omitempty"`
	KillEnemyCount   *uint32                `protobuf:"varint,4,req,name=kill_enemy_count,json=killEnemyCount" json:"kill_enemy_count,omitempty"`
	TakeBoxCount     *uint32                `protobuf:"varint,5,req,name=take_box_count,json=takeBoxCount" json:"take_box_count,omitempty"`
	DefeatCount      *uint32                `protobuf:"varint,6,req,name=defeat_count,json=defeatCount" json:"defeat_count,omitempty"`
	TodayDefeatCount *uint32                `protobuf:"varint,7,req,name=today_defeat_count,json=todayDefeatCount" json:"today_defeat_count,omitempty"`
	PassCount        *uint32                `protobuf:"varint,8,req,name=pass_count,json=passCount" json:"pass_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CHAPTERINFO) Reset() {
	*x = CHAPTERINFO{}
	mi := &file_CHAPTERINFO_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CHAPTERINFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CHAPTERINFO) ProtoMessage() {}

func (x *CHAPTERINFO) ProtoReflect() protoreflect.Message {
	mi := &file_CHAPTERINFO_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CHAPTERINFO.ProtoReflect.Descriptor instead.
func (*CHAPTERINFO) Descriptor() ([]byte, []int) {
	return file_CHAPTERINFO_proto_rawDescGZIP(), []int{0}
}

func (x *CHAPTERINFO) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *CHAPTERINFO) GetProgress() uint32 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

func (x *CHAPTERINFO) GetKillBossCount() uint32 {
	if x != nil && x.KillBossCount != nil {
		return *x.KillBossCount
	}
	return 0
}

func (x *CHAPTERINFO) GetKillEnemyCount() uint32 {
	if x != nil && x.KillEnemyCount != nil {
		return *x.KillEnemyCount
	}
	return 0
}

func (x *CHAPTERINFO) GetTakeBoxCount() uint32 {
	if x != nil && x.TakeBoxCount != nil {
		return *x.TakeBoxCount
	}
	return 0
}

func (x *CHAPTERINFO) GetDefeatCount() uint32 {
	if x != nil && x.DefeatCount != nil {
		return *x.DefeatCount
	}
	return 0
}

func (x *CHAPTERINFO) GetTodayDefeatCount() uint32 {
	if x != nil && x.TodayDefeatCount != nil {
		return *x.TodayDefeatCount
	}
	return 0
}

func (x *CHAPTERINFO) GetPassCount() uint32 {
	if x != nil && x.PassCount != nil {
		return *x.PassCount
	}
	return 0
}

var File_CHAPTERINFO_proto protoreflect.FileDescriptor

const file_CHAPTERINFO_proto_rawDesc = "" +
	"\n" +
	"\x11CHAPTERINFO.proto\x12\abelfast\"\xa1\x02\n" +
	"\vCHAPTERINFO\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x1a\n" +
	"\bprogress\x18\x02 \x02(\rR\bprogress\x12&\n" +
	"\x0fkill_boss_count\x18\x03 \x02(\rR\rkillBossCount\x12(\n" +
	"\x10kill_enemy_count\x18\x04 \x02(\rR\x0ekillEnemyCount\x12$\n" +
	"\x0etake_box_count\x18\x05 \x02(\rR\ftakeBoxCount\x12!\n" +
	"\fdefeat_count\x18\x06 \x02(\rR\vdefeatCount\x12,\n" +
	"\x12today_defeat_count\x18\a \x02(\rR\x10todayDefeatCount\x12\x1d\n" +
	"\n" +
	"pass_count\x18\b \x02(\rR\tpassCountB\fZ\n" +
	"./protobuf"

var (
	file_CHAPTERINFO_proto_rawDescOnce sync.Once
	file_CHAPTERINFO_proto_rawDescData []byte
)

func file_CHAPTERINFO_proto_rawDescGZIP() []byte {
	file_CHAPTERINFO_proto_rawDescOnce.Do(func() {
		file_CHAPTERINFO_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CHAPTERINFO_proto_rawDesc), len(file_CHAPTERINFO_proto_rawDesc)))
	})
	return file_CHAPTERINFO_proto_rawDescData
}

var file_CHAPTERINFO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CHAPTERINFO_proto_goTypes = []any{
	(*CHAPTERINFO)(nil), // 0: belfast.CHAPTERINFO
}
var file_CHAPTERINFO_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CHAPTERINFO_proto_init() }
func file_CHAPTERINFO_proto_init() {
	if File_CHAPTERINFO_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CHAPTERINFO_proto_rawDesc), len(file_CHAPTERINFO_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CHAPTERINFO_proto_goTypes,
		DependencyIndexes: file_CHAPTERINFO_proto_depIdxs,
		MessageInfos:      file_CHAPTERINFO_proto_msgTypes,
	}.Build()
	File_CHAPTERINFO_proto = out.File
	file_CHAPTERINFO_proto_goTypes = nil
	file_CHAPTERINFO_proto_depIdxs = nil
}
