// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CHAPTERCELLINFO.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CHAPTERCELLINFO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *CHAPTERCELLPOS        `protobuf:"bytes,1,req,name=pos" json:"pos,omitempty"`
	Discovered    *uint32                `protobuf:"varint,2,opt,name=discovered" json:"discovered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CHAPTERCELLINFO) Reset() {
	*x = CHAPTERCELLINFO{}
	mi := &file_CHAPTERCELLINFO_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CHAPTERCELLINFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CHAPTERCELLINFO) ProtoMessage() {}

func (x *CHAPTERCELLINFO) ProtoReflect() protoreflect.Message {
	mi := &file_CHAPTERCELLINFO_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CHAPTERCELLINFO.ProtoReflect.Descriptor instead.
func (*CHAPTERCELLINFO) Descriptor() ([]byte, []int) {
	return file_CHAPTERCELLINFO_proto_rawDescGZIP(), []int{0}
}

func (x *CHAPTERCELLINFO) GetPos() *CHAPTERCELLPOS {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *CHAPTERCELLINFO) GetDiscovered() uint32 {
	if x != nil && x.Discovered != nil {
		return *x.Discovered
	}
	return 0
}

var File_CHAPTERCELLINFO_proto protoreflect.FileDescriptor

const file_CHAPTERCELLINFO_proto_rawDesc = "" +
	"\n" +
	"\x15CHAPTERCELLINFO.proto\x12\abelfast\x1a\x14CHAPTERCELLPOS.proto\"\\\n" +
	"\x0fCHAPTERCELLINFO\x12)\n" +
	"\x03pos\x18\x01 \x02(\v2\x17.belfast.CHAPTERCELLPOSR\x03pos\x12\x1e\n" +
	"\n" +
	"discovered\x18\x02 \x01(\rR\n" +
	"discoveredB\fZ\n" +
	"./protobuf"

var (
	file_CHAPTERCELLINFO_proto_rawDescOnce sync.Once
	file_CHAPTERCELLINFO_proto_rawDescData []byte
)

func file_CHAPTERCELLINFO_proto_rawDescGZIP() []byte {
	file_CHAPTERCELLINFO_proto_rawDescOnce.Do(func() {
		file_CHAPTERCELLINFO_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CHAPTERCELLINFO_proto_rawDesc), len(file_CHAPTERCELLINFO_proto_rawDesc)))
	})
	return file_CHAPTERCELLINFO_proto_rawDescData
}

var file_CHAPTERCELLINFO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CHAPTERCELLINFO_proto_goTypes = []any{
	(*CHAPTERCELLINFO)(nil), // 0: belfast.CHAPTERCELLINFO
	(*CHAPTERCELLPOS)(nil),  // 1: belfast.CHAPTERCELLPOS
}
var file_CHAPTERCELLINFO_proto_depIdxs = []int32{
	1, // 0: belfast.CHAPTERCELLINFO.pos:type_name -> belfast.CHAPTERCELLPOS
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CHAPTERCELLINFO_proto_init() }
func file_CHAPTERCELLINFO_proto_init() {
	if File_CHAPTERCELLINFO_proto != nil {
		return
	}
	file_CHAPTERCELLPOS_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CHAPTERCELLINFO_proto_rawDesc), len(file_CHAPTERCELLINFO_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CHAPTERCELLINFO_proto_goTypes,
		DependencyIndexes: file_CHAPTERCELLINFO_proto_depIdxs,
		MessageInfos:      file_CHAPTERCELLINFO_proto_msgTypes,
	}.Build()
	File_CHAPTERCELLINFO_proto = out.File
	file_CHAPTERCELLINFO_proto_goTypes = nil
	file_CHAPTERCELLINFO_proto_depIdxs = nil
}
