// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CHILD_SITE_OPTION.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CHILD_SITE_OPTION struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        *uint32                `protobuf:"varint,1,req,name=site_id,json=siteId" json:"site_id,omitempty"`
	OptionIds     []uint32               `protobuf:"varint,2,rep,name=option_ids,json=optionIds" json:"option_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CHILD_SITE_OPTION) Reset() {
	*x = CHILD_SITE_OPTION{}
	mi := &file_CHILD_SITE_OPTION_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CHILD_SITE_OPTION) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CHILD_SITE_OPTION) ProtoMessage() {}

func (x *CHILD_SITE_OPTION) ProtoReflect() protoreflect.Message {
	mi := &file_CHILD_SITE_OPTION_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CHILD_SITE_OPTION.ProtoReflect.Descriptor instead.
func (*CHILD_SITE_OPTION) Descriptor() ([]byte, []int) {
	return file_CHILD_SITE_OPTION_proto_rawDescGZIP(), []int{0}
}

func (x *CHILD_SITE_OPTION) GetSiteId() uint32 {
	if x != nil && x.SiteId != nil {
		return *x.SiteId
	}
	return 0
}

func (x *CHILD_SITE_OPTION) GetOptionIds() []uint32 {
	if x != nil {
		return x.OptionIds
	}
	return nil
}

var File_CHILD_SITE_OPTION_proto protoreflect.FileDescriptor

const file_CHILD_SITE_OPTION_proto_rawDesc = "" +
	"\n" +
	"\x17CHILD_SITE_OPTION.proto\x12\abelfast\"K\n" +
	"\x11CHILD_SITE_OPTION\x12\x17\n" +
	"\asite_id\x18\x01 \x02(\rR\x06siteId\x12\x1d\n" +
	"\n" +
	"option_ids\x18\x02 \x03(\rR\toptionIdsB\fZ\n" +
	"./protobuf"

var (
	file_CHILD_SITE_OPTION_proto_rawDescOnce sync.Once
	file_CHILD_SITE_OPTION_proto_rawDescData []byte
)

func file_CHILD_SITE_OPTION_proto_rawDescGZIP() []byte {
	file_CHILD_SITE_OPTION_proto_rawDescOnce.Do(func() {
		file_CHILD_SITE_OPTION_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CHILD_SITE_OPTION_proto_rawDesc), len(file_CHILD_SITE_OPTION_proto_rawDesc)))
	})
	return file_CHILD_SITE_OPTION_proto_rawDescData
}

var file_CHILD_SITE_OPTION_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CHILD_SITE_OPTION_proto_goTypes = []any{
	(*CHILD_SITE_OPTION)(nil), // 0: belfast.CHILD_SITE_OPTION
}
var file_CHILD_SITE_OPTION_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CHILD_SITE_OPTION_proto_init() }
func file_CHILD_SITE_OPTION_proto_init() {
	if File_CHILD_SITE_OPTION_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CHILD_SITE_OPTION_proto_rawDesc), len(file_CHILD_SITE_OPTION_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CHILD_SITE_OPTION_proto_goTypes,
		DependencyIndexes: file_CHILD_SITE_OPTION_proto_depIdxs,
		MessageInfos:      file_CHILD_SITE_OPTION_proto_msgTypes,
	}.Build()
	File_CHILD_SITE_OPTION_proto = out.File
	file_CHILD_SITE_OPTION_proto_goTypes = nil
	file_CHILD_SITE_OPTION_proto_depIdxs = nil
}
