// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CHILD_INFO.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CHILD_INFO struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Tid                     *uint32                `protobuf:"varint,1,req,name=tid" json:"tid,omitempty"`
	CurTime                 *CHILD_TIME            `protobuf:"bytes,2,req,name=cur_time,json=curTime" json:"cur_time,omitempty"`
	Mood                    *uint32                `protobuf:"varint,3,req,name=mood" json:"mood,omitempty"`
	Money                   *uint32                `protobuf:"varint,4,req,name=money" json:"money,omitempty"`
	SiteNumber              *uint32                `protobuf:"varint,5,req,name=site_number,json=siteNumber" json:"site_number,omitempty"`
	Attrs                   []*CHILD_ATTR          `protobuf:"bytes,6,rep,name=attrs" json:"attrs,omitempty"`
	Favor                   *CHILD_FAVOR           `protobuf:"bytes,7,req,name=favor" json:"favor,omitempty"`
	Items                   []*CHILD_ITEM          `protobuf:"bytes,8,rep,name=items" json:"items,omitempty"`
	PlanHistory             []*CHILD_PLAN_HISTORY  `protobuf:"bytes,9,rep,name=plan_history,json=planHistory" json:"plan_history,omitempty"`
	Memorys                 []uint32               `protobuf:"varint,10,rep,name=memorys" json:"memorys,omitempty"`
	Plans                   []*CHILD_PLAN_CELL     `protobuf:"bytes,11,rep,name=plans" json:"plans,omitempty"`
	Polaroids               []*CHILD_POLAROID      `protobuf:"bytes,12,rep,name=polaroids" json:"polaroids,omitempty"`
	Target                  *uint32                `protobuf:"varint,13,req,name=target" json:"target,omitempty"`
	Tasks                   []*CHILD_TASK          `protobuf:"bytes,14,rep,name=tasks" json:"tasks,omitempty"`
	RealizedWish            []uint32               `protobuf:"varint,15,rep,name=realized_wish,json=realizedWish" json:"realized_wish,omitempty"`
	Buffs                   []*CHILD_BUFF          `protobuf:"bytes,16,rep,name=buffs" json:"buffs,omitempty"`
	UserName                *string                `protobuf:"bytes,17,req,name=user_name,json=userName" json:"user_name,omitempty"`
	SpecEvents              []uint32               `protobuf:"varint,18,rep,name=spec_events,json=specEvents" json:"spec_events,omitempty"`
	CanTriggerHomeEvent     *uint32                `protobuf:"varint,19,req,name=can_trigger_home_event,json=canTriggerHomeEvent" json:"can_trigger_home_event,omitempty"`
	HomeEvents              []uint32               `protobuf:"varint,20,rep,name=home_events,json=homeEvents" json:"home_events,omitempty"`
	DiscountEventId         []uint32               `protobuf:"varint,21,rep,name=discount_event_id,json=discountEventId" json:"discount_event_id,omitempty"`
	Shop                    []*CHILD_SHOP_DATA     `protobuf:"bytes,22,rep,name=shop" json:"shop,omitempty"`
	OptionRecords           []*CHILD_OPTION_RECORD `protobuf:"bytes,23,rep,name=option_records,json=optionRecords" json:"option_records,omitempty"`
	FavorAwardHistory       []uint32               `protobuf:"varint,24,rep,name=favor_award_history,json=favorAwardHistory" json:"favor_award_history,omitempty"`
	IsEnding                *uint32                `protobuf:"varint,25,req,name=is_ending,json=isEnding" json:"is_ending,omitempty"`
	NewGamePlusCount        *uint32                `protobuf:"varint,26,req,name=new_game_plus_count,json=newGamePlusCount" json:"new_game_plus_count,omitempty"`
	HadTargetStageAward     *uint32                `protobuf:"varint,27,req,name=had_target_stage_award,json=hadTargetStageAward" json:"had_target_stage_award,omitempty"`
	HadAdjustment           *uint32                `protobuf:"varint,28,req,name=had_adjustment,json=hadAdjustment" json:"had_adjustment,omitempty"`
	IsSpecialSecretaryValid *uint32                `protobuf:"varint,29,req,name=is_special_secretary_valid,json=isSpecialSecretaryValid" json:"is_special_secretary_valid,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CHILD_INFO) Reset() {
	*x = CHILD_INFO{}
	mi := &file_CHILD_INFO_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CHILD_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CHILD_INFO) ProtoMessage() {}

func (x *CHILD_INFO) ProtoReflect() protoreflect.Message {
	mi := &file_CHILD_INFO_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CHILD_INFO.ProtoReflect.Descriptor instead.
func (*CHILD_INFO) Descriptor() ([]byte, []int) {
	return file_CHILD_INFO_proto_rawDescGZIP(), []int{0}
}

func (x *CHILD_INFO) GetTid() uint32 {
	if x != nil && x.Tid != nil {
		return *x.Tid
	}
	return 0
}

func (x *CHILD_INFO) GetCurTime() *CHILD_TIME {
	if x != nil {
		return x.CurTime
	}
	return nil
}

func (x *CHILD_INFO) GetMood() uint32 {
	if x != nil && x.Mood != nil {
		return *x.Mood
	}
	return 0
}

func (x *CHILD_INFO) GetMoney() uint32 {
	if x != nil && x.Money != nil {
		return *x.Money
	}
	return 0
}

func (x *CHILD_INFO) GetSiteNumber() uint32 {
	if x != nil && x.SiteNumber != nil {
		return *x.SiteNumber
	}
	return 0
}

func (x *CHILD_INFO) GetAttrs() []*CHILD_ATTR {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *CHILD_INFO) GetFavor() *CHILD_FAVOR {
	if x != nil {
		return x.Favor
	}
	return nil
}

func (x *CHILD_INFO) GetItems() []*CHILD_ITEM {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CHILD_INFO) GetPlanHistory() []*CHILD_PLAN_HISTORY {
	if x != nil {
		return x.PlanHistory
	}
	return nil
}

func (x *CHILD_INFO) GetMemorys() []uint32 {
	if x != nil {
		return x.Memorys
	}
	return nil
}

func (x *CHILD_INFO) GetPlans() []*CHILD_PLAN_CELL {
	if x != nil {
		return x.Plans
	}
	return nil
}

func (x *CHILD_INFO) GetPolaroids() []*CHILD_POLAROID {
	if x != nil {
		return x.Polaroids
	}
	return nil
}

func (x *CHILD_INFO) GetTarget() uint32 {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return 0
}

func (x *CHILD_INFO) GetTasks() []*CHILD_TASK {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *CHILD_INFO) GetRealizedWish() []uint32 {
	if x != nil {
		return x.RealizedWish
	}
	return nil
}

func (x *CHILD_INFO) GetBuffs() []*CHILD_BUFF {
	if x != nil {
		return x.Buffs
	}
	return nil
}

func (x *CHILD_INFO) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *CHILD_INFO) GetSpecEvents() []uint32 {
	if x != nil {
		return x.SpecEvents
	}
	return nil
}

func (x *CHILD_INFO) GetCanTriggerHomeEvent() uint32 {
	if x != nil && x.CanTriggerHomeEvent != nil {
		return *x.CanTriggerHomeEvent
	}
	return 0
}

func (x *CHILD_INFO) GetHomeEvents() []uint32 {
	if x != nil {
		return x.HomeEvents
	}
	return nil
}

func (x *CHILD_INFO) GetDiscountEventId() []uint32 {
	if x != nil {
		return x.DiscountEventId
	}
	return nil
}

func (x *CHILD_INFO) GetShop() []*CHILD_SHOP_DATA {
	if x != nil {
		return x.Shop
	}
	return nil
}

func (x *CHILD_INFO) GetOptionRecords() []*CHILD_OPTION_RECORD {
	if x != nil {
		return x.OptionRecords
	}
	return nil
}

func (x *CHILD_INFO) GetFavorAwardHistory() []uint32 {
	if x != nil {
		return x.FavorAwardHistory
	}
	return nil
}

func (x *CHILD_INFO) GetIsEnding() uint32 {
	if x != nil && x.IsEnding != nil {
		return *x.IsEnding
	}
	return 0
}

func (x *CHILD_INFO) GetNewGamePlusCount() uint32 {
	if x != nil && x.NewGamePlusCount != nil {
		return *x.NewGamePlusCount
	}
	return 0
}

func (x *CHILD_INFO) GetHadTargetStageAward() uint32 {
	if x != nil && x.HadTargetStageAward != nil {
		return *x.HadTargetStageAward
	}
	return 0
}

func (x *CHILD_INFO) GetHadAdjustment() uint32 {
	if x != nil && x.HadAdjustment != nil {
		return *x.HadAdjustment
	}
	return 0
}

func (x *CHILD_INFO) GetIsSpecialSecretaryValid() uint32 {
	if x != nil && x.IsSpecialSecretaryValid != nil {
		return *x.IsSpecialSecretaryValid
	}
	return 0
}

var File_CHILD_INFO_proto protoreflect.FileDescriptor

const file_CHILD_INFO_proto_rawDesc = "" +
	"\n" +
	"\x10CHILD_INFO.proto\x12\abelfast\x1a\x10CHILD_ATTR.proto\x1a\x10CHILD_BUFF.proto\x1a\x11CHILD_FAVOR.proto\x1a\x10CHILD_ITEM.proto\x1a\x19CHILD_OPTION_RECORD.proto\x1a\x15CHILD_PLAN_CELL.proto\x1a\x18CHILD_PLAN_HISTORY.proto\x1a\x14CHILD_POLAROID.proto\x1a\x15CHILD_SHOP_DATA.proto\x1a\x10CHILD_TASK.proto\x1a\x10CHILD_TIME.proto\"\xb7\t\n" +
	"\n" +
	"CHILD_INFO\x12\x10\n" +
	"\x03tid\x18\x01 \x02(\rR\x03tid\x12.\n" +
	"\bcur_time\x18\x02 \x02(\v2\x13.belfast.CHILD_TIMER\acurTime\x12\x12\n" +
	"\x04mood\x18\x03 \x02(\rR\x04mood\x12\x14\n" +
	"\x05money\x18\x04 \x02(\rR\x05money\x12\x1f\n" +
	"\vsite_number\x18\x05 \x02(\rR\n" +
	"siteNumber\x12)\n" +
	"\x05attrs\x18\x06 \x03(\v2\x13.belfast.CHILD_ATTRR\x05attrs\x12*\n" +
	"\x05favor\x18\a \x02(\v2\x14.belfast.CHILD_FAVORR\x05favor\x12)\n" +
	"\x05items\x18\b \x03(\v2\x13.belfast.CHILD_ITEMR\x05items\x12>\n" +
	"\fplan_history\x18\t \x03(\v2\x1b.belfast.CHILD_PLAN_HISTORYR\vplanHistory\x12\x18\n" +
	"\amemorys\x18\n" +
	" \x03(\rR\amemorys\x12.\n" +
	"\x05plans\x18\v \x03(\v2\x18.belfast.CHILD_PLAN_CELLR\x05plans\x125\n" +
	"\tpolaroids\x18\f \x03(\v2\x17.belfast.CHILD_POLAROIDR\tpolaroids\x12\x16\n" +
	"\x06target\x18\r \x02(\rR\x06target\x12)\n" +
	"\x05tasks\x18\x0e \x03(\v2\x13.belfast.CHILD_TASKR\x05tasks\x12#\n" +
	"\rrealized_wish\x18\x0f \x03(\rR\frealizedWish\x12)\n" +
	"\x05buffs\x18\x10 \x03(\v2\x13.belfast.CHILD_BUFFR\x05buffs\x12\x1b\n" +
	"\tuser_name\x18\x11 \x02(\tR\buserName\x12\x1f\n" +
	"\vspec_events\x18\x12 \x03(\rR\n" +
	"specEvents\x123\n" +
	"\x16can_trigger_home_event\x18\x13 \x02(\rR\x13canTriggerHomeEvent\x12\x1f\n" +
	"\vhome_events\x18\x14 \x03(\rR\n" +
	"homeEvents\x12*\n" +
	"\x11discount_event_id\x18\x15 \x03(\rR\x0fdiscountEventId\x12,\n" +
	"\x04shop\x18\x16 \x03(\v2\x18.belfast.CHILD_SHOP_DATAR\x04shop\x12C\n" +
	"\x0eoption_records\x18\x17 \x03(\v2\x1c.belfast.CHILD_OPTION_RECORDR\roptionRecords\x12.\n" +
	"\x13favor_award_history\x18\x18 \x03(\rR\x11favorAwardHistory\x12\x1b\n" +
	"\tis_ending\x18\x19 \x02(\rR\bisEnding\x12-\n" +
	"\x13new_game_plus_count\x18\x1a \x02(\rR\x10newGamePlusCount\x123\n" +
	"\x16had_target_stage_award\x18\x1b \x02(\rR\x13hadTargetStageAward\x12%\n" +
	"\x0ehad_adjustment\x18\x1c \x02(\rR\rhadAdjustment\x12;\n" +
	"\x1ais_special_secretary_valid\x18\x1d \x02(\rR\x17isSpecialSecretaryValidB\fZ\n" +
	"./protobuf"

var (
	file_CHILD_INFO_proto_rawDescOnce sync.Once
	file_CHILD_INFO_proto_rawDescData []byte
)

func file_CHILD_INFO_proto_rawDescGZIP() []byte {
	file_CHILD_INFO_proto_rawDescOnce.Do(func() {
		file_CHILD_INFO_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CHILD_INFO_proto_rawDesc), len(file_CHILD_INFO_proto_rawDesc)))
	})
	return file_CHILD_INFO_proto_rawDescData
}

var file_CHILD_INFO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CHILD_INFO_proto_goTypes = []any{
	(*CHILD_INFO)(nil),          // 0: belfast.CHILD_INFO
	(*CHILD_TIME)(nil),          // 1: belfast.CHILD_TIME
	(*CHILD_ATTR)(nil),          // 2: belfast.CHILD_ATTR
	(*CHILD_FAVOR)(nil),         // 3: belfast.CHILD_FAVOR
	(*CHILD_ITEM)(nil),          // 4: belfast.CHILD_ITEM
	(*CHILD_PLAN_HISTORY)(nil),  // 5: belfast.CHILD_PLAN_HISTORY
	(*CHILD_PLAN_CELL)(nil),     // 6: belfast.CHILD_PLAN_CELL
	(*CHILD_POLAROID)(nil),      // 7: belfast.CHILD_POLAROID
	(*CHILD_TASK)(nil),          // 8: belfast.CHILD_TASK
	(*CHILD_BUFF)(nil),          // 9: belfast.CHILD_BUFF
	(*CHILD_SHOP_DATA)(nil),     // 10: belfast.CHILD_SHOP_DATA
	(*CHILD_OPTION_RECORD)(nil), // 11: belfast.CHILD_OPTION_RECORD
}
var file_CHILD_INFO_proto_depIdxs = []int32{
	1,  // 0: belfast.CHILD_INFO.cur_time:type_name -> belfast.CHILD_TIME
	2,  // 1: belfast.CHILD_INFO.attrs:type_name -> belfast.CHILD_ATTR
	3,  // 2: belfast.CHILD_INFO.favor:type_name -> belfast.CHILD_FAVOR
	4,  // 3: belfast.CHILD_INFO.items:type_name -> belfast.CHILD_ITEM
	5,  // 4: belfast.CHILD_INFO.plan_history:type_name -> belfast.CHILD_PLAN_HISTORY
	6,  // 5: belfast.CHILD_INFO.plans:type_name -> belfast.CHILD_PLAN_CELL
	7,  // 6: belfast.CHILD_INFO.polaroids:type_name -> belfast.CHILD_POLAROID
	8,  // 7: belfast.CHILD_INFO.tasks:type_name -> belfast.CHILD_TASK
	9,  // 8: belfast.CHILD_INFO.buffs:type_name -> belfast.CHILD_BUFF
	10, // 9: belfast.CHILD_INFO.shop:type_name -> belfast.CHILD_SHOP_DATA
	11, // 10: belfast.CHILD_INFO.option_records:type_name -> belfast.CHILD_OPTION_RECORD
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_CHILD_INFO_proto_init() }
func file_CHILD_INFO_proto_init() {
	if File_CHILD_INFO_proto != nil {
		return
	}
	file_CHILD_ATTR_proto_init()
	file_CHILD_BUFF_proto_init()
	file_CHILD_FAVOR_proto_init()
	file_CHILD_ITEM_proto_init()
	file_CHILD_OPTION_RECORD_proto_init()
	file_CHILD_PLAN_CELL_proto_init()
	file_CHILD_PLAN_HISTORY_proto_init()
	file_CHILD_POLAROID_proto_init()
	file_CHILD_SHOP_DATA_proto_init()
	file_CHILD_TASK_proto_init()
	file_CHILD_TIME_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CHILD_INFO_proto_rawDesc), len(file_CHILD_INFO_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CHILD_INFO_proto_goTypes,
		DependencyIndexes: file_CHILD_INFO_proto_depIdxs,
		MessageInfos:      file_CHILD_INFO_proto_msgTypes,
	}.Build()
	File_CHILD_INFO_proto = out.File
	file_CHILD_INFO_proto_goTypes = nil
	file_CHILD_INFO_proto_depIdxs = nil
}
