// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CHILD_PLAN_CELL.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CHILD_PLAN_CELL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           *uint32                `protobuf:"varint,1,req,name=day" json:"day,omitempty"`
	Index         *uint32                `protobuf:"varint,2,req,name=index" json:"index,omitempty"`
	Value         []*CHILD_PLAN_VAL      `protobuf:"bytes,3,rep,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CHILD_PLAN_CELL) Reset() {
	*x = CHILD_PLAN_CELL{}
	mi := &file_CHILD_PLAN_CELL_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CHILD_PLAN_CELL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CHILD_PLAN_CELL) ProtoMessage() {}

func (x *CHILD_PLAN_CELL) ProtoReflect() protoreflect.Message {
	mi := &file_CHILD_PLAN_CELL_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CHILD_PLAN_CELL.ProtoReflect.Descriptor instead.
func (*CHILD_PLAN_CELL) Descriptor() ([]byte, []int) {
	return file_CHILD_PLAN_CELL_proto_rawDescGZIP(), []int{0}
}

func (x *CHILD_PLAN_CELL) GetDay() uint32 {
	if x != nil && x.Day != nil {
		return *x.Day
	}
	return 0
}

func (x *CHILD_PLAN_CELL) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *CHILD_PLAN_CELL) GetValue() []*CHILD_PLAN_VAL {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_CHILD_PLAN_CELL_proto protoreflect.FileDescriptor

const file_CHILD_PLAN_CELL_proto_rawDesc = "" +
	"\n" +
	"\x15CHILD_PLAN_CELL.proto\x12\abelfast\x1a\x14CHILD_PLAN_VAL.proto\"h\n" +
	"\x0fCHILD_PLAN_CELL\x12\x10\n" +
	"\x03day\x18\x01 \x02(\rR\x03day\x12\x14\n" +
	"\x05index\x18\x02 \x02(\rR\x05index\x12-\n" +
	"\x05value\x18\x03 \x03(\v2\x17.belfast.CHILD_PLAN_VALR\x05valueB\fZ\n" +
	"./protobuf"

var (
	file_CHILD_PLAN_CELL_proto_rawDescOnce sync.Once
	file_CHILD_PLAN_CELL_proto_rawDescData []byte
)

func file_CHILD_PLAN_CELL_proto_rawDescGZIP() []byte {
	file_CHILD_PLAN_CELL_proto_rawDescOnce.Do(func() {
		file_CHILD_PLAN_CELL_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CHILD_PLAN_CELL_proto_rawDesc), len(file_CHILD_PLAN_CELL_proto_rawDesc)))
	})
	return file_CHILD_PLAN_CELL_proto_rawDescData
}

var file_CHILD_PLAN_CELL_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CHILD_PLAN_CELL_proto_goTypes = []any{
	(*CHILD_PLAN_CELL)(nil), // 0: belfast.CHILD_PLAN_CELL
	(*CHILD_PLAN_VAL)(nil),  // 1: belfast.CHILD_PLAN_VAL
}
var file_CHILD_PLAN_CELL_proto_depIdxs = []int32{
	1, // 0: belfast.CHILD_PLAN_CELL.value:type_name -> belfast.CHILD_PLAN_VAL
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CHILD_PLAN_CELL_proto_init() }
func file_CHILD_PLAN_CELL_proto_init() {
	if File_CHILD_PLAN_CELL_proto != nil {
		return
	}
	file_CHILD_PLAN_VAL_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CHILD_PLAN_CELL_proto_rawDesc), len(file_CHILD_PLAN_CELL_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CHILD_PLAN_CELL_proto_goTypes,
		DependencyIndexes: file_CHILD_PLAN_CELL_proto_depIdxs,
		MessageInfos:      file_CHILD_PLAN_CELL_proto_msgTypes,
	}.Build()
	File_CHILD_PLAN_CELL_proto = out.File
	file_CHILD_PLAN_CELL_proto_goTypes = nil
	file_CHILD_PLAN_CELL_proto_depIdxs = nil
}
