// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CS_17105.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_17105 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipGroupId   *uint32                `protobuf:"varint,1,req,name=ship_group_id,json=shipGroupId" json:"ship_group_id,omitempty"`
	DiscussId     *uint32                `protobuf:"varint,2,req,name=discuss_id,json=discussId" json:"discuss_id,omitempty"`
	GoodOrBad     *uint32                `protobuf:"varint,3,req,name=good_or_bad,json=goodOrBad" json:"good_or_bad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_17105) Reset() {
	*x = CS_17105{}
	mi := &file_CS_17105_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_17105) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_17105) ProtoMessage() {}

func (x *CS_17105) ProtoReflect() protoreflect.Message {
	mi := &file_CS_17105_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_17105.ProtoReflect.Descriptor instead.
func (*CS_17105) Descriptor() ([]byte, []int) {
	return file_CS_17105_proto_rawDescGZIP(), []int{0}
}

func (x *CS_17105) GetShipGroupId() uint32 {
	if x != nil && x.ShipGroupId != nil {
		return *x.ShipGroupId
	}
	return 0
}

func (x *CS_17105) GetDiscussId() uint32 {
	if x != nil && x.DiscussId != nil {
		return *x.DiscussId
	}
	return 0
}

func (x *CS_17105) GetGoodOrBad() uint32 {
	if x != nil && x.GoodOrBad != nil {
		return *x.GoodOrBad
	}
	return 0
}

var File_CS_17105_proto protoreflect.FileDescriptor

const file_CS_17105_proto_rawDesc = "" +
	"\n" +
	"\x0eCS_17105.proto\x12\abelfast\"m\n" +
	"\bCS_17105\x12\"\n" +
	"\rship_group_id\x18\x01 \x02(\rR\vshipGroupId\x12\x1d\n" +
	"\n" +
	"discuss_id\x18\x02 \x02(\rR\tdiscussId\x12\x1e\n" +
	"\vgood_or_bad\x18\x03 \x02(\rR\tgoodOrBadB\fZ\n" +
	"./protobuf"

var (
	file_CS_17105_proto_rawDescOnce sync.Once
	file_CS_17105_proto_rawDescData []byte
)

func file_CS_17105_proto_rawDescGZIP() []byte {
	file_CS_17105_proto_rawDescOnce.Do(func() {
		file_CS_17105_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CS_17105_proto_rawDesc), len(file_CS_17105_proto_rawDesc)))
	})
	return file_CS_17105_proto_rawDescData
}

var file_CS_17105_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CS_17105_proto_goTypes = []any{
	(*CS_17105)(nil), // 0: belfast.CS_17105
}
var file_CS_17105_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CS_17105_proto_init() }
func file_CS_17105_proto_init() {
	if File_CS_17105_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CS_17105_proto_rawDesc), len(file_CS_17105_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CS_17105_proto_goTypes,
		DependencyIndexes: file_CS_17105_proto_depIdxs,
		MessageInfos:      file_CS_17105_proto_msgTypes,
	}.Build()
	File_CS_17105_proto = out.File
	file_CS_17105_proto_goTypes = nil
	file_CS_17105_proto_depIdxs = nil
}
