// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CS_19109.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_19109 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Pos              *uint32                `protobuf:"varint,1,req,name=pos" json:"pos,omitempty"`
	Name             *string                `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	FurniturePutList []*FURNITUREPUTINFO    `protobuf:"bytes,3,rep,name=furniture_put_list,json=furniturePutList" json:"furniture_put_list,omitempty"`
	IconImageMd5     *string                `protobuf:"bytes,4,req,name=icon_image_md5,json=iconImageMd5" json:"icon_image_md5,omitempty"`
	ImageMd5         *string                `protobuf:"bytes,5,req,name=image_md5,json=imageMd5" json:"image_md5,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CS_19109) Reset() {
	*x = CS_19109{}
	mi := &file_CS_19109_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_19109) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_19109) ProtoMessage() {}

func (x *CS_19109) ProtoReflect() protoreflect.Message {
	mi := &file_CS_19109_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_19109.ProtoReflect.Descriptor instead.
func (*CS_19109) Descriptor() ([]byte, []int) {
	return file_CS_19109_proto_rawDescGZIP(), []int{0}
}

func (x *CS_19109) GetPos() uint32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

func (x *CS_19109) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CS_19109) GetFurniturePutList() []*FURNITUREPUTINFO {
	if x != nil {
		return x.FurniturePutList
	}
	return nil
}

func (x *CS_19109) GetIconImageMd5() string {
	if x != nil && x.IconImageMd5 != nil {
		return *x.IconImageMd5
	}
	return ""
}

func (x *CS_19109) GetImageMd5() string {
	if x != nil && x.ImageMd5 != nil {
		return *x.ImageMd5
	}
	return ""
}

var File_CS_19109_proto protoreflect.FileDescriptor

const file_CS_19109_proto_rawDesc = "" +
	"\n" +
	"\x0eCS_19109.proto\x12\abelfast\x1a\x16FURNITUREPUTINFO.proto\"\xbc\x01\n" +
	"\bCS_19109\x12\x10\n" +
	"\x03pos\x18\x01 \x02(\rR\x03pos\x12\x12\n" +
	"\x04name\x18\x02 \x02(\tR\x04name\x12G\n" +
	"\x12furniture_put_list\x18\x03 \x03(\v2\x19.belfast.FURNITUREPUTINFOR\x10furniturePutList\x12$\n" +
	"\x0eicon_image_md5\x18\x04 \x02(\tR\ficonImageMd5\x12\x1b\n" +
	"\timage_md5\x18\x05 \x02(\tR\bimageMd5B\fZ\n" +
	"./protobuf"

var (
	file_CS_19109_proto_rawDescOnce sync.Once
	file_CS_19109_proto_rawDescData []byte
)

func file_CS_19109_proto_rawDescGZIP() []byte {
	file_CS_19109_proto_rawDescOnce.Do(func() {
		file_CS_19109_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CS_19109_proto_rawDesc), len(file_CS_19109_proto_rawDesc)))
	})
	return file_CS_19109_proto_rawDescData
}

var file_CS_19109_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CS_19109_proto_goTypes = []any{
	(*CS_19109)(nil),         // 0: belfast.CS_19109
	(*FURNITUREPUTINFO)(nil), // 1: belfast.FURNITUREPUTINFO
}
var file_CS_19109_proto_depIdxs = []int32{
	1, // 0: belfast.CS_19109.furniture_put_list:type_name -> belfast.FURNITUREPUTINFO
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CS_19109_proto_init() }
func file_CS_19109_proto_init() {
	if File_CS_19109_proto != nil {
		return
	}
	file_FURNITUREPUTINFO_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CS_19109_proto_rawDesc), len(file_CS_19109_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CS_19109_proto_goTypes,
		DependencyIndexes: file_CS_19109_proto_depIdxs,
		MessageInfos:      file_CS_19109_proto_msgTypes,
	}.Build()
	File_CS_19109_proto = out.File
	file_CS_19109_proto_goTypes = nil
	file_CS_19109_proto_depIdxs = nil
}
