// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CS_19129.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_19129 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      *uint32                `protobuf:"varint,1,req,name=target_id,json=targetId" json:"target_id,omitempty"`
	TargetName    *string                `protobuf:"bytes,2,req,name=target_name,json=targetName" json:"target_name,omitempty"`
	ThemeId       *string                `protobuf:"bytes,3,req,name=theme_id,json=themeId" json:"theme_id,omitempty"`
	ThemeName     *string                `protobuf:"bytes,4,req,name=theme_name,json=themeName" json:"theme_name,omitempty"`
	Reason        *uint32                `protobuf:"varint,5,req,name=reason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_19129) Reset() {
	*x = CS_19129{}
	mi := &file_CS_19129_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_19129) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_19129) ProtoMessage() {}

func (x *CS_19129) ProtoReflect() protoreflect.Message {
	mi := &file_CS_19129_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_19129.ProtoReflect.Descriptor instead.
func (*CS_19129) Descriptor() ([]byte, []int) {
	return file_CS_19129_proto_rawDescGZIP(), []int{0}
}

func (x *CS_19129) GetTargetId() uint32 {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return 0
}

func (x *CS_19129) GetTargetName() string {
	if x != nil && x.TargetName != nil {
		return *x.TargetName
	}
	return ""
}

func (x *CS_19129) GetThemeId() string {
	if x != nil && x.ThemeId != nil {
		return *x.ThemeId
	}
	return ""
}

func (x *CS_19129) GetThemeName() string {
	if x != nil && x.ThemeName != nil {
		return *x.ThemeName
	}
	return ""
}

func (x *CS_19129) GetReason() uint32 {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return 0
}

var File_CS_19129_proto protoreflect.FileDescriptor

const file_CS_19129_proto_rawDesc = "" +
	"\n" +
	"\x0eCS_19129.proto\x12\abelfast\"\x9a\x01\n" +
	"\bCS_19129\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x02(\rR\btargetId\x12\x1f\n" +
	"\vtarget_name\x18\x02 \x02(\tR\n" +
	"targetName\x12\x19\n" +
	"\btheme_id\x18\x03 \x02(\tR\athemeId\x12\x1d\n" +
	"\n" +
	"theme_name\x18\x04 \x02(\tR\tthemeName\x12\x16\n" +
	"\x06reason\x18\x05 \x02(\rR\x06reasonB\fZ\n" +
	"./protobuf"

var (
	file_CS_19129_proto_rawDescOnce sync.Once
	file_CS_19129_proto_rawDescData []byte
)

func file_CS_19129_proto_rawDescGZIP() []byte {
	file_CS_19129_proto_rawDescOnce.Do(func() {
		file_CS_19129_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CS_19129_proto_rawDesc), len(file_CS_19129_proto_rawDesc)))
	})
	return file_CS_19129_proto_rawDescData
}

var file_CS_19129_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CS_19129_proto_goTypes = []any{
	(*CS_19129)(nil), // 0: belfast.CS_19129
}
var file_CS_19129_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CS_19129_proto_init() }
func file_CS_19129_proto_init() {
	if File_CS_19129_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CS_19129_proto_rawDesc), len(file_CS_19129_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CS_19129_proto_goTypes,
		DependencyIndexes: file_CS_19129_proto_depIdxs,
		MessageInfos:      file_CS_19129_proto_msgTypes,
	}.Build()
	File_CS_19129_proto = out.File
	file_CS_19129_proto_goTypes = nil
	file_CS_19129_proto_depIdxs = nil
}
