// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CS_27037.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_27037 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type_1        *uint32                `protobuf:"varint,1,req,name=type_1,json=type1" json:"type_1,omitempty"`
	Progresses    []*CHILD_PROGRESS      `protobuf:"bytes,2,rep,name=progresses" json:"progresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_27037) Reset() {
	*x = CS_27037{}
	mi := &file_CS_27037_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_27037) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_27037) ProtoMessage() {}

func (x *CS_27037) ProtoReflect() protoreflect.Message {
	mi := &file_CS_27037_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_27037.ProtoReflect.Descriptor instead.
func (*CS_27037) Descriptor() ([]byte, []int) {
	return file_CS_27037_proto_rawDescGZIP(), []int{0}
}

func (x *CS_27037) GetType_1() uint32 {
	if x != nil && x.Type_1 != nil {
		return *x.Type_1
	}
	return 0
}

func (x *CS_27037) GetProgresses() []*CHILD_PROGRESS {
	if x != nil {
		return x.Progresses
	}
	return nil
}

var File_CS_27037_proto protoreflect.FileDescriptor

const file_CS_27037_proto_rawDesc = "" +
	"\n" +
	"\x0eCS_27037.proto\x12\abelfast\x1a\x14CHILD_PROGRESS.proto\"Z\n" +
	"\bCS_27037\x12\x15\n" +
	"\x06type_1\x18\x01 \x02(\rR\x05type1\x127\n" +
	"\n" +
	"progresses\x18\x02 \x03(\v2\x17.belfast.CHILD_PROGRESSR\n" +
	"progressesB\fZ\n" +
	"./protobuf"

var (
	file_CS_27037_proto_rawDescOnce sync.Once
	file_CS_27037_proto_rawDescData []byte
)

func file_CS_27037_proto_rawDescGZIP() []byte {
	file_CS_27037_proto_rawDescOnce.Do(func() {
		file_CS_27037_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CS_27037_proto_rawDesc), len(file_CS_27037_proto_rawDesc)))
	})
	return file_CS_27037_proto_rawDescData
}

var file_CS_27037_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CS_27037_proto_goTypes = []any{
	(*CS_27037)(nil),       // 0: belfast.CS_27037
	(*CHILD_PROGRESS)(nil), // 1: belfast.CHILD_PROGRESS
}
var file_CS_27037_proto_depIdxs = []int32{
	1, // 0: belfast.CS_27037.progresses:type_name -> belfast.CHILD_PROGRESS
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CS_27037_proto_init() }
func file_CS_27037_proto_init() {
	if File_CS_27037_proto != nil {
		return
	}
	file_CHILD_PROGRESS_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CS_27037_proto_rawDesc), len(file_CS_27037_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CS_27037_proto_goTypes,
		DependencyIndexes: file_CS_27037_proto_depIdxs,
		MessageInfos:      file_CS_27037_proto_msgTypes,
	}.Build()
	File_CS_27037_proto = out.File
	file_CS_27037_proto_goTypes = nil
	file_CS_27037_proto_depIdxs = nil
}
