// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CS_20005.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_20005 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	ChoiceAward   []*DROPINFO            `protobuf:"bytes,2,rep,name=choice_award,json=choiceAward" json:"choice_award,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_20005) Reset() {
	*x = CS_20005{}
	mi := &file_CS_20005_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_20005) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_20005) ProtoMessage() {}

func (x *CS_20005) ProtoReflect() protoreflect.Message {
	mi := &file_CS_20005_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_20005.ProtoReflect.Descriptor instead.
func (*CS_20005) Descriptor() ([]byte, []int) {
	return file_CS_20005_proto_rawDescGZIP(), []int{0}
}

func (x *CS_20005) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *CS_20005) GetChoiceAward() []*DROPINFO {
	if x != nil {
		return x.ChoiceAward
	}
	return nil
}

var File_CS_20005_proto protoreflect.FileDescriptor

const file_CS_20005_proto_rawDesc = "" +
	"\n" +
	"\x0eCS_20005.proto\x12\abelfast\x1a\x0eDROPINFO.proto\"P\n" +
	"\bCS_20005\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x124\n" +
	"\fchoice_award\x18\x02 \x03(\v2\x11.belfast.DROPINFOR\vchoiceAwardB\fZ\n" +
	"./protobuf"

var (
	file_CS_20005_proto_rawDescOnce sync.Once
	file_CS_20005_proto_rawDescData []byte
)

func file_CS_20005_proto_rawDescGZIP() []byte {
	file_CS_20005_proto_rawDescOnce.Do(func() {
		file_CS_20005_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CS_20005_proto_rawDesc), len(file_CS_20005_proto_rawDesc)))
	})
	return file_CS_20005_proto_rawDescData
}

var file_CS_20005_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CS_20005_proto_goTypes = []any{
	(*CS_20005)(nil), // 0: belfast.CS_20005
	(*DROPINFO)(nil), // 1: belfast.DROPINFO
}
var file_CS_20005_proto_depIdxs = []int32{
	1, // 0: belfast.CS_20005.choice_award:type_name -> belfast.DROPINFO
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CS_20005_proto_init() }
func file_CS_20005_proto_init() {
	if File_CS_20005_proto != nil {
		return
	}
	file_DROPINFO_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CS_20005_proto_rawDesc), len(file_CS_20005_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CS_20005_proto_goTypes,
		DependencyIndexes: file_CS_20005_proto_depIdxs,
		MessageInfos:      file_CS_20005_proto_msgTypes,
	}.Build()
	File_CS_20005_proto = out.File
	file_CS_20005_proto_goTypes = nil
	file_CS_20005_proto_depIdxs = nil
}
