// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CS_21626.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_21626 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IslandId      *uint32                `protobuf:"varint,1,req,name=island_id,json=islandId" json:"island_id,omitempty"`
	DressList     []*PB_ISLAND_CUR_DRESS `protobuf:"bytes,2,rep,name=dress_list,json=dressList" json:"dress_list,omitempty"`
	ColorList     []*PB_DRESS_COLOR      `protobuf:"bytes,3,rep,name=color_list,json=colorList" json:"color_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_21626) Reset() {
	*x = CS_21626{}
	mi := &file_CS_21626_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_21626) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_21626) ProtoMessage() {}

func (x *CS_21626) ProtoReflect() protoreflect.Message {
	mi := &file_CS_21626_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_21626.ProtoReflect.Descriptor instead.
func (*CS_21626) Descriptor() ([]byte, []int) {
	return file_CS_21626_proto_rawDescGZIP(), []int{0}
}

func (x *CS_21626) GetIslandId() uint32 {
	if x != nil && x.IslandId != nil {
		return *x.IslandId
	}
	return 0
}

func (x *CS_21626) GetDressList() []*PB_ISLAND_CUR_DRESS {
	if x != nil {
		return x.DressList
	}
	return nil
}

func (x *CS_21626) GetColorList() []*PB_DRESS_COLOR {
	if x != nil {
		return x.ColorList
	}
	return nil
}

var File_CS_21626_proto protoreflect.FileDescriptor

const file_CS_21626_proto_rawDesc = "" +
	"\n" +
	"\x0eCS_21626.proto\x12\abelfast\x1a\x14PB_DRESS_COLOR.proto\x1a\x19PB_ISLAND_CUR_DRESS.proto\"\x9c\x01\n" +
	"\bCS_21626\x12\x1b\n" +
	"\tisland_id\x18\x01 \x02(\rR\bislandId\x12;\n" +
	"\n" +
	"dress_list\x18\x02 \x03(\v2\x1c.belfast.PB_ISLAND_CUR_DRESSR\tdressList\x126\n" +
	"\n" +
	"color_list\x18\x03 \x03(\v2\x17.belfast.PB_DRESS_COLORR\tcolorListB\fZ\n" +
	"./protobuf"

var (
	file_CS_21626_proto_rawDescOnce sync.Once
	file_CS_21626_proto_rawDescData []byte
)

func file_CS_21626_proto_rawDescGZIP() []byte {
	file_CS_21626_proto_rawDescOnce.Do(func() {
		file_CS_21626_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CS_21626_proto_rawDesc), len(file_CS_21626_proto_rawDesc)))
	})
	return file_CS_21626_proto_rawDescData
}

var file_CS_21626_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CS_21626_proto_goTypes = []any{
	(*CS_21626)(nil),            // 0: belfast.CS_21626
	(*PB_ISLAND_CUR_DRESS)(nil), // 1: belfast.PB_ISLAND_CUR_DRESS
	(*PB_DRESS_COLOR)(nil),      // 2: belfast.PB_DRESS_COLOR
}
var file_CS_21626_proto_depIdxs = []int32{
	1, // 0: belfast.CS_21626.dress_list:type_name -> belfast.PB_ISLAND_CUR_DRESS
	2, // 1: belfast.CS_21626.color_list:type_name -> belfast.PB_DRESS_COLOR
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_CS_21626_proto_init() }
func file_CS_21626_proto_init() {
	if File_CS_21626_proto != nil {
		return
	}
	file_PB_DRESS_COLOR_proto_init()
	file_PB_ISLAND_CUR_DRESS_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CS_21626_proto_rawDesc), len(file_CS_21626_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CS_21626_proto_goTypes,
		DependencyIndexes: file_CS_21626_proto_depIdxs,
		MessageInfos:      file_CS_21626_proto_msgTypes,
	}.Build()
	File_CS_21626_proto = out.File
	file_CS_21626_proto_goTypes = nil
	file_CS_21626_proto_depIdxs = nil
}
