// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CS_21702.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_21702 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NpcId            *uint32                `protobuf:"varint,1,req,name=npc_id,json=npcId" json:"npc_id,omitempty"`
	ActionFeedbackId *uint32                `protobuf:"varint,2,req,name=action_feedback_id,json=actionFeedbackId" json:"action_feedback_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CS_21702) Reset() {
	*x = CS_21702{}
	mi := &file_CS_21702_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_21702) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_21702) ProtoMessage() {}

func (x *CS_21702) ProtoReflect() protoreflect.Message {
	mi := &file_CS_21702_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_21702.ProtoReflect.Descriptor instead.
func (*CS_21702) Descriptor() ([]byte, []int) {
	return file_CS_21702_proto_rawDescGZIP(), []int{0}
}

func (x *CS_21702) GetNpcId() uint32 {
	if x != nil && x.NpcId != nil {
		return *x.NpcId
	}
	return 0
}

func (x *CS_21702) GetActionFeedbackId() uint32 {
	if x != nil && x.ActionFeedbackId != nil {
		return *x.ActionFeedbackId
	}
	return 0
}

var File_CS_21702_proto protoreflect.FileDescriptor

const file_CS_21702_proto_rawDesc = "" +
	"\n" +
	"\x0eCS_21702.proto\x12\abelfast\"O\n" +
	"\bCS_21702\x12\x15\n" +
	"\x06npc_id\x18\x01 \x02(\rR\x05npcId\x12,\n" +
	"\x12action_feedback_id\x18\x02 \x02(\rR\x10actionFeedbackIdB\fZ\n" +
	"./protobuf"

var (
	file_CS_21702_proto_rawDescOnce sync.Once
	file_CS_21702_proto_rawDescData []byte
)

func file_CS_21702_proto_rawDescGZIP() []byte {
	file_CS_21702_proto_rawDescOnce.Do(func() {
		file_CS_21702_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CS_21702_proto_rawDesc), len(file_CS_21702_proto_rawDesc)))
	})
	return file_CS_21702_proto_rawDescData
}

var file_CS_21702_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CS_21702_proto_goTypes = []any{
	(*CS_21702)(nil), // 0: belfast.CS_21702
}
var file_CS_21702_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CS_21702_proto_init() }
func file_CS_21702_proto_init() {
	if File_CS_21702_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CS_21702_proto_rawDesc), len(file_CS_21702_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CS_21702_proto_goTypes,
		DependencyIndexes: file_CS_21702_proto_depIdxs,
		MessageInfos:      file_CS_21702_proto_msgTypes,
	}.Build()
	File_CS_21702_proto = out.File
	file_CS_21702_proto_goTypes = nil
	file_CS_21702_proto_depIdxs = nil
}
