// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CS_21004.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_21004 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Type          *uint32                `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_21004) Reset() {
	*x = CS_21004{}
	mi := &file_CS_21004_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_21004) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_21004) ProtoMessage() {}

func (x *CS_21004) ProtoReflect() protoreflect.Message {
	mi := &file_CS_21004_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_21004.ProtoReflect.Descriptor instead.
func (*CS_21004) Descriptor() ([]byte, []int) {
	return file_CS_21004_proto_rawDescGZIP(), []int{0}
}

func (x *CS_21004) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CS_21004) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

var File_CS_21004_proto protoreflect.FileDescriptor

const file_CS_21004_proto_rawDesc = "" +
	"\n" +
	"\x0eCS_21004.proto\x12\abelfast\"2\n" +
	"\bCS_21004\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x02(\rR\x04typeB\fZ\n" +
	"./protobuf"

var (
	file_CS_21004_proto_rawDescOnce sync.Once
	file_CS_21004_proto_rawDescData []byte
)

func file_CS_21004_proto_rawDescGZIP() []byte {
	file_CS_21004_proto_rawDescOnce.Do(func() {
		file_CS_21004_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CS_21004_proto_rawDesc), len(file_CS_21004_proto_rawDesc)))
	})
	return file_CS_21004_proto_rawDescData
}

var file_CS_21004_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CS_21004_proto_goTypes = []any{
	(*CS_21004)(nil), // 0: belfast.CS_21004
}
var file_CS_21004_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CS_21004_proto_init() }
func file_CS_21004_proto_init() {
	if File_CS_21004_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CS_21004_proto_rawDesc), len(file_CS_21004_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CS_21004_proto_goTypes,
		DependencyIndexes: file_CS_21004_proto_depIdxs,
		MessageInfos:      file_CS_21004_proto_msgTypes,
	}.Build()
	File_CS_21004_proto = out.File
	file_CS_21004_proto_goTypes = nil
	file_CS_21004_proto_depIdxs = nil
}
