// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CS_33103.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_33103 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Act           *uint32                `protobuf:"varint,1,req,name=act" json:"act,omitempty"`
	GroupId       *uint32                `protobuf:"varint,2,req,name=group_id,json=groupId" json:"group_id,omitempty"`
	ActArg_1      *uint32                `protobuf:"varint,3,opt,name=act_arg_1,json=actArg1" json:"act_arg_1,omitempty"`
	ActArg_2      *uint32                `protobuf:"varint,4,opt,name=act_arg_2,json=actArg2" json:"act_arg_2,omitempty"`
	PosList       []*CHAPTERCELLPOS_P33  `protobuf:"bytes,5,rep,name=pos_list,json=posList" json:"pos_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_33103) Reset() {
	*x = CS_33103{}
	mi := &file_CS_33103_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_33103) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_33103) ProtoMessage() {}

func (x *CS_33103) ProtoReflect() protoreflect.Message {
	mi := &file_CS_33103_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_33103.ProtoReflect.Descriptor instead.
func (*CS_33103) Descriptor() ([]byte, []int) {
	return file_CS_33103_proto_rawDescGZIP(), []int{0}
}

func (x *CS_33103) GetAct() uint32 {
	if x != nil && x.Act != nil {
		return *x.Act
	}
	return 0
}

func (x *CS_33103) GetGroupId() uint32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *CS_33103) GetActArg_1() uint32 {
	if x != nil && x.ActArg_1 != nil {
		return *x.ActArg_1
	}
	return 0
}

func (x *CS_33103) GetActArg_2() uint32 {
	if x != nil && x.ActArg_2 != nil {
		return *x.ActArg_2
	}
	return 0
}

func (x *CS_33103) GetPosList() []*CHAPTERCELLPOS_P33 {
	if x != nil {
		return x.PosList
	}
	return nil
}

var File_CS_33103_proto protoreflect.FileDescriptor

const file_CS_33103_proto_rawDesc = "" +
	"\n" +
	"\x0eCS_33103.proto\x12\abelfast\x1a\x18CHAPTERCELLPOS_P33.proto\"\xa7\x01\n" +
	"\bCS_33103\x12\x10\n" +
	"\x03act\x18\x01 \x02(\rR\x03act\x12\x19\n" +
	"\bgroup_id\x18\x02 \x02(\rR\agroupId\x12\x1a\n" +
	"\tact_arg_1\x18\x03 \x01(\rR\aactArg1\x12\x1a\n" +
	"\tact_arg_2\x18\x04 \x01(\rR\aactArg2\x126\n" +
	"\bpos_list\x18\x05 \x03(\v2\x1b.belfast.CHAPTERCELLPOS_P33R\aposListB\fZ\n" +
	"./protobuf"

var (
	file_CS_33103_proto_rawDescOnce sync.Once
	file_CS_33103_proto_rawDescData []byte
)

func file_CS_33103_proto_rawDescGZIP() []byte {
	file_CS_33103_proto_rawDescOnce.Do(func() {
		file_CS_33103_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CS_33103_proto_rawDesc), len(file_CS_33103_proto_rawDesc)))
	})
	return file_CS_33103_proto_rawDescData
}

var file_CS_33103_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CS_33103_proto_goTypes = []any{
	(*CS_33103)(nil),           // 0: belfast.CS_33103
	(*CHAPTERCELLPOS_P33)(nil), // 1: belfast.CHAPTERCELLPOS_P33
}
var file_CS_33103_proto_depIdxs = []int32{
	1, // 0: belfast.CS_33103.pos_list:type_name -> belfast.CHAPTERCELLPOS_P33
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CS_33103_proto_init() }
func file_CS_33103_proto_init() {
	if File_CS_33103_proto != nil {
		return
	}
	file_CHAPTERCELLPOS_P33_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CS_33103_proto_rawDesc), len(file_CS_33103_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CS_33103_proto_goTypes,
		DependencyIndexes: file_CS_33103_proto_depIdxs,
		MessageInfos:      file_CS_33103_proto_msgTypes,
	}.Build()
	File_CS_33103_proto = out.File
	file_CS_33103_proto_goTypes = nil
	file_CS_33103_proto_depIdxs = nil
}
