// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CS_64009.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_64009 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TechsetList   []*TECHSET             `protobuf:"bytes,1,rep,name=techset_list,json=techsetList" json:"techset_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_64009) Reset() {
	*x = CS_64009{}
	mi := &file_CS_64009_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_64009) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_64009) ProtoMessage() {}

func (x *CS_64009) ProtoReflect() protoreflect.Message {
	mi := &file_CS_64009_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_64009.ProtoReflect.Descriptor instead.
func (*CS_64009) Descriptor() ([]byte, []int) {
	return file_CS_64009_proto_rawDescGZIP(), []int{0}
}

func (x *CS_64009) GetTechsetList() []*TECHSET {
	if x != nil {
		return x.TechsetList
	}
	return nil
}

var File_CS_64009_proto protoreflect.FileDescriptor

const file_CS_64009_proto_rawDesc = "" +
	"\n" +
	"\x0eCS_64009.proto\x12\abelfast\x1a\rTECHSET.proto\"?\n" +
	"\bCS_64009\x123\n" +
	"\ftechset_list\x18\x01 \x03(\v2\x10.belfast.TECHSETR\vtechsetListB\fZ\n" +
	"./protobuf"

var (
	file_CS_64009_proto_rawDescOnce sync.Once
	file_CS_64009_proto_rawDescData []byte
)

func file_CS_64009_proto_rawDescGZIP() []byte {
	file_CS_64009_proto_rawDescOnce.Do(func() {
		file_CS_64009_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CS_64009_proto_rawDesc), len(file_CS_64009_proto_rawDesc)))
	})
	return file_CS_64009_proto_rawDescData
}

var file_CS_64009_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CS_64009_proto_goTypes = []any{
	(*CS_64009)(nil), // 0: belfast.CS_64009
	(*TECHSET)(nil),  // 1: belfast.TECHSET
}
var file_CS_64009_proto_depIdxs = []int32{
	1, // 0: belfast.CS_64009.techset_list:type_name -> belfast.TECHSET
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CS_64009_proto_init() }
func file_CS_64009_proto_init() {
	if File_CS_64009_proto != nil {
		return
	}
	file_TECHSET_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CS_64009_proto_rawDesc), len(file_CS_64009_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CS_64009_proto_goTypes,
		DependencyIndexes: file_CS_64009_proto_depIdxs,
		MessageInfos:      file_CS_64009_proto_msgTypes,
	}.Build()
	File_CS_64009_proto = out.File
	file_CS_64009_proto_goTypes = nil
	file_CS_64009_proto_depIdxs = nil
}
