// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: EVENT_BASE.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EVENT_BASE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       *uint32                `protobuf:"varint,1,req,name=event_id,json=eventId" json:"event_id,omitempty"`
	Position      *uint32                `protobuf:"varint,2,req,name=position" json:"position,omitempty"`
	StartTime     *uint32                `protobuf:"varint,3,req,name=start_time,json=startTime" json:"start_time,omitempty"`
	CompleteTime  *uint32                `protobuf:"varint,4,req,name=complete_time,json=completeTime" json:"complete_time,omitempty"`
	Shipinevent   []*SHIP_IN_EVENT       `protobuf:"bytes,5,rep,name=shipinevent" json:"shipinevent,omitempty"`
	AttrAccList   []*KEYVALUE_P61        `protobuf:"bytes,6,rep,name=attr_acc_list,json=attrAccList" json:"attr_acc_list,omitempty"`
	AttrCountList []*KEYVALUE_P61        `protobuf:"bytes,7,rep,name=attr_count_list,json=attrCountList" json:"attr_count_list,omitempty"`
	Eventnodes    []*EVENT_NODE          `protobuf:"bytes,8,rep,name=eventnodes" json:"eventnodes,omitempty"`
	Efficiency    *uint32                `protobuf:"varint,9,req,name=efficiency" json:"efficiency,omitempty"`
	Personship    []*PERSON_SHIP_IN_PAGE `protobuf:"bytes,10,rep,name=personship" json:"personship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EVENT_BASE) Reset() {
	*x = EVENT_BASE{}
	mi := &file_EVENT_BASE_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EVENT_BASE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EVENT_BASE) ProtoMessage() {}

func (x *EVENT_BASE) ProtoReflect() protoreflect.Message {
	mi := &file_EVENT_BASE_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EVENT_BASE.ProtoReflect.Descriptor instead.
func (*EVENT_BASE) Descriptor() ([]byte, []int) {
	return file_EVENT_BASE_proto_rawDescGZIP(), []int{0}
}

func (x *EVENT_BASE) GetEventId() uint32 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

func (x *EVENT_BASE) GetPosition() uint32 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *EVENT_BASE) GetStartTime() uint32 {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return 0
}

func (x *EVENT_BASE) GetCompleteTime() uint32 {
	if x != nil && x.CompleteTime != nil {
		return *x.CompleteTime
	}
	return 0
}

func (x *EVENT_BASE) GetShipinevent() []*SHIP_IN_EVENT {
	if x != nil {
		return x.Shipinevent
	}
	return nil
}

func (x *EVENT_BASE) GetAttrAccList() []*KEYVALUE_P61 {
	if x != nil {
		return x.AttrAccList
	}
	return nil
}

func (x *EVENT_BASE) GetAttrCountList() []*KEYVALUE_P61 {
	if x != nil {
		return x.AttrCountList
	}
	return nil
}

func (x *EVENT_BASE) GetEventnodes() []*EVENT_NODE {
	if x != nil {
		return x.Eventnodes
	}
	return nil
}

func (x *EVENT_BASE) GetEfficiency() uint32 {
	if x != nil && x.Efficiency != nil {
		return *x.Efficiency
	}
	return 0
}

func (x *EVENT_BASE) GetPersonship() []*PERSON_SHIP_IN_PAGE {
	if x != nil {
		return x.Personship
	}
	return nil
}

var File_EVENT_BASE_proto protoreflect.FileDescriptor

const file_EVENT_BASE_proto_rawDesc = "" +
	"\n" +
	"\x10EVENT_BASE.proto\x12\abelfast\x1a\x10EVENT_NODE.proto\x1a\x12KEYVALUE_P61.proto\x1a\x19PERSON_SHIP_IN_PAGE.proto\x1a\x13SHIP_IN_EVENT.proto\"\xce\x03\n" +
	"\n" +
	"EVENT_BASE\x12\x19\n" +
	"\bevent_id\x18\x01 \x02(\rR\aeventId\x12\x1a\n" +
	"\bposition\x18\x02 \x02(\rR\bposition\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x02(\rR\tstartTime\x12#\n" +
	"\rcomplete_time\x18\x04 \x02(\rR\fcompleteTime\x128\n" +
	"\vshipinevent\x18\x05 \x03(\v2\x16.belfast.SHIP_IN_EVENTR\vshipinevent\x129\n" +
	"\rattr_acc_list\x18\x06 \x03(\v2\x15.belfast.KEYVALUE_P61R\vattrAccList\x12=\n" +
	"\x0fattr_count_list\x18\a \x03(\v2\x15.belfast.KEYVALUE_P61R\rattrCountList\x123\n" +
	"\n" +
	"eventnodes\x18\b \x03(\v2\x13.belfast.EVENT_NODER\n" +
	"eventnodes\x12\x1e\n" +
	"\n" +
	"efficiency\x18\t \x02(\rR\n" +
	"efficiency\x12<\n" +
	"\n" +
	"personship\x18\n" +
	" \x03(\v2\x1c.belfast.PERSON_SHIP_IN_PAGER\n" +
	"personshipB\fZ\n" +
	"./protobuf"

var (
	file_EVENT_BASE_proto_rawDescOnce sync.Once
	file_EVENT_BASE_proto_rawDescData []byte
)

func file_EVENT_BASE_proto_rawDescGZIP() []byte {
	file_EVENT_BASE_proto_rawDescOnce.Do(func() {
		file_EVENT_BASE_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EVENT_BASE_proto_rawDesc), len(file_EVENT_BASE_proto_rawDesc)))
	})
	return file_EVENT_BASE_proto_rawDescData
}

var file_EVENT_BASE_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_EVENT_BASE_proto_goTypes = []any{
	(*EVENT_BASE)(nil),          // 0: belfast.EVENT_BASE
	(*SHIP_IN_EVENT)(nil),       // 1: belfast.SHIP_IN_EVENT
	(*KEYVALUE_P61)(nil),        // 2: belfast.KEYVALUE_P61
	(*EVENT_NODE)(nil),          // 3: belfast.EVENT_NODE
	(*PERSON_SHIP_IN_PAGE)(nil), // 4: belfast.PERSON_SHIP_IN_PAGE
}
var file_EVENT_BASE_proto_depIdxs = []int32{
	1, // 0: belfast.EVENT_BASE.shipinevent:type_name -> belfast.SHIP_IN_EVENT
	2, // 1: belfast.EVENT_BASE.attr_acc_list:type_name -> belfast.KEYVALUE_P61
	2, // 2: belfast.EVENT_BASE.attr_count_list:type_name -> belfast.KEYVALUE_P61
	3, // 3: belfast.EVENT_BASE.eventnodes:type_name -> belfast.EVENT_NODE
	4, // 4: belfast.EVENT_BASE.personship:type_name -> belfast.PERSON_SHIP_IN_PAGE
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_EVENT_BASE_proto_init() }
func file_EVENT_BASE_proto_init() {
	if File_EVENT_BASE_proto != nil {
		return
	}
	file_EVENT_NODE_proto_init()
	file_KEYVALUE_P61_proto_init()
	file_PERSON_SHIP_IN_PAGE_proto_init()
	file_SHIP_IN_EVENT_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EVENT_BASE_proto_rawDesc), len(file_EVENT_BASE_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EVENT_BASE_proto_goTypes,
		DependencyIndexes: file_EVENT_BASE_proto_depIdxs,
		MessageInfos:      file_EVENT_BASE_proto_msgTypes,
	}.Build()
	File_EVENT_BASE_proto = out.File
	file_EVENT_BASE_proto_goTypes = nil
	file_EVENT_BASE_proto_depIdxs = nil
}
