// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: FRIEND_CIRCLE_INFO.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FRIEND_CIRCLE_INFO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Time          *uint32                `protobuf:"varint,2,req,name=time" json:"time,omitempty"`
	ReadFlag      *uint32                `protobuf:"varint,3,req,name=read_flag,json=readFlag" json:"read_flag,omitempty"`
	GoodFlag      *uint32                `protobuf:"varint,4,req,name=good_flag,json=goodFlag" json:"good_flag,omitempty"`
	ReplyList     []*REPLY_FRIEND        `protobuf:"bytes,5,rep,name=reply_list,json=replyList" json:"reply_list,omitempty"`
	ExitTime      *uint32                `protobuf:"varint,6,req,name=exit_time,json=exitTime" json:"exit_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FRIEND_CIRCLE_INFO) Reset() {
	*x = FRIEND_CIRCLE_INFO{}
	mi := &file_FRIEND_CIRCLE_INFO_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FRIEND_CIRCLE_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FRIEND_CIRCLE_INFO) ProtoMessage() {}

func (x *FRIEND_CIRCLE_INFO) ProtoReflect() protoreflect.Message {
	mi := &file_FRIEND_CIRCLE_INFO_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FRIEND_CIRCLE_INFO.ProtoReflect.Descriptor instead.
func (*FRIEND_CIRCLE_INFO) Descriptor() ([]byte, []int) {
	return file_FRIEND_CIRCLE_INFO_proto_rawDescGZIP(), []int{0}
}

func (x *FRIEND_CIRCLE_INFO) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *FRIEND_CIRCLE_INFO) GetTime() uint32 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *FRIEND_CIRCLE_INFO) GetReadFlag() uint32 {
	if x != nil && x.ReadFlag != nil {
		return *x.ReadFlag
	}
	return 0
}

func (x *FRIEND_CIRCLE_INFO) GetGoodFlag() uint32 {
	if x != nil && x.GoodFlag != nil {
		return *x.GoodFlag
	}
	return 0
}

func (x *FRIEND_CIRCLE_INFO) GetReplyList() []*REPLY_FRIEND {
	if x != nil {
		return x.ReplyList
	}
	return nil
}

func (x *FRIEND_CIRCLE_INFO) GetExitTime() uint32 {
	if x != nil && x.ExitTime != nil {
		return *x.ExitTime
	}
	return 0
}

var File_FRIEND_CIRCLE_INFO_proto protoreflect.FileDescriptor

const file_FRIEND_CIRCLE_INFO_proto_rawDesc = "" +
	"\n" +
	"\x18FRIEND_CIRCLE_INFO.proto\x12\abelfast\x1a\x12REPLY_FRIEND.proto\"\xc5\x01\n" +
	"\x12FRIEND_CIRCLE_INFO\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x12\n" +
	"\x04time\x18\x02 \x02(\rR\x04time\x12\x1b\n" +
	"\tread_flag\x18\x03 \x02(\rR\breadFlag\x12\x1b\n" +
	"\tgood_flag\x18\x04 \x02(\rR\bgoodFlag\x124\n" +
	"\n" +
	"reply_list\x18\x05 \x03(\v2\x15.belfast.REPLY_FRIENDR\treplyList\x12\x1b\n" +
	"\texit_time\x18\x06 \x02(\rR\bexitTimeB\fZ\n" +
	"./protobuf"

var (
	file_FRIEND_CIRCLE_INFO_proto_rawDescOnce sync.Once
	file_FRIEND_CIRCLE_INFO_proto_rawDescData []byte
)

func file_FRIEND_CIRCLE_INFO_proto_rawDescGZIP() []byte {
	file_FRIEND_CIRCLE_INFO_proto_rawDescOnce.Do(func() {
		file_FRIEND_CIRCLE_INFO_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_FRIEND_CIRCLE_INFO_proto_rawDesc), len(file_FRIEND_CIRCLE_INFO_proto_rawDesc)))
	})
	return file_FRIEND_CIRCLE_INFO_proto_rawDescData
}

var file_FRIEND_CIRCLE_INFO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_FRIEND_CIRCLE_INFO_proto_goTypes = []any{
	(*FRIEND_CIRCLE_INFO)(nil), // 0: belfast.FRIEND_CIRCLE_INFO
	(*REPLY_FRIEND)(nil),       // 1: belfast.REPLY_FRIEND
}
var file_FRIEND_CIRCLE_INFO_proto_depIdxs = []int32{
	1, // 0: belfast.FRIEND_CIRCLE_INFO.reply_list:type_name -> belfast.REPLY_FRIEND
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_FRIEND_CIRCLE_INFO_proto_init() }
func file_FRIEND_CIRCLE_INFO_proto_init() {
	if File_FRIEND_CIRCLE_INFO_proto != nil {
		return
	}
	file_REPLY_FRIEND_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_FRIEND_CIRCLE_INFO_proto_rawDesc), len(file_FRIEND_CIRCLE_INFO_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FRIEND_CIRCLE_INFO_proto_goTypes,
		DependencyIndexes: file_FRIEND_CIRCLE_INFO_proto_depIdxs,
		MessageInfos:      file_FRIEND_CIRCLE_INFO_proto_msgTypes,
	}.Build()
	File_FRIEND_CIRCLE_INFO_proto = out.File
	file_FRIEND_CIRCLE_INFO_proto_goTypes = nil
	file_FRIEND_CIRCLE_INFO_proto_depIdxs = nil
}
