// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: GAMEROOM.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GAMEROOM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roomid        *uint32                `protobuf:"varint,1,req,name=roomid" json:"roomid,omitempty"`
	MaxScore      *uint32                `protobuf:"varint,2,req,name=max_score,json=maxScore" json:"max_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GAMEROOM) Reset() {
	*x = GAMEROOM{}
	mi := &file_GAMEROOM_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GAMEROOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GAMEROOM) ProtoMessage() {}

func (x *GAMEROOM) ProtoReflect() protoreflect.Message {
	mi := &file_GAMEROOM_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GAMEROOM.ProtoReflect.Descriptor instead.
func (*GAMEROOM) Descriptor() ([]byte, []int) {
	return file_GAMEROOM_proto_rawDescGZIP(), []int{0}
}

func (x *GAMEROOM) GetRoomid() uint32 {
	if x != nil && x.Roomid != nil {
		return *x.Roomid
	}
	return 0
}

func (x *GAMEROOM) GetMaxScore() uint32 {
	if x != nil && x.MaxScore != nil {
		return *x.MaxScore
	}
	return 0
}

var File_GAMEROOM_proto protoreflect.FileDescriptor

const file_GAMEROOM_proto_rawDesc = "" +
	"\n" +
	"\x0eGAMEROOM.proto\x12\abelfast\"?\n" +
	"\bGAMEROOM\x12\x16\n" +
	"\x06roomid\x18\x01 \x02(\rR\x06roomid\x12\x1b\n" +
	"\tmax_score\x18\x02 \x02(\rR\bmaxScoreB\fZ\n" +
	"./protobuf"

var (
	file_GAMEROOM_proto_rawDescOnce sync.Once
	file_GAMEROOM_proto_rawDescData []byte
)

func file_GAMEROOM_proto_rawDescGZIP() []byte {
	file_GAMEROOM_proto_rawDescOnce.Do(func() {
		file_GAMEROOM_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GAMEROOM_proto_rawDesc), len(file_GAMEROOM_proto_rawDesc)))
	})
	return file_GAMEROOM_proto_rawDescData
}

var file_GAMEROOM_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GAMEROOM_proto_goTypes = []any{
	(*GAMEROOM)(nil), // 0: belfast.GAMEROOM
}
var file_GAMEROOM_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GAMEROOM_proto_init() }
func file_GAMEROOM_proto_init() {
	if File_GAMEROOM_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GAMEROOM_proto_rawDesc), len(file_GAMEROOM_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GAMEROOM_proto_goTypes,
		DependencyIndexes: file_GAMEROOM_proto_depIdxs,
		MessageInfos:      file_GAMEROOM_proto_msgTypes,
	}.Build()
	File_GAMEROOM_proto = out.File
	file_GAMEROOM_proto_goTypes = nil
	file_GAMEROOM_proto_depIdxs = nil
}
