// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: GROUPINFO.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GROUPINFO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	ShipList      []uint32               `protobuf:"varint,2,rep,name=ship_list,json=shipList" json:"ship_list,omitempty"`
	Commanders    []*COMMANDERSINFO      `protobuf:"bytes,3,rep,name=commanders" json:"commanders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GROUPINFO) Reset() {
	*x = GROUPINFO{}
	mi := &file_GROUPINFO_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GROUPINFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GROUPINFO) ProtoMessage() {}

func (x *GROUPINFO) ProtoReflect() protoreflect.Message {
	mi := &file_GROUPINFO_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GROUPINFO.ProtoReflect.Descriptor instead.
func (*GROUPINFO) Descriptor() ([]byte, []int) {
	return file_GROUPINFO_proto_rawDescGZIP(), []int{0}
}

func (x *GROUPINFO) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GROUPINFO) GetShipList() []uint32 {
	if x != nil {
		return x.ShipList
	}
	return nil
}

func (x *GROUPINFO) GetCommanders() []*COMMANDERSINFO {
	if x != nil {
		return x.Commanders
	}
	return nil
}

var File_GROUPINFO_proto protoreflect.FileDescriptor

const file_GROUPINFO_proto_rawDesc = "" +
	"\n" +
	"\x0fGROUPINFO.proto\x12\abelfast\x1a\x14COMMANDERSINFO.proto\"q\n" +
	"\tGROUPINFO\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x1b\n" +
	"\tship_list\x18\x02 \x03(\rR\bshipList\x127\n" +
	"\n" +
	"commanders\x18\x03 \x03(\v2\x17.belfast.COMMANDERSINFOR\n" +
	"commandersB\fZ\n" +
	"./protobuf"

var (
	file_GROUPINFO_proto_rawDescOnce sync.Once
	file_GROUPINFO_proto_rawDescData []byte
)

func file_GROUPINFO_proto_rawDescGZIP() []byte {
	file_GROUPINFO_proto_rawDescOnce.Do(func() {
		file_GROUPINFO_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GROUPINFO_proto_rawDesc), len(file_GROUPINFO_proto_rawDesc)))
	})
	return file_GROUPINFO_proto_rawDescData
}

var file_GROUPINFO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GROUPINFO_proto_goTypes = []any{
	(*GROUPINFO)(nil),      // 0: belfast.GROUPINFO
	(*COMMANDERSINFO)(nil), // 1: belfast.COMMANDERSINFO
}
var file_GROUPINFO_proto_depIdxs = []int32{
	1, // 0: belfast.GROUPINFO.commanders:type_name -> belfast.COMMANDERSINFO
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_GROUPINFO_proto_init() }
func file_GROUPINFO_proto_init() {
	if File_GROUPINFO_proto != nil {
		return
	}
	file_COMMANDERSINFO_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GROUPINFO_proto_rawDesc), len(file_GROUPINFO_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GROUPINFO_proto_goTypes,
		DependencyIndexes: file_GROUPINFO_proto_depIdxs,
		MessageInfos:      file_GROUPINFO_proto_msgTypes,
	}.Build()
	File_GROUPINFO_proto = out.File
	file_GROUPINFO_proto_goTypes = nil
	file_GROUPINFO_proto_depIdxs = nil
}
