// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: GROUPINCHAPTER_P33.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GROUPINCHAPTER_P33 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	ShipList         []*SHIPINCHAPTER_P33   `protobuf:"bytes,2,rep,name=ship_list,json=shipList" json:"ship_list,omitempty"`
	Pos              *CHAPTERCELLPOS_P33    `protobuf:"bytes,3,req,name=pos" json:"pos,omitempty"`
	LossFlag         *uint32                `protobuf:"varint,4,req,name=loss_flag,json=lossFlag" json:"loss_flag,omitempty"`
	BoxStrategyList  []*STRATEGYINFO_P33    `protobuf:"bytes,5,rep,name=box_strategy_list,json=boxStrategyList" json:"box_strategy_list,omitempty"`
	ShipStrategyList []*STRATEGYINFO_P33    `protobuf:"bytes,6,rep,name=ship_strategy_list,json=shipStrategyList" json:"ship_strategy_list,omitempty"`
	StrategyIds      []uint32               `protobuf:"varint,7,rep,name=strategy_ids,json=strategyIds" json:"strategy_ids,omitempty"`
	Bullet           *uint32                `protobuf:"varint,8,req,name=bullet" json:"bullet,omitempty"`
	StartPos         *CHAPTERCELLPOS_P33    `protobuf:"bytes,9,req,name=start_pos,json=startPos" json:"start_pos,omitempty"`
	AttachList       []uint32               `protobuf:"varint,10,rep,name=attach_list,json=attachList" json:"attach_list,omitempty"`
	DamageLevel      *uint32                `protobuf:"varint,11,req,name=damage_level,json=damageLevel" json:"damage_level,omitempty"`
	BuffList         []*BUFF_INFO           `protobuf:"bytes,12,rep,name=buff_list,json=buffList" json:"buff_list,omitempty"`
	CommanderList    []*COMMANDERSINFO      `protobuf:"bytes,13,rep,name=commander_list,json=commanderList" json:"commander_list,omitempty"`
	KillCount        *uint32                `protobuf:"varint,14,req,name=kill_count,json=killCount" json:"kill_count,omitempty"`
	CmdCollection    *CMDCOLLECTION         `protobuf:"bytes,15,opt,name=cmd_collection,json=cmdCollection" json:"cmd_collection,omitempty"`
	BulletMax        *uint32                `protobuf:"varint,16,req,name=bullet_max,json=bulletMax" json:"bullet_max,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GROUPINCHAPTER_P33) Reset() {
	*x = GROUPINCHAPTER_P33{}
	mi := &file_GROUPINCHAPTER_P33_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GROUPINCHAPTER_P33) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GROUPINCHAPTER_P33) ProtoMessage() {}

func (x *GROUPINCHAPTER_P33) ProtoReflect() protoreflect.Message {
	mi := &file_GROUPINCHAPTER_P33_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GROUPINCHAPTER_P33.ProtoReflect.Descriptor instead.
func (*GROUPINCHAPTER_P33) Descriptor() ([]byte, []int) {
	return file_GROUPINCHAPTER_P33_proto_rawDescGZIP(), []int{0}
}

func (x *GROUPINCHAPTER_P33) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GROUPINCHAPTER_P33) GetShipList() []*SHIPINCHAPTER_P33 {
	if x != nil {
		return x.ShipList
	}
	return nil
}

func (x *GROUPINCHAPTER_P33) GetPos() *CHAPTERCELLPOS_P33 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *GROUPINCHAPTER_P33) GetLossFlag() uint32 {
	if x != nil && x.LossFlag != nil {
		return *x.LossFlag
	}
	return 0
}

func (x *GROUPINCHAPTER_P33) GetBoxStrategyList() []*STRATEGYINFO_P33 {
	if x != nil {
		return x.BoxStrategyList
	}
	return nil
}

func (x *GROUPINCHAPTER_P33) GetShipStrategyList() []*STRATEGYINFO_P33 {
	if x != nil {
		return x.ShipStrategyList
	}
	return nil
}

func (x *GROUPINCHAPTER_P33) GetStrategyIds() []uint32 {
	if x != nil {
		return x.StrategyIds
	}
	return nil
}

func (x *GROUPINCHAPTER_P33) GetBullet() uint32 {
	if x != nil && x.Bullet != nil {
		return *x.Bullet
	}
	return 0
}

func (x *GROUPINCHAPTER_P33) GetStartPos() *CHAPTERCELLPOS_P33 {
	if x != nil {
		return x.StartPos
	}
	return nil
}

func (x *GROUPINCHAPTER_P33) GetAttachList() []uint32 {
	if x != nil {
		return x.AttachList
	}
	return nil
}

func (x *GROUPINCHAPTER_P33) GetDamageLevel() uint32 {
	if x != nil && x.DamageLevel != nil {
		return *x.DamageLevel
	}
	return 0
}

func (x *GROUPINCHAPTER_P33) GetBuffList() []*BUFF_INFO {
	if x != nil {
		return x.BuffList
	}
	return nil
}

func (x *GROUPINCHAPTER_P33) GetCommanderList() []*COMMANDERSINFO {
	if x != nil {
		return x.CommanderList
	}
	return nil
}

func (x *GROUPINCHAPTER_P33) GetKillCount() uint32 {
	if x != nil && x.KillCount != nil {
		return *x.KillCount
	}
	return 0
}

func (x *GROUPINCHAPTER_P33) GetCmdCollection() *CMDCOLLECTION {
	if x != nil {
		return x.CmdCollection
	}
	return nil
}

func (x *GROUPINCHAPTER_P33) GetBulletMax() uint32 {
	if x != nil && x.BulletMax != nil {
		return *x.BulletMax
	}
	return 0
}

var File_GROUPINCHAPTER_P33_proto protoreflect.FileDescriptor

const file_GROUPINCHAPTER_P33_proto_rawDesc = "" +
	"\n" +
	"\x18GROUPINCHAPTER_P33.proto\x12\abelfast\x1a\x0fBUFF_INFO.proto\x1a\x18CHAPTERCELLPOS_P33.proto\x1a\x13CMDCOLLECTION.proto\x1a\x14COMMANDERSINFO.proto\x1a\x17SHIPINCHAPTER_P33.proto\x1a\x16STRATEGYINFO_P33.proto\"\xe0\x05\n" +
	"\x12GROUPINCHAPTER_P33\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x127\n" +
	"\tship_list\x18\x02 \x03(\v2\x1a.belfast.SHIPINCHAPTER_P33R\bshipList\x12-\n" +
	"\x03pos\x18\x03 \x02(\v2\x1b.belfast.CHAPTERCELLPOS_P33R\x03pos\x12\x1b\n" +
	"\tloss_flag\x18\x04 \x02(\rR\blossFlag\x12E\n" +
	"\x11box_strategy_list\x18\x05 \x03(\v2\x19.belfast.STRATEGYINFO_P33R\x0fboxStrategyList\x12G\n" +
	"\x12ship_strategy_list\x18\x06 \x03(\v2\x19.belfast.STRATEGYINFO_P33R\x10shipStrategyList\x12!\n" +
	"\fstrategy_ids\x18\a \x03(\rR\vstrategyIds\x12\x16\n" +
	"\x06bullet\x18\b \x02(\rR\x06bullet\x128\n" +
	"\tstart_pos\x18\t \x02(\v2\x1b.belfast.CHAPTERCELLPOS_P33R\bstartPos\x12\x1f\n" +
	"\vattach_list\x18\n" +
	" \x03(\rR\n" +
	"attachList\x12!\n" +
	"\fdamage_level\x18\v \x02(\rR\vdamageLevel\x12/\n" +
	"\tbuff_list\x18\f \x03(\v2\x12.belfast.BUFF_INFOR\bbuffList\x12>\n" +
	"\x0ecommander_list\x18\r \x03(\v2\x17.belfast.COMMANDERSINFOR\rcommanderList\x12\x1d\n" +
	"\n" +
	"kill_count\x18\x0e \x02(\rR\tkillCount\x12=\n" +
	"\x0ecmd_collection\x18\x0f \x01(\v2\x16.belfast.CMDCOLLECTIONR\rcmdCollection\x12\x1d\n" +
	"\n" +
	"bullet_max\x18\x10 \x02(\rR\tbulletMaxB\fZ\n" +
	"./protobuf"

var (
	file_GROUPINCHAPTER_P33_proto_rawDescOnce sync.Once
	file_GROUPINCHAPTER_P33_proto_rawDescData []byte
)

func file_GROUPINCHAPTER_P33_proto_rawDescGZIP() []byte {
	file_GROUPINCHAPTER_P33_proto_rawDescOnce.Do(func() {
		file_GROUPINCHAPTER_P33_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GROUPINCHAPTER_P33_proto_rawDesc), len(file_GROUPINCHAPTER_P33_proto_rawDesc)))
	})
	return file_GROUPINCHAPTER_P33_proto_rawDescData
}

var file_GROUPINCHAPTER_P33_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GROUPINCHAPTER_P33_proto_goTypes = []any{
	(*GROUPINCHAPTER_P33)(nil), // 0: belfast.GROUPINCHAPTER_P33
	(*SHIPINCHAPTER_P33)(nil),  // 1: belfast.SHIPINCHAPTER_P33
	(*CHAPTERCELLPOS_P33)(nil), // 2: belfast.CHAPTERCELLPOS_P33
	(*STRATEGYINFO_P33)(nil),   // 3: belfast.STRATEGYINFO_P33
	(*BUFF_INFO)(nil),          // 4: belfast.BUFF_INFO
	(*COMMANDERSINFO)(nil),     // 5: belfast.COMMANDERSINFO
	(*CMDCOLLECTION)(nil),      // 6: belfast.CMDCOLLECTION
}
var file_GROUPINCHAPTER_P33_proto_depIdxs = []int32{
	1, // 0: belfast.GROUPINCHAPTER_P33.ship_list:type_name -> belfast.SHIPINCHAPTER_P33
	2, // 1: belfast.GROUPINCHAPTER_P33.pos:type_name -> belfast.CHAPTERCELLPOS_P33
	3, // 2: belfast.GROUPINCHAPTER_P33.box_strategy_list:type_name -> belfast.STRATEGYINFO_P33
	3, // 3: belfast.GROUPINCHAPTER_P33.ship_strategy_list:type_name -> belfast.STRATEGYINFO_P33
	2, // 4: belfast.GROUPINCHAPTER_P33.start_pos:type_name -> belfast.CHAPTERCELLPOS_P33
	4, // 5: belfast.GROUPINCHAPTER_P33.buff_list:type_name -> belfast.BUFF_INFO
	5, // 6: belfast.GROUPINCHAPTER_P33.commander_list:type_name -> belfast.COMMANDERSINFO
	6, // 7: belfast.GROUPINCHAPTER_P33.cmd_collection:type_name -> belfast.CMDCOLLECTION
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_GROUPINCHAPTER_P33_proto_init() }
func file_GROUPINCHAPTER_P33_proto_init() {
	if File_GROUPINCHAPTER_P33_proto != nil {
		return
	}
	file_BUFF_INFO_proto_init()
	file_CHAPTERCELLPOS_P33_proto_init()
	file_CMDCOLLECTION_proto_init()
	file_COMMANDERSINFO_proto_init()
	file_SHIPINCHAPTER_P33_proto_init()
	file_STRATEGYINFO_P33_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GROUPINCHAPTER_P33_proto_rawDesc), len(file_GROUPINCHAPTER_P33_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GROUPINCHAPTER_P33_proto_goTypes,
		DependencyIndexes: file_GROUPINCHAPTER_P33_proto_depIdxs,
		MessageInfos:      file_GROUPINCHAPTER_P33_proto_msgTypes,
	}.Build()
	File_GROUPINCHAPTER_P33_proto = out.File
	file_GROUPINCHAPTER_P33_proto_goTypes = nil
	file_GROUPINCHAPTER_P33_proto_depIdxs = nil
}
