// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: GUILD_SIMPLE_INFO.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GUILD_SIMPLE_INFO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *GUILD_BASE_INFO       `protobuf:"bytes,1,req,name=base" json:"base,omitempty"`
	Leader        *PLAYER_INFO_P60       `protobuf:"bytes,2,req,name=leader" json:"leader,omitempty"`
	TechSeat      *uint32                `protobuf:"varint,3,req,name=tech_seat,json=techSeat" json:"tech_seat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GUILD_SIMPLE_INFO) Reset() {
	*x = GUILD_SIMPLE_INFO{}
	mi := &file_GUILD_SIMPLE_INFO_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GUILD_SIMPLE_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GUILD_SIMPLE_INFO) ProtoMessage() {}

func (x *GUILD_SIMPLE_INFO) ProtoReflect() protoreflect.Message {
	mi := &file_GUILD_SIMPLE_INFO_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GUILD_SIMPLE_INFO.ProtoReflect.Descriptor instead.
func (*GUILD_SIMPLE_INFO) Descriptor() ([]byte, []int) {
	return file_GUILD_SIMPLE_INFO_proto_rawDescGZIP(), []int{0}
}

func (x *GUILD_SIMPLE_INFO) GetBase() *GUILD_BASE_INFO {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GUILD_SIMPLE_INFO) GetLeader() *PLAYER_INFO_P60 {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *GUILD_SIMPLE_INFO) GetTechSeat() uint32 {
	if x != nil && x.TechSeat != nil {
		return *x.TechSeat
	}
	return 0
}

var File_GUILD_SIMPLE_INFO_proto protoreflect.FileDescriptor

const file_GUILD_SIMPLE_INFO_proto_rawDesc = "" +
	"\n" +
	"\x17GUILD_SIMPLE_INFO.proto\x12\abelfast\x1a\x15GUILD_BASE_INFO.proto\x1a\x15PLAYER_INFO_P60.proto\"\x90\x01\n" +
	"\x11GUILD_SIMPLE_INFO\x12,\n" +
	"\x04base\x18\x01 \x02(\v2\x18.belfast.GUILD_BASE_INFOR\x04base\x120\n" +
	"\x06leader\x18\x02 \x02(\v2\x18.belfast.PLAYER_INFO_P60R\x06leader\x12\x1b\n" +
	"\ttech_seat\x18\x03 \x02(\rR\btechSeatB\fZ\n" +
	"./protobuf"

var (
	file_GUILD_SIMPLE_INFO_proto_rawDescOnce sync.Once
	file_GUILD_SIMPLE_INFO_proto_rawDescData []byte
)

func file_GUILD_SIMPLE_INFO_proto_rawDescGZIP() []byte {
	file_GUILD_SIMPLE_INFO_proto_rawDescOnce.Do(func() {
		file_GUILD_SIMPLE_INFO_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GUILD_SIMPLE_INFO_proto_rawDesc), len(file_GUILD_SIMPLE_INFO_proto_rawDesc)))
	})
	return file_GUILD_SIMPLE_INFO_proto_rawDescData
}

var file_GUILD_SIMPLE_INFO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GUILD_SIMPLE_INFO_proto_goTypes = []any{
	(*GUILD_SIMPLE_INFO)(nil), // 0: belfast.GUILD_SIMPLE_INFO
	(*GUILD_BASE_INFO)(nil),   // 1: belfast.GUILD_BASE_INFO
	(*PLAYER_INFO_P60)(nil),   // 2: belfast.PLAYER_INFO_P60
}
var file_GUILD_SIMPLE_INFO_proto_depIdxs = []int32{
	1, // 0: belfast.GUILD_SIMPLE_INFO.base:type_name -> belfast.GUILD_BASE_INFO
	2, // 1: belfast.GUILD_SIMPLE_INFO.leader:type_name -> belfast.PLAYER_INFO_P60
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_GUILD_SIMPLE_INFO_proto_init() }
func file_GUILD_SIMPLE_INFO_proto_init() {
	if File_GUILD_SIMPLE_INFO_proto != nil {
		return
	}
	file_GUILD_BASE_INFO_proto_init()
	file_PLAYER_INFO_P60_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GUILD_SIMPLE_INFO_proto_rawDesc), len(file_GUILD_SIMPLE_INFO_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GUILD_SIMPLE_INFO_proto_goTypes,
		DependencyIndexes: file_GUILD_SIMPLE_INFO_proto_depIdxs,
		MessageInfos:      file_GUILD_SIMPLE_INFO_proto_msgTypes,
	}.Build()
	File_GUILD_SIMPLE_INFO_proto = out.File
	file_GUILD_SIMPLE_INFO_proto_goTypes = nil
	file_GUILD_SIMPLE_INFO_proto_depIdxs = nil
}
