// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: HPDROPINFO.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HPDROPINFO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hp            *uint32                `protobuf:"varint,1,req,name=hp" json:"hp,omitempty"`
	DropInfo      []*DROPINFO            `protobuf:"bytes,2,rep,name=drop_info,json=dropInfo" json:"drop_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HPDROPINFO) Reset() {
	*x = HPDROPINFO{}
	mi := &file_HPDROPINFO_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HPDROPINFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HPDROPINFO) ProtoMessage() {}

func (x *HPDROPINFO) ProtoReflect() protoreflect.Message {
	mi := &file_HPDROPINFO_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HPDROPINFO.ProtoReflect.Descriptor instead.
func (*HPDROPINFO) Descriptor() ([]byte, []int) {
	return file_HPDROPINFO_proto_rawDescGZIP(), []int{0}
}

func (x *HPDROPINFO) GetHp() uint32 {
	if x != nil && x.Hp != nil {
		return *x.Hp
	}
	return 0
}

func (x *HPDROPINFO) GetDropInfo() []*DROPINFO {
	if x != nil {
		return x.DropInfo
	}
	return nil
}

var File_HPDROPINFO_proto protoreflect.FileDescriptor

const file_HPDROPINFO_proto_rawDesc = "" +
	"\n" +
	"\x10HPDROPINFO.proto\x12\abelfast\x1a\x0eDROPINFO.proto\"L\n" +
	"\n" +
	"HPDROPINFO\x12\x0e\n" +
	"\x02hp\x18\x01 \x02(\rR\x02hp\x12.\n" +
	"\tdrop_info\x18\x02 \x03(\v2\x11.belfast.DROPINFOR\bdropInfoB\fZ\n" +
	"./protobuf"

var (
	file_HPDROPINFO_proto_rawDescOnce sync.Once
	file_HPDROPINFO_proto_rawDescData []byte
)

func file_HPDROPINFO_proto_rawDescGZIP() []byte {
	file_HPDROPINFO_proto_rawDescOnce.Do(func() {
		file_HPDROPINFO_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_HPDROPINFO_proto_rawDesc), len(file_HPDROPINFO_proto_rawDesc)))
	})
	return file_HPDROPINFO_proto_rawDescData
}

var file_HPDROPINFO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_HPDROPINFO_proto_goTypes = []any{
	(*HPDROPINFO)(nil), // 0: belfast.HPDROPINFO
	(*DROPINFO)(nil),   // 1: belfast.DROPINFO
}
var file_HPDROPINFO_proto_depIdxs = []int32{
	1, // 0: belfast.HPDROPINFO.drop_info:type_name -> belfast.DROPINFO
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_HPDROPINFO_proto_init() }
func file_HPDROPINFO_proto_init() {
	if File_HPDROPINFO_proto != nil {
		return
	}
	file_DROPINFO_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_HPDROPINFO_proto_rawDesc), len(file_HPDROPINFO_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HPDROPINFO_proto_goTypes,
		DependencyIndexes: file_HPDROPINFO_proto_depIdxs,
		MessageInfos:      file_HPDROPINFO_proto_msgTypes,
	}.Build()
	File_HPDROPINFO_proto = out.File
	file_HPDROPINFO_proto_goTypes = nil
	file_HPDROPINFO_proto_depIdxs = nil
}
