// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ITEMMISC.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ITEMMISC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Data          *uint32                `protobuf:"varint,2,req,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ITEMMISC) Reset() {
	*x = ITEMMISC{}
	mi := &file_ITEMMISC_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ITEMMISC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ITEMMISC) ProtoMessage() {}

func (x *ITEMMISC) ProtoReflect() protoreflect.Message {
	mi := &file_ITEMMISC_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ITEMMISC.ProtoReflect.Descriptor instead.
func (*ITEMMISC) Descriptor() ([]byte, []int) {
	return file_ITEMMISC_proto_rawDescGZIP(), []int{0}
}

func (x *ITEMMISC) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *ITEMMISC) GetData() uint32 {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return 0
}

var File_ITEMMISC_proto protoreflect.FileDescriptor

const file_ITEMMISC_proto_rawDesc = "" +
	"\n" +
	"\x0eITEMMISC.proto\x12\abelfast\".\n" +
	"\bITEMMISC\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x02(\rR\x04dataB\fZ\n" +
	"./protobuf"

var (
	file_ITEMMISC_proto_rawDescOnce sync.Once
	file_ITEMMISC_proto_rawDescData []byte
)

func file_ITEMMISC_proto_rawDescGZIP() []byte {
	file_ITEMMISC_proto_rawDescOnce.Do(func() {
		file_ITEMMISC_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ITEMMISC_proto_rawDesc), len(file_ITEMMISC_proto_rawDesc)))
	})
	return file_ITEMMISC_proto_rawDescData
}

var file_ITEMMISC_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ITEMMISC_proto_goTypes = []any{
	(*ITEMMISC)(nil), // 0: belfast.ITEMMISC
}
var file_ITEMMISC_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ITEMMISC_proto_init() }
func file_ITEMMISC_proto_init() {
	if File_ITEMMISC_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ITEMMISC_proto_rawDesc), len(file_ITEMMISC_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ITEMMISC_proto_goTypes,
		DependencyIndexes: file_ITEMMISC_proto_depIdxs,
		MessageInfos:      file_ITEMMISC_proto_msgTypes,
	}.Build()
	File_ITEMMISC_proto = out.File
	file_ITEMMISC_proto_goTypes = nil
	file_ITEMMISC_proto_depIdxs = nil
}
