// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: KVDATA2.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KVDATA2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *uint32                `protobuf:"varint,1,req,name=key" json:"key,omitempty"`
	Value1        *uint32                `protobuf:"varint,2,req,name=value1" json:"value1,omitempty"`
	Value2        *uint32                `protobuf:"varint,3,req,name=value2" json:"value2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDATA2) Reset() {
	*x = KVDATA2{}
	mi := &file_KVDATA2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDATA2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDATA2) ProtoMessage() {}

func (x *KVDATA2) ProtoReflect() protoreflect.Message {
	mi := &file_KVDATA2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDATA2.ProtoReflect.Descriptor instead.
func (*KVDATA2) Descriptor() ([]byte, []int) {
	return file_KVDATA2_proto_rawDescGZIP(), []int{0}
}

func (x *KVDATA2) GetKey() uint32 {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return 0
}

func (x *KVDATA2) GetValue1() uint32 {
	if x != nil && x.Value1 != nil {
		return *x.Value1
	}
	return 0
}

func (x *KVDATA2) GetValue2() uint32 {
	if x != nil && x.Value2 != nil {
		return *x.Value2
	}
	return 0
}

var File_KVDATA2_proto protoreflect.FileDescriptor

const file_KVDATA2_proto_rawDesc = "" +
	"\n" +
	"\rKVDATA2.proto\x12\abelfast\"K\n" +
	"\aKVDATA2\x12\x10\n" +
	"\x03key\x18\x01 \x02(\rR\x03key\x12\x16\n" +
	"\x06value1\x18\x02 \x02(\rR\x06value1\x12\x16\n" +
	"\x06value2\x18\x03 \x02(\rR\x06value2B\fZ\n" +
	"./protobuf"

var (
	file_KVDATA2_proto_rawDescOnce sync.Once
	file_KVDATA2_proto_rawDescData []byte
)

func file_KVDATA2_proto_rawDescGZIP() []byte {
	file_KVDATA2_proto_rawDescOnce.Do(func() {
		file_KVDATA2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_KVDATA2_proto_rawDesc), len(file_KVDATA2_proto_rawDesc)))
	})
	return file_KVDATA2_proto_rawDescData
}

var file_KVDATA2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_KVDATA2_proto_goTypes = []any{
	(*KVDATA2)(nil), // 0: belfast.KVDATA2
}
var file_KVDATA2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_KVDATA2_proto_init() }
func file_KVDATA2_proto_init() {
	if File_KVDATA2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_KVDATA2_proto_rawDesc), len(file_KVDATA2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_KVDATA2_proto_goTypes,
		DependencyIndexes: file_KVDATA2_proto_depIdxs,
		MessageInfos:      file_KVDATA2_proto_msgTypes,
	}.Build()
	File_KVDATA2_proto = out.File
	file_KVDATA2_proto_goTypes = nil
	file_KVDATA2_proto_depIdxs = nil
}
