// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: LIVINGAREA_COVER.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LIVINGAREA_COVER struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Covers        []uint32               `protobuf:"varint,2,rep,name=covers" json:"covers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LIVINGAREA_COVER) Reset() {
	*x = LIVINGAREA_COVER{}
	mi := &file_LIVINGAREA_COVER_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LIVINGAREA_COVER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LIVINGAREA_COVER) ProtoMessage() {}

func (x *LIVINGAREA_COVER) ProtoReflect() protoreflect.Message {
	mi := &file_LIVINGAREA_COVER_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LIVINGAREA_COVER.ProtoReflect.Descriptor instead.
func (*LIVINGAREA_COVER) Descriptor() ([]byte, []int) {
	return file_LIVINGAREA_COVER_proto_rawDescGZIP(), []int{0}
}

func (x *LIVINGAREA_COVER) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *LIVINGAREA_COVER) GetCovers() []uint32 {
	if x != nil {
		return x.Covers
	}
	return nil
}

var File_LIVINGAREA_COVER_proto protoreflect.FileDescriptor

const file_LIVINGAREA_COVER_proto_rawDesc = "" +
	"\n" +
	"\x16LIVINGAREA_COVER.proto\x12\abelfast\":\n" +
	"\x10LIVINGAREA_COVER\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x16\n" +
	"\x06covers\x18\x02 \x03(\rR\x06coversB\fZ\n" +
	"./protobuf"

var (
	file_LIVINGAREA_COVER_proto_rawDescOnce sync.Once
	file_LIVINGAREA_COVER_proto_rawDescData []byte
)

func file_LIVINGAREA_COVER_proto_rawDescGZIP() []byte {
	file_LIVINGAREA_COVER_proto_rawDescOnce.Do(func() {
		file_LIVINGAREA_COVER_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_LIVINGAREA_COVER_proto_rawDesc), len(file_LIVINGAREA_COVER_proto_rawDesc)))
	})
	return file_LIVINGAREA_COVER_proto_rawDescData
}

var file_LIVINGAREA_COVER_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_LIVINGAREA_COVER_proto_goTypes = []any{
	(*LIVINGAREA_COVER)(nil), // 0: belfast.LIVINGAREA_COVER
}
var file_LIVINGAREA_COVER_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_LIVINGAREA_COVER_proto_init() }
func file_LIVINGAREA_COVER_proto_init() {
	if File_LIVINGAREA_COVER_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_LIVINGAREA_COVER_proto_rawDesc), len(file_LIVINGAREA_COVER_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_LIVINGAREA_COVER_proto_goTypes,
		DependencyIndexes: file_LIVINGAREA_COVER_proto_depIdxs,
		MessageInfos:      file_LIVINGAREA_COVER_proto_msgTypes,
	}.Build()
	File_LIVINGAREA_COVER_proto = out.File
	file_LIVINGAREA_COVER_proto_goTypes = nil
	file_LIVINGAREA_COVER_proto_depIdxs = nil
}
