// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: MSG_INFO_P60.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MSG_INFO_P60 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *uint32                `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	Player        *PLAYER_INFO_P60       `protobuf:"bytes,2,req,name=player" json:"player,omitempty"`
	Content       *string                `protobuf:"bytes,3,req,name=content" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSG_INFO_P60) Reset() {
	*x = MSG_INFO_P60{}
	mi := &file_MSG_INFO_P60_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSG_INFO_P60) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_INFO_P60) ProtoMessage() {}

func (x *MSG_INFO_P60) ProtoReflect() protoreflect.Message {
	mi := &file_MSG_INFO_P60_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_INFO_P60.ProtoReflect.Descriptor instead.
func (*MSG_INFO_P60) Descriptor() ([]byte, []int) {
	return file_MSG_INFO_P60_proto_rawDescGZIP(), []int{0}
}

func (x *MSG_INFO_P60) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *MSG_INFO_P60) GetPlayer() *PLAYER_INFO_P60 {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *MSG_INFO_P60) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

var File_MSG_INFO_P60_proto protoreflect.FileDescriptor

const file_MSG_INFO_P60_proto_rawDesc = "" +
	"\n" +
	"\x12MSG_INFO_P60.proto\x12\abelfast\x1a\x15PLAYER_INFO_P60.proto\"x\n" +
	"\fMSG_INFO_P60\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x02(\rR\ttimestamp\x120\n" +
	"\x06player\x18\x02 \x02(\v2\x18.belfast.PLAYER_INFO_P60R\x06player\x12\x18\n" +
	"\acontent\x18\x03 \x02(\tR\acontentB\fZ\n" +
	"./protobuf"

var (
	file_MSG_INFO_P60_proto_rawDescOnce sync.Once
	file_MSG_INFO_P60_proto_rawDescData []byte
)

func file_MSG_INFO_P60_proto_rawDescGZIP() []byte {
	file_MSG_INFO_P60_proto_rawDescOnce.Do(func() {
		file_MSG_INFO_P60_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_MSG_INFO_P60_proto_rawDesc), len(file_MSG_INFO_P60_proto_rawDesc)))
	})
	return file_MSG_INFO_P60_proto_rawDescData
}

var file_MSG_INFO_P60_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_MSG_INFO_P60_proto_goTypes = []any{
	(*MSG_INFO_P60)(nil),    // 0: belfast.MSG_INFO_P60
	(*PLAYER_INFO_P60)(nil), // 1: belfast.PLAYER_INFO_P60
}
var file_MSG_INFO_P60_proto_depIdxs = []int32{
	1, // 0: belfast.MSG_INFO_P60.player:type_name -> belfast.PLAYER_INFO_P60
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_MSG_INFO_P60_proto_init() }
func file_MSG_INFO_P60_proto_init() {
	if File_MSG_INFO_P60_proto != nil {
		return
	}
	file_PLAYER_INFO_P60_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_MSG_INFO_P60_proto_rawDesc), len(file_MSG_INFO_P60_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MSG_INFO_P60_proto_goTypes,
		DependencyIndexes: file_MSG_INFO_P60_proto_depIdxs,
		MessageInfos:      file_MSG_INFO_P60_proto_msgTypes,
	}.Build()
	File_MSG_INFO_P60_proto = out.File
	file_MSG_INFO_P60_proto_goTypes = nil
	file_MSG_INFO_P60_proto_depIdxs = nil
}
