// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: NAVALACADEMY_STUDENT.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NAVALACADEMY_STUDENT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipId        *uint32                `protobuf:"varint,1,req,name=ship_id,json=shipId" json:"ship_id,omitempty"`
	Energy        *uint32                `protobuf:"varint,2,req,name=energy" json:"energy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NAVALACADEMY_STUDENT) Reset() {
	*x = NAVALACADEMY_STUDENT{}
	mi := &file_NAVALACADEMY_STUDENT_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NAVALACADEMY_STUDENT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NAVALACADEMY_STUDENT) ProtoMessage() {}

func (x *NAVALACADEMY_STUDENT) ProtoReflect() protoreflect.Message {
	mi := &file_NAVALACADEMY_STUDENT_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NAVALACADEMY_STUDENT.ProtoReflect.Descriptor instead.
func (*NAVALACADEMY_STUDENT) Descriptor() ([]byte, []int) {
	return file_NAVALACADEMY_STUDENT_proto_rawDescGZIP(), []int{0}
}

func (x *NAVALACADEMY_STUDENT) GetShipId() uint32 {
	if x != nil && x.ShipId != nil {
		return *x.ShipId
	}
	return 0
}

func (x *NAVALACADEMY_STUDENT) GetEnergy() uint32 {
	if x != nil && x.Energy != nil {
		return *x.Energy
	}
	return 0
}

var File_NAVALACADEMY_STUDENT_proto protoreflect.FileDescriptor

const file_NAVALACADEMY_STUDENT_proto_rawDesc = "" +
	"\n" +
	"\x1aNAVALACADEMY_STUDENT.proto\x12\abelfast\"G\n" +
	"\x14NAVALACADEMY_STUDENT\x12\x17\n" +
	"\aship_id\x18\x01 \x02(\rR\x06shipId\x12\x16\n" +
	"\x06energy\x18\x02 \x02(\rR\x06energyB\fZ\n" +
	"./protobuf"

var (
	file_NAVALACADEMY_STUDENT_proto_rawDescOnce sync.Once
	file_NAVALACADEMY_STUDENT_proto_rawDescData []byte
)

func file_NAVALACADEMY_STUDENT_proto_rawDescGZIP() []byte {
	file_NAVALACADEMY_STUDENT_proto_rawDescOnce.Do(func() {
		file_NAVALACADEMY_STUDENT_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_NAVALACADEMY_STUDENT_proto_rawDesc), len(file_NAVALACADEMY_STUDENT_proto_rawDesc)))
	})
	return file_NAVALACADEMY_STUDENT_proto_rawDescData
}

var file_NAVALACADEMY_STUDENT_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_NAVALACADEMY_STUDENT_proto_goTypes = []any{
	(*NAVALACADEMY_STUDENT)(nil), // 0: belfast.NAVALACADEMY_STUDENT
}
var file_NAVALACADEMY_STUDENT_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_NAVALACADEMY_STUDENT_proto_init() }
func file_NAVALACADEMY_STUDENT_proto_init() {
	if File_NAVALACADEMY_STUDENT_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_NAVALACADEMY_STUDENT_proto_rawDesc), len(file_NAVALACADEMY_STUDENT_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_NAVALACADEMY_STUDENT_proto_goTypes,
		DependencyIndexes: file_NAVALACADEMY_STUDENT_proto_depIdxs,
		MessageInfos:      file_NAVALACADEMY_STUDENT_proto_msgTypes,
	}.Build()
	File_NAVALACADEMY_STUDENT_proto = out.File
	file_NAVALACADEMY_STUDENT_proto_goTypes = nil
	file_NAVALACADEMY_STUDENT_proto_depIdxs = nil
}
