// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: OTHERSHIPID.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OTHERSHIPID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipId        *uint32                `protobuf:"varint,1,req,name=ship_id,json=shipId" json:"ship_id,omitempty"`
	UserId        *uint32                `protobuf:"varint,2,req,name=user_id,json=userId" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OTHERSHIPID) Reset() {
	*x = OTHERSHIPID{}
	mi := &file_OTHERSHIPID_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OTHERSHIPID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTHERSHIPID) ProtoMessage() {}

func (x *OTHERSHIPID) ProtoReflect() protoreflect.Message {
	mi := &file_OTHERSHIPID_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTHERSHIPID.ProtoReflect.Descriptor instead.
func (*OTHERSHIPID) Descriptor() ([]byte, []int) {
	return file_OTHERSHIPID_proto_rawDescGZIP(), []int{0}
}

func (x *OTHERSHIPID) GetShipId() uint32 {
	if x != nil && x.ShipId != nil {
		return *x.ShipId
	}
	return 0
}

func (x *OTHERSHIPID) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

var File_OTHERSHIPID_proto protoreflect.FileDescriptor

const file_OTHERSHIPID_proto_rawDesc = "" +
	"\n" +
	"\x11OTHERSHIPID.proto\x12\abelfast\"?\n" +
	"\vOTHERSHIPID\x12\x17\n" +
	"\aship_id\x18\x01 \x02(\rR\x06shipId\x12\x17\n" +
	"\auser_id\x18\x02 \x02(\rR\x06userIdB\fZ\n" +
	"./protobuf"

var (
	file_OTHERSHIPID_proto_rawDescOnce sync.Once
	file_OTHERSHIPID_proto_rawDescData []byte
)

func file_OTHERSHIPID_proto_rawDescGZIP() []byte {
	file_OTHERSHIPID_proto_rawDescOnce.Do(func() {
		file_OTHERSHIPID_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_OTHERSHIPID_proto_rawDesc), len(file_OTHERSHIPID_proto_rawDesc)))
	})
	return file_OTHERSHIPID_proto_rawDescData
}

var file_OTHERSHIPID_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_OTHERSHIPID_proto_goTypes = []any{
	(*OTHERSHIPID)(nil), // 0: belfast.OTHERSHIPID
}
var file_OTHERSHIPID_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_OTHERSHIPID_proto_init() }
func file_OTHERSHIPID_proto_init() {
	if File_OTHERSHIPID_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_OTHERSHIPID_proto_rawDesc), len(file_OTHERSHIPID_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OTHERSHIPID_proto_goTypes,
		DependencyIndexes: file_OTHERSHIPID_proto_depIdxs,
		MessageInfos:      file_OTHERSHIPID_proto_msgTypes,
	}.Build()
	File_OTHERSHIPID_proto = out.File
	file_OTHERSHIPID_proto_goTypes = nil
	file_OTHERSHIPID_proto_depIdxs = nil
}
