// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PB_ISLAND_COLLECT_SYS.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PB_ISLAND_COLLECT_SYS struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	CollectItem   []*PB_ISLAND_COLLECT_ITEM `protobuf:"bytes,1,rep,name=collect_item,json=collectItem" json:"collect_item,omitempty"`
	FinishList    []uint32                  `protobuf:"varint,2,rep,name=finish_list,json=finishList" json:"finish_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PB_ISLAND_COLLECT_SYS) Reset() {
	*x = PB_ISLAND_COLLECT_SYS{}
	mi := &file_PB_ISLAND_COLLECT_SYS_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PB_ISLAND_COLLECT_SYS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PB_ISLAND_COLLECT_SYS) ProtoMessage() {}

func (x *PB_ISLAND_COLLECT_SYS) ProtoReflect() protoreflect.Message {
	mi := &file_PB_ISLAND_COLLECT_SYS_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PB_ISLAND_COLLECT_SYS.ProtoReflect.Descriptor instead.
func (*PB_ISLAND_COLLECT_SYS) Descriptor() ([]byte, []int) {
	return file_PB_ISLAND_COLLECT_SYS_proto_rawDescGZIP(), []int{0}
}

func (x *PB_ISLAND_COLLECT_SYS) GetCollectItem() []*PB_ISLAND_COLLECT_ITEM {
	if x != nil {
		return x.CollectItem
	}
	return nil
}

func (x *PB_ISLAND_COLLECT_SYS) GetFinishList() []uint32 {
	if x != nil {
		return x.FinishList
	}
	return nil
}

var File_PB_ISLAND_COLLECT_SYS_proto protoreflect.FileDescriptor

const file_PB_ISLAND_COLLECT_SYS_proto_rawDesc = "" +
	"\n" +
	"\x1bPB_ISLAND_COLLECT_SYS.proto\x12\abelfast\x1a\x1cPB_ISLAND_COLLECT_ITEM.proto\"|\n" +
	"\x15PB_ISLAND_COLLECT_SYS\x12B\n" +
	"\fcollect_item\x18\x01 \x03(\v2\x1f.belfast.PB_ISLAND_COLLECT_ITEMR\vcollectItem\x12\x1f\n" +
	"\vfinish_list\x18\x02 \x03(\rR\n" +
	"finishListB\fZ\n" +
	"./protobuf"

var (
	file_PB_ISLAND_COLLECT_SYS_proto_rawDescOnce sync.Once
	file_PB_ISLAND_COLLECT_SYS_proto_rawDescData []byte
)

func file_PB_ISLAND_COLLECT_SYS_proto_rawDescGZIP() []byte {
	file_PB_ISLAND_COLLECT_SYS_proto_rawDescOnce.Do(func() {
		file_PB_ISLAND_COLLECT_SYS_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_ISLAND_COLLECT_SYS_proto_rawDesc), len(file_PB_ISLAND_COLLECT_SYS_proto_rawDesc)))
	})
	return file_PB_ISLAND_COLLECT_SYS_proto_rawDescData
}

var file_PB_ISLAND_COLLECT_SYS_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PB_ISLAND_COLLECT_SYS_proto_goTypes = []any{
	(*PB_ISLAND_COLLECT_SYS)(nil),  // 0: belfast.PB_ISLAND_COLLECT_SYS
	(*PB_ISLAND_COLLECT_ITEM)(nil), // 1: belfast.PB_ISLAND_COLLECT_ITEM
}
var file_PB_ISLAND_COLLECT_SYS_proto_depIdxs = []int32{
	1, // 0: belfast.PB_ISLAND_COLLECT_SYS.collect_item:type_name -> belfast.PB_ISLAND_COLLECT_ITEM
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PB_ISLAND_COLLECT_SYS_proto_init() }
func file_PB_ISLAND_COLLECT_SYS_proto_init() {
	if File_PB_ISLAND_COLLECT_SYS_proto != nil {
		return
	}
	file_PB_ISLAND_COLLECT_ITEM_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_ISLAND_COLLECT_SYS_proto_rawDesc), len(file_PB_ISLAND_COLLECT_SYS_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PB_ISLAND_COLLECT_SYS_proto_goTypes,
		DependencyIndexes: file_PB_ISLAND_COLLECT_SYS_proto_depIdxs,
		MessageInfos:      file_PB_ISLAND_COLLECT_SYS_proto_msgTypes,
	}.Build()
	File_PB_ISLAND_COLLECT_SYS_proto = out.File
	file_PB_ISLAND_COLLECT_SYS_proto_goTypes = nil
	file_PB_ISLAND_COLLECT_SYS_proto_depIdxs = nil
}
