// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PB_ISLAND.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PB_ISLAND struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicData    *PB_ISLAND_PUBLIC      `protobuf:"bytes,1,req,name=public_data,json=publicData" json:"public_data,omitempty"`
	PrivateData   *PB_ISLAND_PRIVATE     `protobuf:"bytes,2,opt,name=private_data,json=privateData" json:"private_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PB_ISLAND) Reset() {
	*x = PB_ISLAND{}
	mi := &file_PB_ISLAND_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PB_ISLAND) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PB_ISLAND) ProtoMessage() {}

func (x *PB_ISLAND) ProtoReflect() protoreflect.Message {
	mi := &file_PB_ISLAND_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PB_ISLAND.ProtoReflect.Descriptor instead.
func (*PB_ISLAND) Descriptor() ([]byte, []int) {
	return file_PB_ISLAND_proto_rawDescGZIP(), []int{0}
}

func (x *PB_ISLAND) GetPublicData() *PB_ISLAND_PUBLIC {
	if x != nil {
		return x.PublicData
	}
	return nil
}

func (x *PB_ISLAND) GetPrivateData() *PB_ISLAND_PRIVATE {
	if x != nil {
		return x.PrivateData
	}
	return nil
}

var File_PB_ISLAND_proto protoreflect.FileDescriptor

const file_PB_ISLAND_proto_rawDesc = "" +
	"\n" +
	"\x0fPB_ISLAND.proto\x12\abelfast\x1a\x17PB_ISLAND_PRIVATE.proto\x1a\x16PB_ISLAND_PUBLIC.proto\"\x86\x01\n" +
	"\tPB_ISLAND\x12:\n" +
	"\vpublic_data\x18\x01 \x02(\v2\x19.belfast.PB_ISLAND_PUBLICR\n" +
	"publicData\x12=\n" +
	"\fprivate_data\x18\x02 \x01(\v2\x1a.belfast.PB_ISLAND_PRIVATER\vprivateDataB\fZ\n" +
	"./protobuf"

var (
	file_PB_ISLAND_proto_rawDescOnce sync.Once
	file_PB_ISLAND_proto_rawDescData []byte
)

func file_PB_ISLAND_proto_rawDescGZIP() []byte {
	file_PB_ISLAND_proto_rawDescOnce.Do(func() {
		file_PB_ISLAND_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_ISLAND_proto_rawDesc), len(file_PB_ISLAND_proto_rawDesc)))
	})
	return file_PB_ISLAND_proto_rawDescData
}

var file_PB_ISLAND_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PB_ISLAND_proto_goTypes = []any{
	(*PB_ISLAND)(nil),         // 0: belfast.PB_ISLAND
	(*PB_ISLAND_PUBLIC)(nil),  // 1: belfast.PB_ISLAND_PUBLIC
	(*PB_ISLAND_PRIVATE)(nil), // 2: belfast.PB_ISLAND_PRIVATE
}
var file_PB_ISLAND_proto_depIdxs = []int32{
	1, // 0: belfast.PB_ISLAND.public_data:type_name -> belfast.PB_ISLAND_PUBLIC
	2, // 1: belfast.PB_ISLAND.private_data:type_name -> belfast.PB_ISLAND_PRIVATE
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PB_ISLAND_proto_init() }
func file_PB_ISLAND_proto_init() {
	if File_PB_ISLAND_proto != nil {
		return
	}
	file_PB_ISLAND_PRIVATE_proto_init()
	file_PB_ISLAND_PUBLIC_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_ISLAND_proto_rawDesc), len(file_PB_ISLAND_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PB_ISLAND_proto_goTypes,
		DependencyIndexes: file_PB_ISLAND_proto_depIdxs,
		MessageInfos:      file_PB_ISLAND_proto_msgTypes,
	}.Build()
	File_PB_ISLAND_proto = out.File
	file_PB_ISLAND_proto_goTypes = nil
	file_PB_ISLAND_proto_depIdxs = nil
}
