// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PB_ISLAND_TRADE_SYS.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PB_ISLAND_TRADE_SYS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TodayEvent    *uint32                `protobuf:"varint,1,req,name=today_event,json=todayEvent" json:"today_event,omitempty"`
	TodayTrade    *uint32                `protobuf:"varint,2,req,name=today_trade,json=todayTrade" json:"today_trade,omitempty"`
	Effect        []*PB_EVENT_EFFECT     `protobuf:"bytes,3,rep,name=effect" json:"effect,omitempty"`
	TodayNum      []*PB_TRADE_NUM        `protobuf:"bytes,4,rep,name=today_num,json=todayNum" json:"today_num,omitempty"`
	TradeList     []*PB_ISLAND_TRADE     `protobuf:"bytes,5,rep,name=trade_list,json=tradeList" json:"trade_list,omitempty"`
	PresellList   []*PB_TRADE_PRESELL    `protobuf:"bytes,6,rep,name=presell_list,json=presellList" json:"presell_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PB_ISLAND_TRADE_SYS) Reset() {
	*x = PB_ISLAND_TRADE_SYS{}
	mi := &file_PB_ISLAND_TRADE_SYS_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PB_ISLAND_TRADE_SYS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PB_ISLAND_TRADE_SYS) ProtoMessage() {}

func (x *PB_ISLAND_TRADE_SYS) ProtoReflect() protoreflect.Message {
	mi := &file_PB_ISLAND_TRADE_SYS_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PB_ISLAND_TRADE_SYS.ProtoReflect.Descriptor instead.
func (*PB_ISLAND_TRADE_SYS) Descriptor() ([]byte, []int) {
	return file_PB_ISLAND_TRADE_SYS_proto_rawDescGZIP(), []int{0}
}

func (x *PB_ISLAND_TRADE_SYS) GetTodayEvent() uint32 {
	if x != nil && x.TodayEvent != nil {
		return *x.TodayEvent
	}
	return 0
}

func (x *PB_ISLAND_TRADE_SYS) GetTodayTrade() uint32 {
	if x != nil && x.TodayTrade != nil {
		return *x.TodayTrade
	}
	return 0
}

func (x *PB_ISLAND_TRADE_SYS) GetEffect() []*PB_EVENT_EFFECT {
	if x != nil {
		return x.Effect
	}
	return nil
}

func (x *PB_ISLAND_TRADE_SYS) GetTodayNum() []*PB_TRADE_NUM {
	if x != nil {
		return x.TodayNum
	}
	return nil
}

func (x *PB_ISLAND_TRADE_SYS) GetTradeList() []*PB_ISLAND_TRADE {
	if x != nil {
		return x.TradeList
	}
	return nil
}

func (x *PB_ISLAND_TRADE_SYS) GetPresellList() []*PB_TRADE_PRESELL {
	if x != nil {
		return x.PresellList
	}
	return nil
}

var File_PB_ISLAND_TRADE_SYS_proto protoreflect.FileDescriptor

const file_PB_ISLAND_TRADE_SYS_proto_rawDesc = "" +
	"\n" +
	"\x19PB_ISLAND_TRADE_SYS.proto\x12\abelfast\x1a\x15PB_EVENT_EFFECT.proto\x1a\x15PB_ISLAND_TRADE.proto\x1a\x12PB_TRADE_NUM.proto\x1a\x16PB_TRADE_PRESELL.proto\"\xb4\x02\n" +
	"\x13PB_ISLAND_TRADE_SYS\x12\x1f\n" +
	"\vtoday_event\x18\x01 \x02(\rR\n" +
	"todayEvent\x12\x1f\n" +
	"\vtoday_trade\x18\x02 \x02(\rR\n" +
	"todayTrade\x120\n" +
	"\x06effect\x18\x03 \x03(\v2\x18.belfast.PB_EVENT_EFFECTR\x06effect\x122\n" +
	"\ttoday_num\x18\x04 \x03(\v2\x15.belfast.PB_TRADE_NUMR\btodayNum\x127\n" +
	"\n" +
	"trade_list\x18\x05 \x03(\v2\x18.belfast.PB_ISLAND_TRADER\ttradeList\x12<\n" +
	"\fpresell_list\x18\x06 \x03(\v2\x19.belfast.PB_TRADE_PRESELLR\vpresellListB\fZ\n" +
	"./protobuf"

var (
	file_PB_ISLAND_TRADE_SYS_proto_rawDescOnce sync.Once
	file_PB_ISLAND_TRADE_SYS_proto_rawDescData []byte
)

func file_PB_ISLAND_TRADE_SYS_proto_rawDescGZIP() []byte {
	file_PB_ISLAND_TRADE_SYS_proto_rawDescOnce.Do(func() {
		file_PB_ISLAND_TRADE_SYS_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_ISLAND_TRADE_SYS_proto_rawDesc), len(file_PB_ISLAND_TRADE_SYS_proto_rawDesc)))
	})
	return file_PB_ISLAND_TRADE_SYS_proto_rawDescData
}

var file_PB_ISLAND_TRADE_SYS_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PB_ISLAND_TRADE_SYS_proto_goTypes = []any{
	(*PB_ISLAND_TRADE_SYS)(nil), // 0: belfast.PB_ISLAND_TRADE_SYS
	(*PB_EVENT_EFFECT)(nil),     // 1: belfast.PB_EVENT_EFFECT
	(*PB_TRADE_NUM)(nil),        // 2: belfast.PB_TRADE_NUM
	(*PB_ISLAND_TRADE)(nil),     // 3: belfast.PB_ISLAND_TRADE
	(*PB_TRADE_PRESELL)(nil),    // 4: belfast.PB_TRADE_PRESELL
}
var file_PB_ISLAND_TRADE_SYS_proto_depIdxs = []int32{
	1, // 0: belfast.PB_ISLAND_TRADE_SYS.effect:type_name -> belfast.PB_EVENT_EFFECT
	2, // 1: belfast.PB_ISLAND_TRADE_SYS.today_num:type_name -> belfast.PB_TRADE_NUM
	3, // 2: belfast.PB_ISLAND_TRADE_SYS.trade_list:type_name -> belfast.PB_ISLAND_TRADE
	4, // 3: belfast.PB_ISLAND_TRADE_SYS.presell_list:type_name -> belfast.PB_TRADE_PRESELL
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_PB_ISLAND_TRADE_SYS_proto_init() }
func file_PB_ISLAND_TRADE_SYS_proto_init() {
	if File_PB_ISLAND_TRADE_SYS_proto != nil {
		return
	}
	file_PB_EVENT_EFFECT_proto_init()
	file_PB_ISLAND_TRADE_proto_init()
	file_PB_TRADE_NUM_proto_init()
	file_PB_TRADE_PRESELL_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_ISLAND_TRADE_SYS_proto_rawDesc), len(file_PB_ISLAND_TRADE_SYS_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PB_ISLAND_TRADE_SYS_proto_goTypes,
		DependencyIndexes: file_PB_ISLAND_TRADE_SYS_proto_depIdxs,
		MessageInfos:      file_PB_ISLAND_TRADE_SYS_proto_msgTypes,
	}.Build()
	File_PB_ISLAND_TRADE_SYS_proto = out.File
	file_PB_ISLAND_TRADE_SYS_proto_goTypes = nil
	file_PB_ISLAND_TRADE_SYS_proto_depIdxs = nil
}
