// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PB_SPEEDUP_KEY.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PB_SPEEDUP_KEY struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpeedId       *uint32                `protobuf:"varint,1,req,name=speed_id,json=speedId" json:"speed_id,omitempty"`
	EndTime       *uint32                `protobuf:"varint,2,req,name=end_time,json=endTime" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PB_SPEEDUP_KEY) Reset() {
	*x = PB_SPEEDUP_KEY{}
	mi := &file_PB_SPEEDUP_KEY_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PB_SPEEDUP_KEY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PB_SPEEDUP_KEY) ProtoMessage() {}

func (x *PB_SPEEDUP_KEY) ProtoReflect() protoreflect.Message {
	mi := &file_PB_SPEEDUP_KEY_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PB_SPEEDUP_KEY.ProtoReflect.Descriptor instead.
func (*PB_SPEEDUP_KEY) Descriptor() ([]byte, []int) {
	return file_PB_SPEEDUP_KEY_proto_rawDescGZIP(), []int{0}
}

func (x *PB_SPEEDUP_KEY) GetSpeedId() uint32 {
	if x != nil && x.SpeedId != nil {
		return *x.SpeedId
	}
	return 0
}

func (x *PB_SPEEDUP_KEY) GetEndTime() uint32 {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return 0
}

var File_PB_SPEEDUP_KEY_proto protoreflect.FileDescriptor

const file_PB_SPEEDUP_KEY_proto_rawDesc = "" +
	"\n" +
	"\x14PB_SPEEDUP_KEY.proto\x12\abelfast\"F\n" +
	"\x0ePB_SPEEDUP_KEY\x12\x19\n" +
	"\bspeed_id\x18\x01 \x02(\rR\aspeedId\x12\x19\n" +
	"\bend_time\x18\x02 \x02(\rR\aendTimeB\fZ\n" +
	"./protobuf"

var (
	file_PB_SPEEDUP_KEY_proto_rawDescOnce sync.Once
	file_PB_SPEEDUP_KEY_proto_rawDescData []byte
)

func file_PB_SPEEDUP_KEY_proto_rawDescGZIP() []byte {
	file_PB_SPEEDUP_KEY_proto_rawDescOnce.Do(func() {
		file_PB_SPEEDUP_KEY_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_SPEEDUP_KEY_proto_rawDesc), len(file_PB_SPEEDUP_KEY_proto_rawDesc)))
	})
	return file_PB_SPEEDUP_KEY_proto_rawDescData
}

var file_PB_SPEEDUP_KEY_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PB_SPEEDUP_KEY_proto_goTypes = []any{
	(*PB_SPEEDUP_KEY)(nil), // 0: belfast.PB_SPEEDUP_KEY
}
var file_PB_SPEEDUP_KEY_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PB_SPEEDUP_KEY_proto_init() }
func file_PB_SPEEDUP_KEY_proto_init() {
	if File_PB_SPEEDUP_KEY_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_SPEEDUP_KEY_proto_rawDesc), len(file_PB_SPEEDUP_KEY_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PB_SPEEDUP_KEY_proto_goTypes,
		DependencyIndexes: file_PB_SPEEDUP_KEY_proto_depIdxs,
		MessageInfos:      file_PB_SPEEDUP_KEY_proto_msgTypes,
	}.Build()
	File_PB_SPEEDUP_KEY_proto = out.File
	file_PB_SPEEDUP_KEY_proto_goTypes = nil
	file_PB_SPEEDUP_KEY_proto_depIdxs = nil
}
