// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PB_SET_FLAG.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PB_SET_FLAG struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *uint32                `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Flag          *uint32                `protobuf:"varint,2,req,name=flag" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PB_SET_FLAG) Reset() {
	*x = PB_SET_FLAG{}
	mi := &file_PB_SET_FLAG_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PB_SET_FLAG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PB_SET_FLAG) ProtoMessage() {}

func (x *PB_SET_FLAG) ProtoReflect() protoreflect.Message {
	mi := &file_PB_SET_FLAG_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PB_SET_FLAG.ProtoReflect.Descriptor instead.
func (*PB_SET_FLAG) Descriptor() ([]byte, []int) {
	return file_PB_SET_FLAG_proto_rawDescGZIP(), []int{0}
}

func (x *PB_SET_FLAG) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *PB_SET_FLAG) GetFlag() uint32 {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return 0
}

var File_PB_SET_FLAG_proto protoreflect.FileDescriptor

const file_PB_SET_FLAG_proto_rawDesc = "" +
	"\n" +
	"\x11PB_SET_FLAG.proto\x12\abelfast\"5\n" +
	"\vPB_SET_FLAG\x12\x12\n" +
	"\x04type\x18\x01 \x02(\rR\x04type\x12\x12\n" +
	"\x04flag\x18\x02 \x02(\rR\x04flagB\fZ\n" +
	"./protobuf"

var (
	file_PB_SET_FLAG_proto_rawDescOnce sync.Once
	file_PB_SET_FLAG_proto_rawDescData []byte
)

func file_PB_SET_FLAG_proto_rawDescGZIP() []byte {
	file_PB_SET_FLAG_proto_rawDescOnce.Do(func() {
		file_PB_SET_FLAG_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_SET_FLAG_proto_rawDesc), len(file_PB_SET_FLAG_proto_rawDesc)))
	})
	return file_PB_SET_FLAG_proto_rawDescData
}

var file_PB_SET_FLAG_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PB_SET_FLAG_proto_goTypes = []any{
	(*PB_SET_FLAG)(nil), // 0: belfast.PB_SET_FLAG
}
var file_PB_SET_FLAG_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PB_SET_FLAG_proto_init() }
func file_PB_SET_FLAG_proto_init() {
	if File_PB_SET_FLAG_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_SET_FLAG_proto_rawDesc), len(file_PB_SET_FLAG_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PB_SET_FLAG_proto_goTypes,
		DependencyIndexes: file_PB_SET_FLAG_proto_depIdxs,
		MessageInfos:      file_PB_SET_FLAG_proto_msgTypes,
	}.Build()
	File_PB_SET_FLAG_proto = out.File
	file_PB_SET_FLAG_proto_goTypes = nil
	file_PB_SET_FLAG_proto_depIdxs = nil
}
