// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PB_VISITOR.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PB_VISITOR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Time          *uint32                `protobuf:"varint,3,req,name=time" json:"time,omitempty"`
	Cmd           *uint32                `protobuf:"varint,4,req,name=cmd" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PB_VISITOR) Reset() {
	*x = PB_VISITOR{}
	mi := &file_PB_VISITOR_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PB_VISITOR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PB_VISITOR) ProtoMessage() {}

func (x *PB_VISITOR) ProtoReflect() protoreflect.Message {
	mi := &file_PB_VISITOR_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PB_VISITOR.ProtoReflect.Descriptor instead.
func (*PB_VISITOR) Descriptor() ([]byte, []int) {
	return file_PB_VISITOR_proto_rawDescGZIP(), []int{0}
}

func (x *PB_VISITOR) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PB_VISITOR) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PB_VISITOR) GetTime() uint32 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *PB_VISITOR) GetCmd() uint32 {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return 0
}

var File_PB_VISITOR_proto protoreflect.FileDescriptor

const file_PB_VISITOR_proto_rawDesc = "" +
	"\n" +
	"\x10PB_VISITOR.proto\x12\abelfast\"V\n" +
	"\n" +
	"PB_VISITOR\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x02(\tR\x04name\x12\x12\n" +
	"\x04time\x18\x03 \x02(\rR\x04time\x12\x10\n" +
	"\x03cmd\x18\x04 \x02(\rR\x03cmdB\fZ\n" +
	"./protobuf"

var (
	file_PB_VISITOR_proto_rawDescOnce sync.Once
	file_PB_VISITOR_proto_rawDescData []byte
)

func file_PB_VISITOR_proto_rawDescGZIP() []byte {
	file_PB_VISITOR_proto_rawDescOnce.Do(func() {
		file_PB_VISITOR_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_VISITOR_proto_rawDesc), len(file_PB_VISITOR_proto_rawDesc)))
	})
	return file_PB_VISITOR_proto_rawDescData
}

var file_PB_VISITOR_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PB_VISITOR_proto_goTypes = []any{
	(*PB_VISITOR)(nil), // 0: belfast.PB_VISITOR
}
var file_PB_VISITOR_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PB_VISITOR_proto_init() }
func file_PB_VISITOR_proto_init() {
	if File_PB_VISITOR_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_VISITOR_proto_rawDesc), len(file_PB_VISITOR_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PB_VISITOR_proto_goTypes,
		DependencyIndexes: file_PB_VISITOR_proto_depIdxs,
		MessageInfos:      file_PB_VISITOR_proto_msgTypes,
	}.Build()
	File_PB_VISITOR_proto = out.File
	file_PB_VISITOR_proto_goTypes = nil
	file_PB_VISITOR_proto_depIdxs = nil
}
