// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PT_SHIP_LOVE_LETTER.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PT_SHIP_LOVE_LETTER struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       *uint32                `protobuf:"varint,1,req,name=group_id,json=groupId" json:"group_id,omitempty"`
	LetterIdList  []uint32               `protobuf:"varint,2,rep,name=letter_id_list,json=letterIdList" json:"letter_id_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PT_SHIP_LOVE_LETTER) Reset() {
	*x = PT_SHIP_LOVE_LETTER{}
	mi := &file_PT_SHIP_LOVE_LETTER_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PT_SHIP_LOVE_LETTER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PT_SHIP_LOVE_LETTER) ProtoMessage() {}

func (x *PT_SHIP_LOVE_LETTER) ProtoReflect() protoreflect.Message {
	mi := &file_PT_SHIP_LOVE_LETTER_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PT_SHIP_LOVE_LETTER.ProtoReflect.Descriptor instead.
func (*PT_SHIP_LOVE_LETTER) Descriptor() ([]byte, []int) {
	return file_PT_SHIP_LOVE_LETTER_proto_rawDescGZIP(), []int{0}
}

func (x *PT_SHIP_LOVE_LETTER) GetGroupId() uint32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *PT_SHIP_LOVE_LETTER) GetLetterIdList() []uint32 {
	if x != nil {
		return x.LetterIdList
	}
	return nil
}

var File_PT_SHIP_LOVE_LETTER_proto protoreflect.FileDescriptor

const file_PT_SHIP_LOVE_LETTER_proto_rawDesc = "" +
	"\n" +
	"\x19PT_SHIP_LOVE_LETTER.proto\x12\abelfast\"V\n" +
	"\x13PT_SHIP_LOVE_LETTER\x12\x19\n" +
	"\bgroup_id\x18\x01 \x02(\rR\agroupId\x12$\n" +
	"\x0eletter_id_list\x18\x02 \x03(\rR\fletterIdListB\fZ\n" +
	"./protobuf"

var (
	file_PT_SHIP_LOVE_LETTER_proto_rawDescOnce sync.Once
	file_PT_SHIP_LOVE_LETTER_proto_rawDescData []byte
)

func file_PT_SHIP_LOVE_LETTER_proto_rawDescGZIP() []byte {
	file_PT_SHIP_LOVE_LETTER_proto_rawDescOnce.Do(func() {
		file_PT_SHIP_LOVE_LETTER_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PT_SHIP_LOVE_LETTER_proto_rawDesc), len(file_PT_SHIP_LOVE_LETTER_proto_rawDesc)))
	})
	return file_PT_SHIP_LOVE_LETTER_proto_rawDescData
}

var file_PT_SHIP_LOVE_LETTER_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PT_SHIP_LOVE_LETTER_proto_goTypes = []any{
	(*PT_SHIP_LOVE_LETTER)(nil), // 0: belfast.PT_SHIP_LOVE_LETTER
}
var file_PT_SHIP_LOVE_LETTER_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PT_SHIP_LOVE_LETTER_proto_init() }
func file_PT_SHIP_LOVE_LETTER_proto_init() {
	if File_PT_SHIP_LOVE_LETTER_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PT_SHIP_LOVE_LETTER_proto_rawDesc), len(file_PT_SHIP_LOVE_LETTER_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PT_SHIP_LOVE_LETTER_proto_goTypes,
		DependencyIndexes: file_PT_SHIP_LOVE_LETTER_proto_depIdxs,
		MessageInfos:      file_PT_SHIP_LOVE_LETTER_proto_msgTypes,
	}.Build()
	File_PT_SHIP_LOVE_LETTER_proto = out.File
	file_PT_SHIP_LOVE_LETTER_proto_goTypes = nil
	file_PT_SHIP_LOVE_LETTER_proto_depIdxs = nil
}
