// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: REMAPCOUNT.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type REMAPCOUNT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChapterId     *uint32                `protobuf:"varint,1,req,name=chapter_id,json=chapterId" json:"chapter_id,omitempty"`
	Pos           *uint32                `protobuf:"varint,2,req,name=pos" json:"pos,omitempty"`
	Count         *uint32                `protobuf:"varint,3,req,name=count" json:"count,omitempty"`
	Flag          *uint32                `protobuf:"varint,4,req,name=flag" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *REMAPCOUNT) Reset() {
	*x = REMAPCOUNT{}
	mi := &file_REMAPCOUNT_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *REMAPCOUNT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*REMAPCOUNT) ProtoMessage() {}

func (x *REMAPCOUNT) ProtoReflect() protoreflect.Message {
	mi := &file_REMAPCOUNT_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use REMAPCOUNT.ProtoReflect.Descriptor instead.
func (*REMAPCOUNT) Descriptor() ([]byte, []int) {
	return file_REMAPCOUNT_proto_rawDescGZIP(), []int{0}
}

func (x *REMAPCOUNT) GetChapterId() uint32 {
	if x != nil && x.ChapterId != nil {
		return *x.ChapterId
	}
	return 0
}

func (x *REMAPCOUNT) GetPos() uint32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

func (x *REMAPCOUNT) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *REMAPCOUNT) GetFlag() uint32 {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return 0
}

var File_REMAPCOUNT_proto protoreflect.FileDescriptor

const file_REMAPCOUNT_proto_rawDesc = "" +
	"\n" +
	"\x10REMAPCOUNT.proto\x12\abelfast\"g\n" +
	"\n" +
	"REMAPCOUNT\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x01 \x02(\rR\tchapterId\x12\x10\n" +
	"\x03pos\x18\x02 \x02(\rR\x03pos\x12\x14\n" +
	"\x05count\x18\x03 \x02(\rR\x05count\x12\x12\n" +
	"\x04flag\x18\x04 \x02(\rR\x04flagB\fZ\n" +
	"./protobuf"

var (
	file_REMAPCOUNT_proto_rawDescOnce sync.Once
	file_REMAPCOUNT_proto_rawDescData []byte
)

func file_REMAPCOUNT_proto_rawDescGZIP() []byte {
	file_REMAPCOUNT_proto_rawDescOnce.Do(func() {
		file_REMAPCOUNT_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_REMAPCOUNT_proto_rawDesc), len(file_REMAPCOUNT_proto_rawDesc)))
	})
	return file_REMAPCOUNT_proto_rawDescData
}

var file_REMAPCOUNT_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_REMAPCOUNT_proto_goTypes = []any{
	(*REMAPCOUNT)(nil), // 0: belfast.REMAPCOUNT
}
var file_REMAPCOUNT_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_REMAPCOUNT_proto_init() }
func file_REMAPCOUNT_proto_init() {
	if File_REMAPCOUNT_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_REMAPCOUNT_proto_rawDesc), len(file_REMAPCOUNT_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_REMAPCOUNT_proto_goTypes,
		DependencyIndexes: file_REMAPCOUNT_proto_depIdxs,
		MessageInfos:      file_REMAPCOUNT_proto_msgTypes,
	}.Build()
	File_REMAPCOUNT_proto = out.File
	file_REMAPCOUNT_proto_goTypes = nil
	file_REMAPCOUNT_proto_depIdxs = nil
}
