// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: REPORT.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type REPORT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	EventId       *uint32                `protobuf:"varint,2,req,name=event_id,json=eventId" json:"event_id,omitempty"`
	EventType     *uint32                `protobuf:"varint,3,req,name=event_type,json=eventType" json:"event_type,omitempty"`
	Score         *uint32                `protobuf:"varint,4,req,name=score" json:"score,omitempty"`
	Nodes         []*REPORT_NODE         `protobuf:"bytes,5,rep,name=nodes" json:"nodes,omitempty"`
	Status        *uint32                `protobuf:"varint,6,req,name=status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *REPORT) Reset() {
	*x = REPORT{}
	mi := &file_REPORT_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *REPORT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*REPORT) ProtoMessage() {}

func (x *REPORT) ProtoReflect() protoreflect.Message {
	mi := &file_REPORT_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use REPORT.ProtoReflect.Descriptor instead.
func (*REPORT) Descriptor() ([]byte, []int) {
	return file_REPORT_proto_rawDescGZIP(), []int{0}
}

func (x *REPORT) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *REPORT) GetEventId() uint32 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

func (x *REPORT) GetEventType() uint32 {
	if x != nil && x.EventType != nil {
		return *x.EventType
	}
	return 0
}

func (x *REPORT) GetScore() uint32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *REPORT) GetNodes() []*REPORT_NODE {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *REPORT) GetStatus() uint32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

var File_REPORT_proto protoreflect.FileDescriptor

const file_REPORT_proto_rawDesc = "" +
	"\n" +
	"\fREPORT.proto\x12\abelfast\x1a\x11REPORT_NODE.proto\"\xac\x01\n" +
	"\x06REPORT\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x02(\rR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x02(\rR\teventType\x12\x14\n" +
	"\x05score\x18\x04 \x02(\rR\x05score\x12*\n" +
	"\x05nodes\x18\x05 \x03(\v2\x14.belfast.REPORT_NODER\x05nodes\x12\x16\n" +
	"\x06status\x18\x06 \x02(\rR\x06statusB\fZ\n" +
	"./protobuf"

var (
	file_REPORT_proto_rawDescOnce sync.Once
	file_REPORT_proto_rawDescData []byte
)

func file_REPORT_proto_rawDescGZIP() []byte {
	file_REPORT_proto_rawDescOnce.Do(func() {
		file_REPORT_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_REPORT_proto_rawDesc), len(file_REPORT_proto_rawDesc)))
	})
	return file_REPORT_proto_rawDescData
}

var file_REPORT_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_REPORT_proto_goTypes = []any{
	(*REPORT)(nil),      // 0: belfast.REPORT
	(*REPORT_NODE)(nil), // 1: belfast.REPORT_NODE
}
var file_REPORT_proto_depIdxs = []int32{
	1, // 0: belfast.REPORT.nodes:type_name -> belfast.REPORT_NODE
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_REPORT_proto_init() }
func file_REPORT_proto_init() {
	if File_REPORT_proto != nil {
		return
	}
	file_REPORT_NODE_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_REPORT_proto_rawDesc), len(file_REPORT_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_REPORT_proto_goTypes,
		DependencyIndexes: file_REPORT_proto_depIdxs,
		MessageInfos:      file_REPORT_proto_msgTypes,
	}.Build()
	File_REPORT_proto = out.File
	file_REPORT_proto_goTypes = nil
	file_REPORT_proto_depIdxs = nil
}
