// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_19001.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_19001 struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Lv                   *uint32                `protobuf:"varint,1,req,name=lv" json:"lv,omitempty"`
	Food                 *uint32                `protobuf:"varint,2,req,name=food" json:"food,omitempty"`
	FoodMaxIncrease      *uint32                `protobuf:"varint,3,req,name=food_max_increase,json=foodMaxIncrease" json:"food_max_increase,omitempty"`
	FoodMaxIncreaseCount *uint32                `protobuf:"varint,4,req,name=food_max_increase_count,json=foodMaxIncreaseCount" json:"food_max_increase_count,omitempty"`
	ShipIdList           []uint32               `protobuf:"varint,5,rep,name=ship_id_list,json=shipIdList" json:"ship_id_list,omitempty"`
	FurnitureIdList      []*FURNITUREINFO       `protobuf:"bytes,6,rep,name=furniture_id_list,json=furnitureIdList" json:"furniture_id_list,omitempty"`
	FloorNum             *uint32                `protobuf:"varint,7,req,name=floor_num,json=floorNum" json:"floor_num,omitempty"`
	ExpPos               *uint32                `protobuf:"varint,8,req,name=exp_pos,json=expPos" json:"exp_pos,omitempty"`
	FurniturePutList     []*FURFLOORPUTINFO     `protobuf:"bytes,9,rep,name=furniture_put_list,json=furniturePutList" json:"furniture_put_list,omitempty"`
	NextTimestamp        *uint32                `protobuf:"varint,10,req,name=next_timestamp,json=nextTimestamp" json:"next_timestamp,omitempty"`
	LoadExp              *uint32                `protobuf:"varint,11,req,name=load_exp,json=loadExp" json:"load_exp,omitempty"`
	LoadFood             *uint32                `protobuf:"varint,12,req,name=load_food,json=loadFood" json:"load_food,omitempty"`
	LoadTime             *uint32                `protobuf:"varint,13,req,name=load_time,json=loadTime" json:"load_time,omitempty"`
	Name                 *string                `protobuf:"bytes,14,req,name=name" json:"name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SC_19001) Reset() {
	*x = SC_19001{}
	mi := &file_SC_19001_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_19001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_19001) ProtoMessage() {}

func (x *SC_19001) ProtoReflect() protoreflect.Message {
	mi := &file_SC_19001_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_19001.ProtoReflect.Descriptor instead.
func (*SC_19001) Descriptor() ([]byte, []int) {
	return file_SC_19001_proto_rawDescGZIP(), []int{0}
}

func (x *SC_19001) GetLv() uint32 {
	if x != nil && x.Lv != nil {
		return *x.Lv
	}
	return 0
}

func (x *SC_19001) GetFood() uint32 {
	if x != nil && x.Food != nil {
		return *x.Food
	}
	return 0
}

func (x *SC_19001) GetFoodMaxIncrease() uint32 {
	if x != nil && x.FoodMaxIncrease != nil {
		return *x.FoodMaxIncrease
	}
	return 0
}

func (x *SC_19001) GetFoodMaxIncreaseCount() uint32 {
	if x != nil && x.FoodMaxIncreaseCount != nil {
		return *x.FoodMaxIncreaseCount
	}
	return 0
}

func (x *SC_19001) GetShipIdList() []uint32 {
	if x != nil {
		return x.ShipIdList
	}
	return nil
}

func (x *SC_19001) GetFurnitureIdList() []*FURNITUREINFO {
	if x != nil {
		return x.FurnitureIdList
	}
	return nil
}

func (x *SC_19001) GetFloorNum() uint32 {
	if x != nil && x.FloorNum != nil {
		return *x.FloorNum
	}
	return 0
}

func (x *SC_19001) GetExpPos() uint32 {
	if x != nil && x.ExpPos != nil {
		return *x.ExpPos
	}
	return 0
}

func (x *SC_19001) GetFurniturePutList() []*FURFLOORPUTINFO {
	if x != nil {
		return x.FurniturePutList
	}
	return nil
}

func (x *SC_19001) GetNextTimestamp() uint32 {
	if x != nil && x.NextTimestamp != nil {
		return *x.NextTimestamp
	}
	return 0
}

func (x *SC_19001) GetLoadExp() uint32 {
	if x != nil && x.LoadExp != nil {
		return *x.LoadExp
	}
	return 0
}

func (x *SC_19001) GetLoadFood() uint32 {
	if x != nil && x.LoadFood != nil {
		return *x.LoadFood
	}
	return 0
}

func (x *SC_19001) GetLoadTime() uint32 {
	if x != nil && x.LoadTime != nil {
		return *x.LoadTime
	}
	return 0
}

func (x *SC_19001) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_SC_19001_proto protoreflect.FileDescriptor

const file_SC_19001_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_19001.proto\x12\abelfast\x1a\x15FURFLOORPUTINFO.proto\x1a\x13FURNITUREINFO.proto\"\x85\x04\n" +
	"\bSC_19001\x12\x0e\n" +
	"\x02lv\x18\x01 \x02(\rR\x02lv\x12\x12\n" +
	"\x04food\x18\x02 \x02(\rR\x04food\x12*\n" +
	"\x11food_max_increase\x18\x03 \x02(\rR\x0ffoodMaxIncrease\x125\n" +
	"\x17food_max_increase_count\x18\x04 \x02(\rR\x14foodMaxIncreaseCount\x12 \n" +
	"\fship_id_list\x18\x05 \x03(\rR\n" +
	"shipIdList\x12B\n" +
	"\x11furniture_id_list\x18\x06 \x03(\v2\x16.belfast.FURNITUREINFOR\x0ffurnitureIdList\x12\x1b\n" +
	"\tfloor_num\x18\a \x02(\rR\bfloorNum\x12\x17\n" +
	"\aexp_pos\x18\b \x02(\rR\x06expPos\x12F\n" +
	"\x12furniture_put_list\x18\t \x03(\v2\x18.belfast.FURFLOORPUTINFOR\x10furniturePutList\x12%\n" +
	"\x0enext_timestamp\x18\n" +
	" \x02(\rR\rnextTimestamp\x12\x19\n" +
	"\bload_exp\x18\v \x02(\rR\aloadExp\x12\x1b\n" +
	"\tload_food\x18\f \x02(\rR\bloadFood\x12\x1b\n" +
	"\tload_time\x18\r \x02(\rR\bloadTime\x12\x12\n" +
	"\x04name\x18\x0e \x02(\tR\x04nameB\fZ\n" +
	"./protobuf"

var (
	file_SC_19001_proto_rawDescOnce sync.Once
	file_SC_19001_proto_rawDescData []byte
)

func file_SC_19001_proto_rawDescGZIP() []byte {
	file_SC_19001_proto_rawDescOnce.Do(func() {
		file_SC_19001_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_19001_proto_rawDesc), len(file_SC_19001_proto_rawDesc)))
	})
	return file_SC_19001_proto_rawDescData
}

var file_SC_19001_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_19001_proto_goTypes = []any{
	(*SC_19001)(nil),        // 0: belfast.SC_19001
	(*FURNITUREINFO)(nil),   // 1: belfast.FURNITUREINFO
	(*FURFLOORPUTINFO)(nil), // 2: belfast.FURFLOORPUTINFO
}
var file_SC_19001_proto_depIdxs = []int32{
	1, // 0: belfast.SC_19001.furniture_id_list:type_name -> belfast.FURNITUREINFO
	2, // 1: belfast.SC_19001.furniture_put_list:type_name -> belfast.FURFLOORPUTINFO
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_SC_19001_proto_init() }
func file_SC_19001_proto_init() {
	if File_SC_19001_proto != nil {
		return
	}
	file_FURFLOORPUTINFO_proto_init()
	file_FURNITUREINFO_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_19001_proto_rawDesc), len(file_SC_19001_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_19001_proto_goTypes,
		DependencyIndexes: file_SC_19001_proto_depIdxs,
		MessageInfos:      file_SC_19001_proto_msgTypes,
	}.Build()
	File_SC_19001_proto = out.File
	file_SC_19001_proto_goTypes = nil
	file_SC_19001_proto_depIdxs = nil
}
