// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_18204.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_18204 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *uint32                `protobuf:"varint,1,req,name=point" json:"point,omitempty"`
	Rank          *uint32                `protobuf:"varint,2,req,name=rank" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_18204) Reset() {
	*x = SC_18204{}
	mi := &file_SC_18204_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_18204) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_18204) ProtoMessage() {}

func (x *SC_18204) ProtoReflect() protoreflect.Message {
	mi := &file_SC_18204_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_18204.ProtoReflect.Descriptor instead.
func (*SC_18204) Descriptor() ([]byte, []int) {
	return file_SC_18204_proto_rawDescGZIP(), []int{0}
}

func (x *SC_18204) GetPoint() uint32 {
	if x != nil && x.Point != nil {
		return *x.Point
	}
	return 0
}

func (x *SC_18204) GetRank() uint32 {
	if x != nil && x.Rank != nil {
		return *x.Rank
	}
	return 0
}

var File_SC_18204_proto protoreflect.FileDescriptor

const file_SC_18204_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_18204.proto\x12\abelfast\"4\n" +
	"\bSC_18204\x12\x14\n" +
	"\x05point\x18\x01 \x02(\rR\x05point\x12\x12\n" +
	"\x04rank\x18\x02 \x02(\rR\x04rankB\fZ\n" +
	"./protobuf"

var (
	file_SC_18204_proto_rawDescOnce sync.Once
	file_SC_18204_proto_rawDescData []byte
)

func file_SC_18204_proto_rawDescGZIP() []byte {
	file_SC_18204_proto_rawDescOnce.Do(func() {
		file_SC_18204_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_18204_proto_rawDesc), len(file_SC_18204_proto_rawDesc)))
	})
	return file_SC_18204_proto_rawDescData
}

var file_SC_18204_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_18204_proto_goTypes = []any{
	(*SC_18204)(nil), // 0: belfast.SC_18204
}
var file_SC_18204_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SC_18204_proto_init() }
func file_SC_18204_proto_init() {
	if File_SC_18204_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_18204_proto_rawDesc), len(file_SC_18204_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_18204_proto_goTypes,
		DependencyIndexes: file_SC_18204_proto_depIdxs,
		MessageInfos:      file_SC_18204_proto_msgTypes,
	}.Build()
	File_SC_18204_proto = out.File
	file_SC_18204_proto_goTypes = nil
	file_SC_18204_proto_depIdxs = nil
}
