// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_11300.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_11300 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoticeList    []*NOTICEINFO          `protobuf:"bytes,1,rep,name=notice_list,json=noticeList" json:"notice_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_11300) Reset() {
	*x = SC_11300{}
	mi := &file_SC_11300_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_11300) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_11300) ProtoMessage() {}

func (x *SC_11300) ProtoReflect() protoreflect.Message {
	mi := &file_SC_11300_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_11300.ProtoReflect.Descriptor instead.
func (*SC_11300) Descriptor() ([]byte, []int) {
	return file_SC_11300_proto_rawDescGZIP(), []int{0}
}

func (x *SC_11300) GetNoticeList() []*NOTICEINFO {
	if x != nil {
		return x.NoticeList
	}
	return nil
}

var File_SC_11300_proto protoreflect.FileDescriptor

const file_SC_11300_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_11300.proto\x12\abelfast\x1a\x10NOTICEINFO.proto\"@\n" +
	"\bSC_11300\x124\n" +
	"\vnotice_list\x18\x01 \x03(\v2\x13.belfast.NOTICEINFOR\n" +
	"noticeListB\fZ\n" +
	"./protobuf"

var (
	file_SC_11300_proto_rawDescOnce sync.Once
	file_SC_11300_proto_rawDescData []byte
)

func file_SC_11300_proto_rawDescGZIP() []byte {
	file_SC_11300_proto_rawDescOnce.Do(func() {
		file_SC_11300_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_11300_proto_rawDesc), len(file_SC_11300_proto_rawDesc)))
	})
	return file_SC_11300_proto_rawDescData
}

var file_SC_11300_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_11300_proto_goTypes = []any{
	(*SC_11300)(nil),   // 0: belfast.SC_11300
	(*NOTICEINFO)(nil), // 1: belfast.NOTICEINFO
}
var file_SC_11300_proto_depIdxs = []int32{
	1, // 0: belfast.SC_11300.notice_list:type_name -> belfast.NOTICEINFO
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SC_11300_proto_init() }
func file_SC_11300_proto_init() {
	if File_SC_11300_proto != nil {
		return
	}
	file_NOTICEINFO_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_11300_proto_rawDesc), len(file_SC_11300_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_11300_proto_goTypes,
		DependencyIndexes: file_SC_11300_proto_depIdxs,
		MessageInfos:      file_SC_11300_proto_msgTypes,
	}.Build()
	File_SC_11300_proto = out.File
	file_SC_11300_proto_goTypes = nil
	file_SC_11300_proto_depIdxs = nil
}
