// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_15001.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_15001 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemList      []*ITEMINFO            `protobuf:"bytes,1,rep,name=item_list,json=itemList" json:"item_list,omitempty"`
	LimitList     []*ITEMINFO            `protobuf:"bytes,2,rep,name=limit_list,json=limitList" json:"limit_list,omitempty"`
	ItemMiscList  []*ITEMMISC            `protobuf:"bytes,3,rep,name=item_misc_list,json=itemMiscList" json:"item_misc_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_15001) Reset() {
	*x = SC_15001{}
	mi := &file_SC_15001_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_15001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_15001) ProtoMessage() {}

func (x *SC_15001) ProtoReflect() protoreflect.Message {
	mi := &file_SC_15001_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_15001.ProtoReflect.Descriptor instead.
func (*SC_15001) Descriptor() ([]byte, []int) {
	return file_SC_15001_proto_rawDescGZIP(), []int{0}
}

func (x *SC_15001) GetItemList() []*ITEMINFO {
	if x != nil {
		return x.ItemList
	}
	return nil
}

func (x *SC_15001) GetLimitList() []*ITEMINFO {
	if x != nil {
		return x.LimitList
	}
	return nil
}

func (x *SC_15001) GetItemMiscList() []*ITEMMISC {
	if x != nil {
		return x.ItemMiscList
	}
	return nil
}

var File_SC_15001_proto protoreflect.FileDescriptor

const file_SC_15001_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_15001.proto\x12\abelfast\x1a\x0eITEMINFO.proto\x1a\x0eITEMMISC.proto\"\xa5\x01\n" +
	"\bSC_15001\x12.\n" +
	"\titem_list\x18\x01 \x03(\v2\x11.belfast.ITEMINFOR\bitemList\x120\n" +
	"\n" +
	"limit_list\x18\x02 \x03(\v2\x11.belfast.ITEMINFOR\tlimitList\x127\n" +
	"\x0eitem_misc_list\x18\x03 \x03(\v2\x11.belfast.ITEMMISCR\fitemMiscListB\fZ\n" +
	"./protobuf"

var (
	file_SC_15001_proto_rawDescOnce sync.Once
	file_SC_15001_proto_rawDescData []byte
)

func file_SC_15001_proto_rawDescGZIP() []byte {
	file_SC_15001_proto_rawDescOnce.Do(func() {
		file_SC_15001_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_15001_proto_rawDesc), len(file_SC_15001_proto_rawDesc)))
	})
	return file_SC_15001_proto_rawDescData
}

var file_SC_15001_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_15001_proto_goTypes = []any{
	(*SC_15001)(nil), // 0: belfast.SC_15001
	(*ITEMINFO)(nil), // 1: belfast.ITEMINFO
	(*ITEMMISC)(nil), // 2: belfast.ITEMMISC
}
var file_SC_15001_proto_depIdxs = []int32{
	1, // 0: belfast.SC_15001.item_list:type_name -> belfast.ITEMINFO
	1, // 1: belfast.SC_15001.limit_list:type_name -> belfast.ITEMINFO
	2, // 2: belfast.SC_15001.item_misc_list:type_name -> belfast.ITEMMISC
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_SC_15001_proto_init() }
func file_SC_15001_proto_init() {
	if File_SC_15001_proto != nil {
		return
	}
	file_ITEMINFO_proto_init()
	file_ITEMMISC_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_15001_proto_rawDesc), len(file_SC_15001_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_15001_proto_goTypes,
		DependencyIndexes: file_SC_15001_proto_depIdxs,
		MessageInfos:      file_SC_15001_proto_msgTypes,
	}.Build()
	File_SC_15001_proto = out.File
	file_SC_15001_proto_goTypes = nil
	file_SC_15001_proto_depIdxs = nil
}
