// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_16105.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_16105 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FirstPayList    []uint32               `protobuf:"varint,1,rep,name=first_pay_list,json=firstPayList" json:"first_pay_list,omitempty"`
	PayList         []*SHOPINFO            `protobuf:"bytes,2,rep,name=pay_list,json=payList" json:"pay_list,omitempty"`
	NormalList      []*SHOPINFO            `protobuf:"bytes,3,rep,name=normal_list,json=normalList" json:"normal_list,omitempty"`
	NormalGroupList []*SHOPINFO            `protobuf:"bytes,4,rep,name=normal_group_list,json=normalGroupList" json:"normal_group_list,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SC_16105) Reset() {
	*x = SC_16105{}
	mi := &file_SC_16105_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_16105) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_16105) ProtoMessage() {}

func (x *SC_16105) ProtoReflect() protoreflect.Message {
	mi := &file_SC_16105_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_16105.ProtoReflect.Descriptor instead.
func (*SC_16105) Descriptor() ([]byte, []int) {
	return file_SC_16105_proto_rawDescGZIP(), []int{0}
}

func (x *SC_16105) GetFirstPayList() []uint32 {
	if x != nil {
		return x.FirstPayList
	}
	return nil
}

func (x *SC_16105) GetPayList() []*SHOPINFO {
	if x != nil {
		return x.PayList
	}
	return nil
}

func (x *SC_16105) GetNormalList() []*SHOPINFO {
	if x != nil {
		return x.NormalList
	}
	return nil
}

func (x *SC_16105) GetNormalGroupList() []*SHOPINFO {
	if x != nil {
		return x.NormalGroupList
	}
	return nil
}

var File_SC_16105_proto protoreflect.FileDescriptor

const file_SC_16105_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_16105.proto\x12\abelfast\x1a\x0eSHOPINFO.proto\"\xd1\x01\n" +
	"\bSC_16105\x12$\n" +
	"\x0efirst_pay_list\x18\x01 \x03(\rR\ffirstPayList\x12,\n" +
	"\bpay_list\x18\x02 \x03(\v2\x11.belfast.SHOPINFOR\apayList\x122\n" +
	"\vnormal_list\x18\x03 \x03(\v2\x11.belfast.SHOPINFOR\n" +
	"normalList\x12=\n" +
	"\x11normal_group_list\x18\x04 \x03(\v2\x11.belfast.SHOPINFOR\x0fnormalGroupListB\fZ\n" +
	"./protobuf"

var (
	file_SC_16105_proto_rawDescOnce sync.Once
	file_SC_16105_proto_rawDescData []byte
)

func file_SC_16105_proto_rawDescGZIP() []byte {
	file_SC_16105_proto_rawDescOnce.Do(func() {
		file_SC_16105_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_16105_proto_rawDesc), len(file_SC_16105_proto_rawDesc)))
	})
	return file_SC_16105_proto_rawDescData
}

var file_SC_16105_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_16105_proto_goTypes = []any{
	(*SC_16105)(nil), // 0: belfast.SC_16105
	(*SHOPINFO)(nil), // 1: belfast.SHOPINFO
}
var file_SC_16105_proto_depIdxs = []int32{
	1, // 0: belfast.SC_16105.pay_list:type_name -> belfast.SHOPINFO
	1, // 1: belfast.SC_16105.normal_list:type_name -> belfast.SHOPINFO
	1, // 2: belfast.SC_16105.normal_group_list:type_name -> belfast.SHOPINFO
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_SC_16105_proto_init() }
func file_SC_16105_proto_init() {
	if File_SC_16105_proto != nil {
		return
	}
	file_SHOPINFO_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_16105_proto_rawDesc), len(file_SC_16105_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_16105_proto_goTypes,
		DependencyIndexes: file_SC_16105_proto_depIdxs,
		MessageInfos:      file_SC_16105_proto_msgTypes,
	}.Build()
	File_SC_16105_proto = out.File
	file_SC_16105_proto_goTypes = nil
	file_SC_16105_proto_depIdxs = nil
}
