// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_21422.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_21422 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *uint32                `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	TodayEvent    *uint32                `protobuf:"varint,2,req,name=today_event,json=todayEvent" json:"today_event,omitempty"`
	TodayTrade    *uint32                `protobuf:"varint,3,req,name=today_trade,json=todayTrade" json:"today_trade,omitempty"`
	Effect        []*PB_EVENT_EFFECT     `protobuf:"bytes,4,rep,name=effect" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_21422) Reset() {
	*x = SC_21422{}
	mi := &file_SC_21422_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_21422) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_21422) ProtoMessage() {}

func (x *SC_21422) ProtoReflect() protoreflect.Message {
	mi := &file_SC_21422_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_21422.ProtoReflect.Descriptor instead.
func (*SC_21422) Descriptor() ([]byte, []int) {
	return file_SC_21422_proto_rawDescGZIP(), []int{0}
}

func (x *SC_21422) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *SC_21422) GetTodayEvent() uint32 {
	if x != nil && x.TodayEvent != nil {
		return *x.TodayEvent
	}
	return 0
}

func (x *SC_21422) GetTodayTrade() uint32 {
	if x != nil && x.TodayTrade != nil {
		return *x.TodayTrade
	}
	return 0
}

func (x *SC_21422) GetEffect() []*PB_EVENT_EFFECT {
	if x != nil {
		return x.Effect
	}
	return nil
}

var File_SC_21422_proto protoreflect.FileDescriptor

const file_SC_21422_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_21422.proto\x12\abelfast\x1a\x15PB_EVENT_EFFECT.proto\"\x92\x01\n" +
	"\bSC_21422\x12\x12\n" +
	"\x04type\x18\x01 \x02(\rR\x04type\x12\x1f\n" +
	"\vtoday_event\x18\x02 \x02(\rR\n" +
	"todayEvent\x12\x1f\n" +
	"\vtoday_trade\x18\x03 \x02(\rR\n" +
	"todayTrade\x120\n" +
	"\x06effect\x18\x04 \x03(\v2\x18.belfast.PB_EVENT_EFFECTR\x06effectB\fZ\n" +
	"./protobuf"

var (
	file_SC_21422_proto_rawDescOnce sync.Once
	file_SC_21422_proto_rawDescData []byte
)

func file_SC_21422_proto_rawDescGZIP() []byte {
	file_SC_21422_proto_rawDescOnce.Do(func() {
		file_SC_21422_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_21422_proto_rawDesc), len(file_SC_21422_proto_rawDesc)))
	})
	return file_SC_21422_proto_rawDescData
}

var file_SC_21422_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_21422_proto_goTypes = []any{
	(*SC_21422)(nil),        // 0: belfast.SC_21422
	(*PB_EVENT_EFFECT)(nil), // 1: belfast.PB_EVENT_EFFECT
}
var file_SC_21422_proto_depIdxs = []int32{
	1, // 0: belfast.SC_21422.effect:type_name -> belfast.PB_EVENT_EFFECT
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SC_21422_proto_init() }
func file_SC_21422_proto_init() {
	if File_SC_21422_proto != nil {
		return
	}
	file_PB_EVENT_EFFECT_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_21422_proto_rawDesc), len(file_SC_21422_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_21422_proto_goTypes,
		DependencyIndexes: file_SC_21422_proto_depIdxs,
		MessageInfos:      file_SC_21422_proto_msgTypes,
	}.Build()
	File_SC_21422_proto = out.File
	file_SC_21422_proto_goTypes = nil
	file_SC_21422_proto_depIdxs = nil
}
