// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_24005.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_24005 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Result           *uint32                `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	CurrentChallenge *CHALLENGEINFO         `protobuf:"bytes,2,req,name=current_challenge,json=currentChallenge" json:"current_challenge,omitempty"`
	UserChallenge    []*USERCHALLENGEINFO   `protobuf:"bytes,3,rep,name=user_challenge,json=userChallenge" json:"user_challenge,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SC_24005) Reset() {
	*x = SC_24005{}
	mi := &file_SC_24005_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_24005) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_24005) ProtoMessage() {}

func (x *SC_24005) ProtoReflect() protoreflect.Message {
	mi := &file_SC_24005_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_24005.ProtoReflect.Descriptor instead.
func (*SC_24005) Descriptor() ([]byte, []int) {
	return file_SC_24005_proto_rawDescGZIP(), []int{0}
}

func (x *SC_24005) GetResult() uint32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *SC_24005) GetCurrentChallenge() *CHALLENGEINFO {
	if x != nil {
		return x.CurrentChallenge
	}
	return nil
}

func (x *SC_24005) GetUserChallenge() []*USERCHALLENGEINFO {
	if x != nil {
		return x.UserChallenge
	}
	return nil
}

var File_SC_24005_proto protoreflect.FileDescriptor

const file_SC_24005_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_24005.proto\x12\abelfast\x1a\x13CHALLENGEINFO.proto\x1a\x17USERCHALLENGEINFO.proto\"\xaa\x01\n" +
	"\bSC_24005\x12\x16\n" +
	"\x06result\x18\x01 \x02(\rR\x06result\x12C\n" +
	"\x11current_challenge\x18\x02 \x02(\v2\x16.belfast.CHALLENGEINFOR\x10currentChallenge\x12A\n" +
	"\x0euser_challenge\x18\x03 \x03(\v2\x1a.belfast.USERCHALLENGEINFOR\ruserChallengeB\fZ\n" +
	"./protobuf"

var (
	file_SC_24005_proto_rawDescOnce sync.Once
	file_SC_24005_proto_rawDescData []byte
)

func file_SC_24005_proto_rawDescGZIP() []byte {
	file_SC_24005_proto_rawDescOnce.Do(func() {
		file_SC_24005_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_24005_proto_rawDesc), len(file_SC_24005_proto_rawDesc)))
	})
	return file_SC_24005_proto_rawDescData
}

var file_SC_24005_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_24005_proto_goTypes = []any{
	(*SC_24005)(nil),          // 0: belfast.SC_24005
	(*CHALLENGEINFO)(nil),     // 1: belfast.CHALLENGEINFO
	(*USERCHALLENGEINFO)(nil), // 2: belfast.USERCHALLENGEINFO
}
var file_SC_24005_proto_depIdxs = []int32{
	1, // 0: belfast.SC_24005.current_challenge:type_name -> belfast.CHALLENGEINFO
	2, // 1: belfast.SC_24005.user_challenge:type_name -> belfast.USERCHALLENGEINFO
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_SC_24005_proto_init() }
func file_SC_24005_proto_init() {
	if File_SC_24005_proto != nil {
		return
	}
	file_CHALLENGEINFO_proto_init()
	file_USERCHALLENGEINFO_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_24005_proto_rawDesc), len(file_SC_24005_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_24005_proto_goTypes,
		DependencyIndexes: file_SC_24005_proto_depIdxs,
		MessageInfos:      file_SC_24005_proto_msgTypes,
	}.Build()
	File_SC_24005_proto = out.File
	file_SC_24005_proto_goTypes = nil
	file_SC_24005_proto_depIdxs = nil
}
