// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_21040.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_21040 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskList      []*PB_TASK             `protobuf:"bytes,1,rep,name=task_list,json=taskList" json:"task_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_21040) Reset() {
	*x = SC_21040{}
	mi := &file_SC_21040_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_21040) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_21040) ProtoMessage() {}

func (x *SC_21040) ProtoReflect() protoreflect.Message {
	mi := &file_SC_21040_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_21040.ProtoReflect.Descriptor instead.
func (*SC_21040) Descriptor() ([]byte, []int) {
	return file_SC_21040_proto_rawDescGZIP(), []int{0}
}

func (x *SC_21040) GetTaskList() []*PB_TASK {
	if x != nil {
		return x.TaskList
	}
	return nil
}

var File_SC_21040_proto protoreflect.FileDescriptor

const file_SC_21040_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_21040.proto\x12\abelfast\x1a\rPB_TASK.proto\"9\n" +
	"\bSC_21040\x12-\n" +
	"\ttask_list\x18\x01 \x03(\v2\x10.belfast.PB_TASKR\btaskListB\fZ\n" +
	"./protobuf"

var (
	file_SC_21040_proto_rawDescOnce sync.Once
	file_SC_21040_proto_rawDescData []byte
)

func file_SC_21040_proto_rawDescGZIP() []byte {
	file_SC_21040_proto_rawDescOnce.Do(func() {
		file_SC_21040_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_21040_proto_rawDesc), len(file_SC_21040_proto_rawDesc)))
	})
	return file_SC_21040_proto_rawDescData
}

var file_SC_21040_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_21040_proto_goTypes = []any{
	(*SC_21040)(nil), // 0: belfast.SC_21040
	(*PB_TASK)(nil),  // 1: belfast.PB_TASK
}
var file_SC_21040_proto_depIdxs = []int32{
	1, // 0: belfast.SC_21040.task_list:type_name -> belfast.PB_TASK
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SC_21040_proto_init() }
func file_SC_21040_proto_init() {
	if File_SC_21040_proto != nil {
		return
	}
	file_PB_TASK_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_21040_proto_rawDesc), len(file_SC_21040_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_21040_proto_goTypes,
		DependencyIndexes: file_SC_21040_proto_depIdxs,
		MessageInfos:      file_SC_21040_proto_msgTypes,
	}.Build()
	File_SC_21040_proto = out.File
	file_SC_21040_proto_goTypes = nil
	file_SC_21040_proto_depIdxs = nil
}
