// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_26052.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_26052 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *uint32                `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	Items         []*KVDATA              `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	Recipes       []*KVDATA              `protobuf:"bytes,3,rep,name=recipes" json:"recipes,omitempty"`
	Slots         []*BUFF_SLOT           `protobuf:"bytes,4,rep,name=slots" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_26052) Reset() {
	*x = SC_26052{}
	mi := &file_SC_26052_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_26052) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_26052) ProtoMessage() {}

func (x *SC_26052) ProtoReflect() protoreflect.Message {
	mi := &file_SC_26052_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_26052.ProtoReflect.Descriptor instead.
func (*SC_26052) Descriptor() ([]byte, []int) {
	return file_SC_26052_proto_rawDescGZIP(), []int{0}
}

func (x *SC_26052) GetResult() uint32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *SC_26052) GetItems() []*KVDATA {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SC_26052) GetRecipes() []*KVDATA {
	if x != nil {
		return x.Recipes
	}
	return nil
}

func (x *SC_26052) GetSlots() []*BUFF_SLOT {
	if x != nil {
		return x.Slots
	}
	return nil
}

var File_SC_26052_proto protoreflect.FileDescriptor

const file_SC_26052_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_26052.proto\x12\abelfast\x1a\x0fBUFF_SLOT.proto\x1a\fKVDATA.proto\"\x9e\x01\n" +
	"\bSC_26052\x12\x16\n" +
	"\x06result\x18\x01 \x02(\rR\x06result\x12%\n" +
	"\x05items\x18\x02 \x03(\v2\x0f.belfast.KVDATAR\x05items\x12)\n" +
	"\arecipes\x18\x03 \x03(\v2\x0f.belfast.KVDATAR\arecipes\x12(\n" +
	"\x05slots\x18\x04 \x03(\v2\x12.belfast.BUFF_SLOTR\x05slotsB\fZ\n" +
	"./protobuf"

var (
	file_SC_26052_proto_rawDescOnce sync.Once
	file_SC_26052_proto_rawDescData []byte
)

func file_SC_26052_proto_rawDescGZIP() []byte {
	file_SC_26052_proto_rawDescOnce.Do(func() {
		file_SC_26052_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_26052_proto_rawDesc), len(file_SC_26052_proto_rawDesc)))
	})
	return file_SC_26052_proto_rawDescData
}

var file_SC_26052_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_26052_proto_goTypes = []any{
	(*SC_26052)(nil),  // 0: belfast.SC_26052
	(*KVDATA)(nil),    // 1: belfast.KVDATA
	(*BUFF_SLOT)(nil), // 2: belfast.BUFF_SLOT
}
var file_SC_26052_proto_depIdxs = []int32{
	1, // 0: belfast.SC_26052.items:type_name -> belfast.KVDATA
	1, // 1: belfast.SC_26052.recipes:type_name -> belfast.KVDATA
	2, // 2: belfast.SC_26052.slots:type_name -> belfast.BUFF_SLOT
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_SC_26052_proto_init() }
func file_SC_26052_proto_init() {
	if File_SC_26052_proto != nil {
		return
	}
	file_BUFF_SLOT_proto_init()
	file_KVDATA_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_26052_proto_rawDesc), len(file_SC_26052_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_26052_proto_goTypes,
		DependencyIndexes: file_SC_26052_proto_depIdxs,
		MessageInfos:      file_SC_26052_proto_msgTypes,
	}.Build()
	File_SC_26052_proto = out.File
	file_SC_26052_proto_goTypes = nil
	file_SC_26052_proto_depIdxs = nil
}
