// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_21502.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_21502 struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Result        *uint32                 `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	ShipPower     *uint32                 `protobuf:"varint,2,req,name=ship_power,json=shipPower" json:"ship_power,omitempty"`
	ShipAppoint   *PB_ISLAND_SHIP_APPOINT `protobuf:"bytes,3,req,name=ship_appoint,json=shipAppoint" json:"ship_appoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_21502) Reset() {
	*x = SC_21502{}
	mi := &file_SC_21502_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_21502) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_21502) ProtoMessage() {}

func (x *SC_21502) ProtoReflect() protoreflect.Message {
	mi := &file_SC_21502_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_21502.ProtoReflect.Descriptor instead.
func (*SC_21502) Descriptor() ([]byte, []int) {
	return file_SC_21502_proto_rawDescGZIP(), []int{0}
}

func (x *SC_21502) GetResult() uint32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *SC_21502) GetShipPower() uint32 {
	if x != nil && x.ShipPower != nil {
		return *x.ShipPower
	}
	return 0
}

func (x *SC_21502) GetShipAppoint() *PB_ISLAND_SHIP_APPOINT {
	if x != nil {
		return x.ShipAppoint
	}
	return nil
}

var File_SC_21502_proto protoreflect.FileDescriptor

const file_SC_21502_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_21502.proto\x12\abelfast\x1a\x1cPB_ISLAND_SHIP_APPOINT.proto\"\x85\x01\n" +
	"\bSC_21502\x12\x16\n" +
	"\x06result\x18\x01 \x02(\rR\x06result\x12\x1d\n" +
	"\n" +
	"ship_power\x18\x02 \x02(\rR\tshipPower\x12B\n" +
	"\fship_appoint\x18\x03 \x02(\v2\x1f.belfast.PB_ISLAND_SHIP_APPOINTR\vshipAppointB\fZ\n" +
	"./protobuf"

var (
	file_SC_21502_proto_rawDescOnce sync.Once
	file_SC_21502_proto_rawDescData []byte
)

func file_SC_21502_proto_rawDescGZIP() []byte {
	file_SC_21502_proto_rawDescOnce.Do(func() {
		file_SC_21502_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_21502_proto_rawDesc), len(file_SC_21502_proto_rawDesc)))
	})
	return file_SC_21502_proto_rawDescData
}

var file_SC_21502_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_21502_proto_goTypes = []any{
	(*SC_21502)(nil),               // 0: belfast.SC_21502
	(*PB_ISLAND_SHIP_APPOINT)(nil), // 1: belfast.PB_ISLAND_SHIP_APPOINT
}
var file_SC_21502_proto_depIdxs = []int32{
	1, // 0: belfast.SC_21502.ship_appoint:type_name -> belfast.PB_ISLAND_SHIP_APPOINT
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SC_21502_proto_init() }
func file_SC_21502_proto_init() {
	if File_SC_21502_proto != nil {
		return
	}
	file_PB_ISLAND_SHIP_APPOINT_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_21502_proto_rawDesc), len(file_SC_21502_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_21502_proto_goTypes,
		DependencyIndexes: file_SC_21502_proto_depIdxs,
		MessageInfos:      file_SC_21502_proto_msgTypes,
	}.Build()
	File_SC_21502_proto = out.File
	file_SC_21502_proto_goTypes = nil
	file_SC_21502_proto_depIdxs = nil
}
