// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_30001.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_30001 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadNumber  *uint32                `protobuf:"varint,1,req,name=unread_number,json=unreadNumber" json:"unread_number,omitempty"`
	TotalNumber   *uint32                `protobuf:"varint,2,req,name=total_number,json=totalNumber" json:"total_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_30001) Reset() {
	*x = SC_30001{}
	mi := &file_SC_30001_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_30001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_30001) ProtoMessage() {}

func (x *SC_30001) ProtoReflect() protoreflect.Message {
	mi := &file_SC_30001_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_30001.ProtoReflect.Descriptor instead.
func (*SC_30001) Descriptor() ([]byte, []int) {
	return file_SC_30001_proto_rawDescGZIP(), []int{0}
}

func (x *SC_30001) GetUnreadNumber() uint32 {
	if x != nil && x.UnreadNumber != nil {
		return *x.UnreadNumber
	}
	return 0
}

func (x *SC_30001) GetTotalNumber() uint32 {
	if x != nil && x.TotalNumber != nil {
		return *x.TotalNumber
	}
	return 0
}

var File_SC_30001_proto protoreflect.FileDescriptor

const file_SC_30001_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_30001.proto\x12\abelfast\"R\n" +
	"\bSC_30001\x12#\n" +
	"\runread_number\x18\x01 \x02(\rR\funreadNumber\x12!\n" +
	"\ftotal_number\x18\x02 \x02(\rR\vtotalNumberB\fZ\n" +
	"./protobuf"

var (
	file_SC_30001_proto_rawDescOnce sync.Once
	file_SC_30001_proto_rawDescData []byte
)

func file_SC_30001_proto_rawDescGZIP() []byte {
	file_SC_30001_proto_rawDescOnce.Do(func() {
		file_SC_30001_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_30001_proto_rawDesc), len(file_SC_30001_proto_rawDesc)))
	})
	return file_SC_30001_proto_rawDescData
}

var file_SC_30001_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_30001_proto_goTypes = []any{
	(*SC_30001)(nil), // 0: belfast.SC_30001
}
var file_SC_30001_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SC_30001_proto_init() }
func file_SC_30001_proto_init() {
	if File_SC_30001_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_30001_proto_rawDesc), len(file_SC_30001_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_30001_proto_goTypes,
		DependencyIndexes: file_SC_30001_proto_depIdxs,
		MessageInfos:      file_SC_30001_proto_msgTypes,
	}.Build()
	File_SC_30001_proto = out.File
	file_SC_30001_proto_goTypes = nil
	file_SC_30001_proto_depIdxs = nil
}
