// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_30105.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_30105 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *uint32                `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	DropList      []*DROPINFO            `protobuf:"bytes,2,rep,name=drop_list,json=dropList" json:"drop_list,omitempty"`
	Number        *uint32                `protobuf:"varint,3,req,name=number" json:"number,omitempty"`
	MaxTimestamp  *uint32                `protobuf:"varint,4,req,name=max_timestamp,json=maxTimestamp" json:"max_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_30105) Reset() {
	*x = SC_30105{}
	mi := &file_SC_30105_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_30105) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_30105) ProtoMessage() {}

func (x *SC_30105) ProtoReflect() protoreflect.Message {
	mi := &file_SC_30105_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_30105.ProtoReflect.Descriptor instead.
func (*SC_30105) Descriptor() ([]byte, []int) {
	return file_SC_30105_proto_rawDescGZIP(), []int{0}
}

func (x *SC_30105) GetResult() uint32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *SC_30105) GetDropList() []*DROPINFO {
	if x != nil {
		return x.DropList
	}
	return nil
}

func (x *SC_30105) GetNumber() uint32 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

func (x *SC_30105) GetMaxTimestamp() uint32 {
	if x != nil && x.MaxTimestamp != nil {
		return *x.MaxTimestamp
	}
	return 0
}

var File_SC_30105_proto protoreflect.FileDescriptor

const file_SC_30105_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_30105.proto\x12\abelfast\x1a\x0eDROPINFO.proto\"\x8f\x01\n" +
	"\bSC_30105\x12\x16\n" +
	"\x06result\x18\x01 \x02(\rR\x06result\x12.\n" +
	"\tdrop_list\x18\x02 \x03(\v2\x11.belfast.DROPINFOR\bdropList\x12\x16\n" +
	"\x06number\x18\x03 \x02(\rR\x06number\x12#\n" +
	"\rmax_timestamp\x18\x04 \x02(\rR\fmaxTimestampB\fZ\n" +
	"./protobuf"

var (
	file_SC_30105_proto_rawDescOnce sync.Once
	file_SC_30105_proto_rawDescData []byte
)

func file_SC_30105_proto_rawDescGZIP() []byte {
	file_SC_30105_proto_rawDescOnce.Do(func() {
		file_SC_30105_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_30105_proto_rawDesc), len(file_SC_30105_proto_rawDesc)))
	})
	return file_SC_30105_proto_rawDescData
}

var file_SC_30105_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_30105_proto_goTypes = []any{
	(*SC_30105)(nil), // 0: belfast.SC_30105
	(*DROPINFO)(nil), // 1: belfast.DROPINFO
}
var file_SC_30105_proto_depIdxs = []int32{
	1, // 0: belfast.SC_30105.drop_list:type_name -> belfast.DROPINFO
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SC_30105_proto_init() }
func file_SC_30105_proto_init() {
	if File_SC_30105_proto != nil {
		return
	}
	file_DROPINFO_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_30105_proto_rawDesc), len(file_SC_30105_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_30105_proto_goTypes,
		DependencyIndexes: file_SC_30105_proto_depIdxs,
		MessageInfos:      file_SC_30105_proto_msgTypes,
	}.Build()
	File_SC_30105_proto = out.File
	file_SC_30105_proto_goTypes = nil
	file_SC_30105_proto_depIdxs = nil
}
