// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_40009.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_40009 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Re40004       []*SC_40004            `protobuf:"bytes,1,rep,name=re40004" json:"re40004,omitempty"`
	System        *uint32                `protobuf:"varint,2,req,name=system" json:"system,omitempty"`
	Arg1          *uint32                `protobuf:"varint,3,opt,name=arg1" json:"arg1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_40009) Reset() {
	*x = SC_40009{}
	mi := &file_SC_40009_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_40009) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_40009) ProtoMessage() {}

func (x *SC_40009) ProtoReflect() protoreflect.Message {
	mi := &file_SC_40009_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_40009.ProtoReflect.Descriptor instead.
func (*SC_40009) Descriptor() ([]byte, []int) {
	return file_SC_40009_proto_rawDescGZIP(), []int{0}
}

func (x *SC_40009) GetRe40004() []*SC_40004 {
	if x != nil {
		return x.Re40004
	}
	return nil
}

func (x *SC_40009) GetSystem() uint32 {
	if x != nil && x.System != nil {
		return *x.System
	}
	return 0
}

func (x *SC_40009) GetArg1() uint32 {
	if x != nil && x.Arg1 != nil {
		return *x.Arg1
	}
	return 0
}

var File_SC_40009_proto protoreflect.FileDescriptor

const file_SC_40009_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_40009.proto\x12\abelfast\x1a\x0eSC_40004.proto\"c\n" +
	"\bSC_40009\x12+\n" +
	"\are40004\x18\x01 \x03(\v2\x11.belfast.SC_40004R\are40004\x12\x16\n" +
	"\x06system\x18\x02 \x02(\rR\x06system\x12\x12\n" +
	"\x04arg1\x18\x03 \x01(\rR\x04arg1B\fZ\n" +
	"./protobuf"

var (
	file_SC_40009_proto_rawDescOnce sync.Once
	file_SC_40009_proto_rawDescData []byte
)

func file_SC_40009_proto_rawDescGZIP() []byte {
	file_SC_40009_proto_rawDescOnce.Do(func() {
		file_SC_40009_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_40009_proto_rawDesc), len(file_SC_40009_proto_rawDesc)))
	})
	return file_SC_40009_proto_rawDescData
}

var file_SC_40009_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_40009_proto_goTypes = []any{
	(*SC_40009)(nil), // 0: belfast.SC_40009
	(*SC_40004)(nil), // 1: belfast.SC_40004
}
var file_SC_40009_proto_depIdxs = []int32{
	1, // 0: belfast.SC_40009.re40004:type_name -> belfast.SC_40004
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SC_40009_proto_init() }
func file_SC_40009_proto_init() {
	if File_SC_40009_proto != nil {
		return
	}
	file_SC_40004_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_40009_proto_rawDesc), len(file_SC_40009_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_40009_proto_goTypes,
		DependencyIndexes: file_SC_40009_proto_depIdxs,
		MessageInfos:      file_SC_40009_proto_msgTypes,
	}.Build()
	File_SC_40009_proto = out.File
	file_SC_40009_proto_goTypes = nil
	file_SC_40009_proto_depIdxs = nil
}
