// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_64000.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_64000 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TechList      []*FLEETTECH           `protobuf:"bytes,1,rep,name=tech_list,json=techList" json:"tech_list,omitempty"`
	TechsetList   []*TECHSET             `protobuf:"bytes,2,rep,name=techset_list,json=techsetList" json:"techset_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_64000) Reset() {
	*x = SC_64000{}
	mi := &file_SC_64000_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_64000) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_64000) ProtoMessage() {}

func (x *SC_64000) ProtoReflect() protoreflect.Message {
	mi := &file_SC_64000_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_64000.ProtoReflect.Descriptor instead.
func (*SC_64000) Descriptor() ([]byte, []int) {
	return file_SC_64000_proto_rawDescGZIP(), []int{0}
}

func (x *SC_64000) GetTechList() []*FLEETTECH {
	if x != nil {
		return x.TechList
	}
	return nil
}

func (x *SC_64000) GetTechsetList() []*TECHSET {
	if x != nil {
		return x.TechsetList
	}
	return nil
}

var File_SC_64000_proto protoreflect.FileDescriptor

const file_SC_64000_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_64000.proto\x12\abelfast\x1a\x0fFLEETTECH.proto\x1a\rTECHSET.proto\"p\n" +
	"\bSC_64000\x12/\n" +
	"\ttech_list\x18\x01 \x03(\v2\x12.belfast.FLEETTECHR\btechList\x123\n" +
	"\ftechset_list\x18\x02 \x03(\v2\x10.belfast.TECHSETR\vtechsetListB\fZ\n" +
	"./protobuf"

var (
	file_SC_64000_proto_rawDescOnce sync.Once
	file_SC_64000_proto_rawDescData []byte
)

func file_SC_64000_proto_rawDescGZIP() []byte {
	file_SC_64000_proto_rawDescOnce.Do(func() {
		file_SC_64000_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_64000_proto_rawDesc), len(file_SC_64000_proto_rawDesc)))
	})
	return file_SC_64000_proto_rawDescData
}

var file_SC_64000_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_64000_proto_goTypes = []any{
	(*SC_64000)(nil),  // 0: belfast.SC_64000
	(*FLEETTECH)(nil), // 1: belfast.FLEETTECH
	(*TECHSET)(nil),   // 2: belfast.TECHSET
}
var file_SC_64000_proto_depIdxs = []int32{
	1, // 0: belfast.SC_64000.tech_list:type_name -> belfast.FLEETTECH
	2, // 1: belfast.SC_64000.techset_list:type_name -> belfast.TECHSET
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_SC_64000_proto_init() }
func file_SC_64000_proto_init() {
	if File_SC_64000_proto != nil {
		return
	}
	file_FLEETTECH_proto_init()
	file_TECHSET_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_64000_proto_rawDesc), len(file_SC_64000_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_64000_proto_goTypes,
		DependencyIndexes: file_SC_64000_proto_depIdxs,
		MessageInfos:      file_SC_64000_proto_msgTypes,
	}.Build()
	File_SC_64000_proto = out.File
	file_SC_64000_proto_goTypes = nil
	file_SC_64000_proto_depIdxs = nil
}
