// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: SHIPID_POS_INFO.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SHIPID_POS_INFO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos      *uint32   `protobuf:"varint,1,req,name=pos" json:"pos,omitempty"`
	Ship     *SHIPINFO `protobuf:"bytes,2,req,name=ship" json:"ship,omitempty"`
	LastTime *uint32   `protobuf:"varint,3,req,name=last_time,json=lastTime" json:"last_time,omitempty"`
}

func (x *SHIPID_POS_INFO) Reset() {
	*x = SHIPID_POS_INFO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SHIPID_POS_INFO_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SHIPID_POS_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SHIPID_POS_INFO) ProtoMessage() {}

func (x *SHIPID_POS_INFO) ProtoReflect() protoreflect.Message {
	mi := &file_SHIPID_POS_INFO_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SHIPID_POS_INFO.ProtoReflect.Descriptor instead.
func (*SHIPID_POS_INFO) Descriptor() ([]byte, []int) {
	return file_SHIPID_POS_INFO_proto_rawDescGZIP(), []int{0}
}

func (x *SHIPID_POS_INFO) GetPos() uint32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

func (x *SHIPID_POS_INFO) GetShip() *SHIPINFO {
	if x != nil {
		return x.Ship
	}
	return nil
}

func (x *SHIPID_POS_INFO) GetLastTime() uint32 {
	if x != nil && x.LastTime != nil {
		return *x.LastTime
	}
	return 0
}

var File_SHIPID_POS_INFO_proto protoreflect.FileDescriptor

var file_SHIPID_POS_INFO_proto_rawDesc = []byte{
	0x0a, 0x15, 0x53, 0x48, 0x49, 0x50, 0x49, 0x44, 0x5f, 0x50, 0x4f, 0x53, 0x5f, 0x49, 0x4e, 0x46,
	0x4f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x65, 0x6c, 0x66, 0x61, 0x73, 0x74,
	0x1a, 0x0e, 0x53, 0x48, 0x49, 0x50, 0x49, 0x4e, 0x46, 0x4f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x67, 0x0a, 0x0f, 0x53, 0x48, 0x49, 0x50, 0x49, 0x44, 0x5f, 0x50, 0x4f, 0x53, 0x5f, 0x49,
	0x4e, 0x46, 0x4f, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d,
	0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x73, 0x68, 0x69, 0x70, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x65, 0x6c, 0x66, 0x61, 0x73, 0x74, 0x2e, 0x53, 0x48,
	0x49, 0x50, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x04, 0x73, 0x68, 0x69, 0x70, 0x12, 0x1b, 0x0a, 0x09,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
}

var (
	file_SHIPID_POS_INFO_proto_rawDescOnce sync.Once
	file_SHIPID_POS_INFO_proto_rawDescData = file_SHIPID_POS_INFO_proto_rawDesc
)

func file_SHIPID_POS_INFO_proto_rawDescGZIP() []byte {
	file_SHIPID_POS_INFO_proto_rawDescOnce.Do(func() {
		file_SHIPID_POS_INFO_proto_rawDescData = protoimpl.X.CompressGZIP(file_SHIPID_POS_INFO_proto_rawDescData)
	})
	return file_SHIPID_POS_INFO_proto_rawDescData
}

var file_SHIPID_POS_INFO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SHIPID_POS_INFO_proto_goTypes = []any{
	(*SHIPID_POS_INFO)(nil), // 0: belfast.SHIPID_POS_INFO
	(*SHIPINFO)(nil),        // 1: belfast.SHIPINFO
}
var file_SHIPID_POS_INFO_proto_depIdxs = []int32{
	1, // 0: belfast.SHIPID_POS_INFO.ship:type_name -> belfast.SHIPINFO
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SHIPID_POS_INFO_proto_init() }
func file_SHIPID_POS_INFO_proto_init() {
	if File_SHIPID_POS_INFO_proto != nil {
		return
	}
	file_SHIPINFO_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SHIPID_POS_INFO_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SHIPID_POS_INFO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SHIPID_POS_INFO_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SHIPID_POS_INFO_proto_goTypes,
		DependencyIndexes: file_SHIPID_POS_INFO_proto_depIdxs,
		MessageInfos:      file_SHIPID_POS_INFO_proto_msgTypes,
	}.Build()
	File_SHIPID_POS_INFO_proto = out.File
	file_SHIPID_POS_INFO_proto_rawDesc = nil
	file_SHIPID_POS_INFO_proto_goTypes = nil
	file_SHIPID_POS_INFO_proto_depIdxs = nil
}
