// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: STRATEGYINFO_P13.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type STRATEGYINFO_P13 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Count         *uint32                `protobuf:"varint,3,req,name=count" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *STRATEGYINFO_P13) Reset() {
	*x = STRATEGYINFO_P13{}
	mi := &file_STRATEGYINFO_P13_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *STRATEGYINFO_P13) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STRATEGYINFO_P13) ProtoMessage() {}

func (x *STRATEGYINFO_P13) ProtoReflect() protoreflect.Message {
	mi := &file_STRATEGYINFO_P13_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STRATEGYINFO_P13.ProtoReflect.Descriptor instead.
func (*STRATEGYINFO_P13) Descriptor() ([]byte, []int) {
	return file_STRATEGYINFO_P13_proto_rawDescGZIP(), []int{0}
}

func (x *STRATEGYINFO_P13) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *STRATEGYINFO_P13) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

var File_STRATEGYINFO_P13_proto protoreflect.FileDescriptor

const file_STRATEGYINFO_P13_proto_rawDesc = "" +
	"\n" +
	"\x16STRATEGYINFO_P13.proto\x12\abelfast\"8\n" +
	"\x10STRATEGYINFO_P13\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x14\n" +
	"\x05count\x18\x03 \x02(\rR\x05countB\fZ\n" +
	"./protobuf"

var (
	file_STRATEGYINFO_P13_proto_rawDescOnce sync.Once
	file_STRATEGYINFO_P13_proto_rawDescData []byte
)

func file_STRATEGYINFO_P13_proto_rawDescGZIP() []byte {
	file_STRATEGYINFO_P13_proto_rawDescOnce.Do(func() {
		file_STRATEGYINFO_P13_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_STRATEGYINFO_P13_proto_rawDesc), len(file_STRATEGYINFO_P13_proto_rawDesc)))
	})
	return file_STRATEGYINFO_P13_proto_rawDescData
}

var file_STRATEGYINFO_P13_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_STRATEGYINFO_P13_proto_goTypes = []any{
	(*STRATEGYINFO_P13)(nil), // 0: belfast.STRATEGYINFO_P13
}
var file_STRATEGYINFO_P13_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_STRATEGYINFO_P13_proto_init() }
func file_STRATEGYINFO_P13_proto_init() {
	if File_STRATEGYINFO_P13_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_STRATEGYINFO_P13_proto_rawDesc), len(file_STRATEGYINFO_P13_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_STRATEGYINFO_P13_proto_goTypes,
		DependencyIndexes: file_STRATEGYINFO_P13_proto_depIdxs,
		MessageInfos:      file_STRATEGYINFO_P13_proto_msgTypes,
	}.Build()
	File_STRATEGYINFO_P13_proto = out.File
	file_STRATEGYINFO_P13_proto_goTypes = nil
	file_STRATEGYINFO_P13_proto_depIdxs = nil
}
