// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: TBBF.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TBBF struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Round         *uint32                `protobuf:"varint,2,req,name=round" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TBBF) Reset() {
	*x = TBBF{}
	mi := &file_TBBF_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TBBF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TBBF) ProtoMessage() {}

func (x *TBBF) ProtoReflect() protoreflect.Message {
	mi := &file_TBBF_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TBBF.ProtoReflect.Descriptor instead.
func (*TBBF) Descriptor() ([]byte, []int) {
	return file_TBBF_proto_rawDescGZIP(), []int{0}
}

func (x *TBBF) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TBBF) GetRound() uint32 {
	if x != nil && x.Round != nil {
		return *x.Round
	}
	return 0
}

var File_TBBF_proto protoreflect.FileDescriptor

const file_TBBF_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"TBBF.proto\x12\abelfast\",\n" +
	"\x04TBBF\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x14\n" +
	"\x05round\x18\x02 \x02(\rR\x05roundB\fZ\n" +
	"./protobuf"

var (
	file_TBBF_proto_rawDescOnce sync.Once
	file_TBBF_proto_rawDescData []byte
)

func file_TBBF_proto_rawDescGZIP() []byte {
	file_TBBF_proto_rawDescOnce.Do(func() {
		file_TBBF_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TBBF_proto_rawDesc), len(file_TBBF_proto_rawDesc)))
	})
	return file_TBBF_proto_rawDescData
}

var file_TBBF_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TBBF_proto_goTypes = []any{
	(*TBBF)(nil), // 0: belfast.TBBF
}
var file_TBBF_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TBBF_proto_init() }
func file_TBBF_proto_init() {
	if File_TBBF_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TBBF_proto_rawDesc), len(file_TBBF_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TBBF_proto_goTypes,
		DependencyIndexes: file_TBBF_proto_depIdxs,
		MessageInfos:      file_TBBF_proto_msgTypes,
	}.Build()
	File_TBBF_proto = out.File
	file_TBBF_proto_goTypes = nil
	file_TBBF_proto_depIdxs = nil
}
