// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: TBROUND.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TBROUND struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         *uint32                `protobuf:"varint,1,req,name=round" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TBROUND) Reset() {
	*x = TBROUND{}
	mi := &file_TBROUND_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TBROUND) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TBROUND) ProtoMessage() {}

func (x *TBROUND) ProtoReflect() protoreflect.Message {
	mi := &file_TBROUND_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TBROUND.ProtoReflect.Descriptor instead.
func (*TBROUND) Descriptor() ([]byte, []int) {
	return file_TBROUND_proto_rawDescGZIP(), []int{0}
}

func (x *TBROUND) GetRound() uint32 {
	if x != nil && x.Round != nil {
		return *x.Round
	}
	return 0
}

var File_TBROUND_proto protoreflect.FileDescriptor

const file_TBROUND_proto_rawDesc = "" +
	"\n" +
	"\rTBROUND.proto\x12\abelfast\"\x1f\n" +
	"\aTBROUND\x12\x14\n" +
	"\x05round\x18\x01 \x02(\rR\x05roundB\fZ\n" +
	"./protobuf"

var (
	file_TBROUND_proto_rawDescOnce sync.Once
	file_TBROUND_proto_rawDescData []byte
)

func file_TBROUND_proto_rawDescGZIP() []byte {
	file_TBROUND_proto_rawDescOnce.Do(func() {
		file_TBROUND_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TBROUND_proto_rawDesc), len(file_TBROUND_proto_rawDesc)))
	})
	return file_TBROUND_proto_rawDescData
}

var file_TBROUND_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TBROUND_proto_goTypes = []any{
	(*TBROUND)(nil), // 0: belfast.TBROUND
}
var file_TBROUND_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TBROUND_proto_init() }
func file_TBROUND_proto_init() {
	if File_TBROUND_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TBROUND_proto_rawDesc), len(file_TBROUND_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TBROUND_proto_goTypes,
		DependencyIndexes: file_TBROUND_proto_depIdxs,
		MessageInfos:      file_TBROUND_proto_msgTypes,
	}.Build()
	File_TBROUND_proto = out.File
	file_TBROUND_proto_goTypes = nil
	file_TBROUND_proto_depIdxs = nil
}
