// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: TRACK_INFO.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TRACK_INFO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackTyp      *uint32                `protobuf:"varint,1,req,name=track_typ,json=trackTyp" json:"track_typ,omitempty"`
	TrackTime     *uint32                `protobuf:"varint,2,req,name=track_time,json=trackTime" json:"track_time,omitempty"`
	IntArgs       []int32                `protobuf:"varint,3,rep,name=int_args,json=intArgs" json:"int_args,omitempty"`
	StrArgs       []string               `protobuf:"bytes,4,rep,name=str_args,json=strArgs" json:"str_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TRACK_INFO) Reset() {
	*x = TRACK_INFO{}
	mi := &file_TRACK_INFO_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TRACK_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TRACK_INFO) ProtoMessage() {}

func (x *TRACK_INFO) ProtoReflect() protoreflect.Message {
	mi := &file_TRACK_INFO_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TRACK_INFO.ProtoReflect.Descriptor instead.
func (*TRACK_INFO) Descriptor() ([]byte, []int) {
	return file_TRACK_INFO_proto_rawDescGZIP(), []int{0}
}

func (x *TRACK_INFO) GetTrackTyp() uint32 {
	if x != nil && x.TrackTyp != nil {
		return *x.TrackTyp
	}
	return 0
}

func (x *TRACK_INFO) GetTrackTime() uint32 {
	if x != nil && x.TrackTime != nil {
		return *x.TrackTime
	}
	return 0
}

func (x *TRACK_INFO) GetIntArgs() []int32 {
	if x != nil {
		return x.IntArgs
	}
	return nil
}

func (x *TRACK_INFO) GetStrArgs() []string {
	if x != nil {
		return x.StrArgs
	}
	return nil
}

var File_TRACK_INFO_proto protoreflect.FileDescriptor

const file_TRACK_INFO_proto_rawDesc = "" +
	"\n" +
	"\x10TRACK_INFO.proto\x12\abelfast\"~\n" +
	"\n" +
	"TRACK_INFO\x12\x1b\n" +
	"\ttrack_typ\x18\x01 \x02(\rR\btrackTyp\x12\x1d\n" +
	"\n" +
	"track_time\x18\x02 \x02(\rR\ttrackTime\x12\x19\n" +
	"\bint_args\x18\x03 \x03(\x05R\aintArgs\x12\x19\n" +
	"\bstr_args\x18\x04 \x03(\tR\astrArgsB\fZ\n" +
	"./protobuf"

var (
	file_TRACK_INFO_proto_rawDescOnce sync.Once
	file_TRACK_INFO_proto_rawDescData []byte
)

func file_TRACK_INFO_proto_rawDescGZIP() []byte {
	file_TRACK_INFO_proto_rawDescOnce.Do(func() {
		file_TRACK_INFO_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TRACK_INFO_proto_rawDesc), len(file_TRACK_INFO_proto_rawDesc)))
	})
	return file_TRACK_INFO_proto_rawDescData
}

var file_TRACK_INFO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TRACK_INFO_proto_goTypes = []any{
	(*TRACK_INFO)(nil), // 0: belfast.TRACK_INFO
}
var file_TRACK_INFO_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TRACK_INFO_proto_init() }
func file_TRACK_INFO_proto_init() {
	if File_TRACK_INFO_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TRACK_INFO_proto_rawDesc), len(file_TRACK_INFO_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TRACK_INFO_proto_goTypes,
		DependencyIndexes: file_TRACK_INFO_proto_depIdxs,
		MessageInfos:      file_TRACK_INFO_proto_msgTypes,
	}.Build()
	File_TRACK_INFO_proto = out.File
	file_TRACK_INFO_proto_goTypes = nil
	file_TRACK_INFO_proto_depIdxs = nil
}
