// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: WORLDTARGET_PROCESS.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WORLDTARGET_PROCESS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerId     *uint32                `protobuf:"varint,1,req,name=trigger_id,json=triggerId" json:"trigger_id,omitempty"`
	Count         *uint32                `protobuf:"varint,2,req,name=count" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WORLDTARGET_PROCESS) Reset() {
	*x = WORLDTARGET_PROCESS{}
	mi := &file_WORLDTARGET_PROCESS_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WORLDTARGET_PROCESS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WORLDTARGET_PROCESS) ProtoMessage() {}

func (x *WORLDTARGET_PROCESS) ProtoReflect() protoreflect.Message {
	mi := &file_WORLDTARGET_PROCESS_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WORLDTARGET_PROCESS.ProtoReflect.Descriptor instead.
func (*WORLDTARGET_PROCESS) Descriptor() ([]byte, []int) {
	return file_WORLDTARGET_PROCESS_proto_rawDescGZIP(), []int{0}
}

func (x *WORLDTARGET_PROCESS) GetTriggerId() uint32 {
	if x != nil && x.TriggerId != nil {
		return *x.TriggerId
	}
	return 0
}

func (x *WORLDTARGET_PROCESS) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

var File_WORLDTARGET_PROCESS_proto protoreflect.FileDescriptor

const file_WORLDTARGET_PROCESS_proto_rawDesc = "" +
	"\n" +
	"\x19WORLDTARGET_PROCESS.proto\x12\abelfast\"J\n" +
	"\x13WORLDTARGET_PROCESS\x12\x1d\n" +
	"\n" +
	"trigger_id\x18\x01 \x02(\rR\ttriggerId\x12\x14\n" +
	"\x05count\x18\x02 \x02(\rR\x05countB\fZ\n" +
	"./protobuf"

var (
	file_WORLDTARGET_PROCESS_proto_rawDescOnce sync.Once
	file_WORLDTARGET_PROCESS_proto_rawDescData []byte
)

func file_WORLDTARGET_PROCESS_proto_rawDescGZIP() []byte {
	file_WORLDTARGET_PROCESS_proto_rawDescOnce.Do(func() {
		file_WORLDTARGET_PROCESS_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_WORLDTARGET_PROCESS_proto_rawDesc), len(file_WORLDTARGET_PROCESS_proto_rawDesc)))
	})
	return file_WORLDTARGET_PROCESS_proto_rawDescData
}

var file_WORLDTARGET_PROCESS_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_WORLDTARGET_PROCESS_proto_goTypes = []any{
	(*WORLDTARGET_PROCESS)(nil), // 0: belfast.WORLDTARGET_PROCESS
}
var file_WORLDTARGET_PROCESS_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_WORLDTARGET_PROCESS_proto_init() }
func file_WORLDTARGET_PROCESS_proto_init() {
	if File_WORLDTARGET_PROCESS_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_WORLDTARGET_PROCESS_proto_rawDesc), len(file_WORLDTARGET_PROCESS_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_WORLDTARGET_PROCESS_proto_goTypes,
		DependencyIndexes: file_WORLDTARGET_PROCESS_proto_depIdxs,
		MessageInfos:      file_WORLDTARGET_PROCESS_proto_msgTypes,
	}.Build()
	File_WORLDTARGET_PROCESS_proto = out.File
	file_WORLDTARGET_PROCESS_proto_goTypes = nil
	file_WORLDTARGET_PROCESS_proto_depIdxs = nil
}
