// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: WORLDITEMINFO.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WORLDITEMINFO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemType      *uint32                `protobuf:"varint,1,req,name=item_type,json=itemType" json:"item_type,omitempty"`
	ItemId        *uint32                `protobuf:"varint,2,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	ItemFlag      *uint32                `protobuf:"varint,3,opt,name=item_flag,json=itemFlag" json:"item_flag,omitempty"`
	ItemData      *uint32                `protobuf:"varint,4,opt,name=item_data,json=itemData" json:"item_data,omitempty"`
	BuffList      []uint32               `protobuf:"varint,5,rep,name=buff_list,json=buffList" json:"buff_list,omitempty"`
	BossHp        *uint32                `protobuf:"varint,6,opt,name=boss_hp,json=bossHp" json:"boss_hp,omitempty"`
	EffectList    []uint32               `protobuf:"varint,7,rep,name=effect_list,json=effectList" json:"effect_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WORLDITEMINFO) Reset() {
	*x = WORLDITEMINFO{}
	mi := &file_WORLDITEMINFO_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WORLDITEMINFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WORLDITEMINFO) ProtoMessage() {}

func (x *WORLDITEMINFO) ProtoReflect() protoreflect.Message {
	mi := &file_WORLDITEMINFO_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WORLDITEMINFO.ProtoReflect.Descriptor instead.
func (*WORLDITEMINFO) Descriptor() ([]byte, []int) {
	return file_WORLDITEMINFO_proto_rawDescGZIP(), []int{0}
}

func (x *WORLDITEMINFO) GetItemType() uint32 {
	if x != nil && x.ItemType != nil {
		return *x.ItemType
	}
	return 0
}

func (x *WORLDITEMINFO) GetItemId() uint32 {
	if x != nil && x.ItemId != nil {
		return *x.ItemId
	}
	return 0
}

func (x *WORLDITEMINFO) GetItemFlag() uint32 {
	if x != nil && x.ItemFlag != nil {
		return *x.ItemFlag
	}
	return 0
}

func (x *WORLDITEMINFO) GetItemData() uint32 {
	if x != nil && x.ItemData != nil {
		return *x.ItemData
	}
	return 0
}

func (x *WORLDITEMINFO) GetBuffList() []uint32 {
	if x != nil {
		return x.BuffList
	}
	return nil
}

func (x *WORLDITEMINFO) GetBossHp() uint32 {
	if x != nil && x.BossHp != nil {
		return *x.BossHp
	}
	return 0
}

func (x *WORLDITEMINFO) GetEffectList() []uint32 {
	if x != nil {
		return x.EffectList
	}
	return nil
}

var File_WORLDITEMINFO_proto protoreflect.FileDescriptor

const file_WORLDITEMINFO_proto_rawDesc = "" +
	"\n" +
	"\x13WORLDITEMINFO.proto\x12\abelfast\"\xd6\x01\n" +
	"\rWORLDITEMINFO\x12\x1b\n" +
	"\titem_type\x18\x01 \x02(\rR\bitemType\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\rR\x06itemId\x12\x1b\n" +
	"\titem_flag\x18\x03 \x01(\rR\bitemFlag\x12\x1b\n" +
	"\titem_data\x18\x04 \x01(\rR\bitemData\x12\x1b\n" +
	"\tbuff_list\x18\x05 \x03(\rR\bbuffList\x12\x17\n" +
	"\aboss_hp\x18\x06 \x01(\rR\x06bossHp\x12\x1f\n" +
	"\veffect_list\x18\a \x03(\rR\n" +
	"effectListB\fZ\n" +
	"./protobuf"

var (
	file_WORLDITEMINFO_proto_rawDescOnce sync.Once
	file_WORLDITEMINFO_proto_rawDescData []byte
)

func file_WORLDITEMINFO_proto_rawDescGZIP() []byte {
	file_WORLDITEMINFO_proto_rawDescOnce.Do(func() {
		file_WORLDITEMINFO_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_WORLDITEMINFO_proto_rawDesc), len(file_WORLDITEMINFO_proto_rawDesc)))
	})
	return file_WORLDITEMINFO_proto_rawDescData
}

var file_WORLDITEMINFO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_WORLDITEMINFO_proto_goTypes = []any{
	(*WORLDITEMINFO)(nil), // 0: belfast.WORLDITEMINFO
}
var file_WORLDITEMINFO_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_WORLDITEMINFO_proto_init() }
func file_WORLDITEMINFO_proto_init() {
	if File_WORLDITEMINFO_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_WORLDITEMINFO_proto_rawDesc), len(file_WORLDITEMINFO_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_WORLDITEMINFO_proto_goTypes,
		DependencyIndexes: file_WORLDITEMINFO_proto_depIdxs,
		MessageInfos:      file_WORLDITEMINFO_proto_msgTypes,
	}.Build()
	File_WORLDITEMINFO_proto = out.File
	file_WORLDITEMINFO_proto_goTypes = nil
	file_WORLDITEMINFO_proto_depIdxs = nil
}
