// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: APARTMENT_GIVE_GIFT.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APARTMENT_GIVE_GIFT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GiftId *uint32 `protobuf:"varint,1,req,name=gift_id,json=giftId" json:"gift_id,omitempty"`
	Number *uint32 `protobuf:"varint,2,req,name=number" json:"number,omitempty"`
}

func (x *APARTMENT_GIVE_GIFT) Reset() {
	*x = APARTMENT_GIVE_GIFT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_APARTMENT_GIVE_GIFT_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APARTMENT_GIVE_GIFT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APARTMENT_GIVE_GIFT) ProtoMessage() {}

func (x *APARTMENT_GIVE_GIFT) ProtoReflect() protoreflect.Message {
	mi := &file_APARTMENT_GIVE_GIFT_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APARTMENT_GIVE_GIFT.ProtoReflect.Descriptor instead.
func (*APARTMENT_GIVE_GIFT) Descriptor() ([]byte, []int) {
	return file_APARTMENT_GIVE_GIFT_proto_rawDescGZIP(), []int{0}
}

func (x *APARTMENT_GIVE_GIFT) GetGiftId() uint32 {
	if x != nil && x.GiftId != nil {
		return *x.GiftId
	}
	return 0
}

func (x *APARTMENT_GIVE_GIFT) GetNumber() uint32 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

var File_APARTMENT_GIVE_GIFT_proto protoreflect.FileDescriptor

var file_APARTMENT_GIVE_GIFT_proto_rawDesc = []byte{
	0x0a, 0x19, 0x41, 0x50, 0x41, 0x52, 0x54, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x47, 0x49, 0x56, 0x45,
	0x5f, 0x47, 0x49, 0x46, 0x54, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x65, 0x6c,
	0x66, 0x61, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x13, 0x41, 0x50, 0x41, 0x52, 0x54, 0x4d, 0x45, 0x4e,
	0x54, 0x5f, 0x47, 0x49, 0x56, 0x45, 0x5f, 0x47, 0x49, 0x46, 0x54, 0x12, 0x17, 0x0a, 0x07, 0x67,
	0x69, 0x66, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x69,
	0x66, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
}

var (
	file_APARTMENT_GIVE_GIFT_proto_rawDescOnce sync.Once
	file_APARTMENT_GIVE_GIFT_proto_rawDescData = file_APARTMENT_GIVE_GIFT_proto_rawDesc
)

func file_APARTMENT_GIVE_GIFT_proto_rawDescGZIP() []byte {
	file_APARTMENT_GIVE_GIFT_proto_rawDescOnce.Do(func() {
		file_APARTMENT_GIVE_GIFT_proto_rawDescData = protoimpl.X.CompressGZIP(file_APARTMENT_GIVE_GIFT_proto_rawDescData)
	})
	return file_APARTMENT_GIVE_GIFT_proto_rawDescData
}

var file_APARTMENT_GIVE_GIFT_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_APARTMENT_GIVE_GIFT_proto_goTypes = []any{
	(*APARTMENT_GIVE_GIFT)(nil), // 0: belfast.APARTMENT_GIVE_GIFT
}
var file_APARTMENT_GIVE_GIFT_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_APARTMENT_GIVE_GIFT_proto_init() }
func file_APARTMENT_GIVE_GIFT_proto_init() {
	if File_APARTMENT_GIVE_GIFT_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_APARTMENT_GIVE_GIFT_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*APARTMENT_GIVE_GIFT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_APARTMENT_GIVE_GIFT_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_APARTMENT_GIVE_GIFT_proto_goTypes,
		DependencyIndexes: file_APARTMENT_GIVE_GIFT_proto_depIdxs,
		MessageInfos:      file_APARTMENT_GIVE_GIFT_proto_msgTypes,
	}.Build()
	File_APARTMENT_GIVE_GIFT_proto = out.File
	file_APARTMENT_GIVE_GIFT_proto_rawDesc = nil
	file_APARTMENT_GIVE_GIFT_proto_goTypes = nil
	file_APARTMENT_GIVE_GIFT_proto_depIdxs = nil
}
