// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: COMMANDERBOXINFO.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type COMMANDERBOXINFO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	PoolId     *uint32 `protobuf:"varint,2,req,name=poolId" json:"poolId,omitempty"`
	FinishTime *uint32 `protobuf:"varint,3,req,name=finish_time,json=finishTime" json:"finish_time,omitempty"`
	BeginTime  *uint32 `protobuf:"varint,4,req,name=begin_time,json=beginTime" json:"begin_time,omitempty"`
}

func (x *COMMANDERBOXINFO) Reset() {
	*x = COMMANDERBOXINFO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_COMMANDERBOXINFO_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *COMMANDERBOXINFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*COMMANDERBOXINFO) ProtoMessage() {}

func (x *COMMANDERBOXINFO) ProtoReflect() protoreflect.Message {
	mi := &file_COMMANDERBOXINFO_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use COMMANDERBOXINFO.ProtoReflect.Descriptor instead.
func (*COMMANDERBOXINFO) Descriptor() ([]byte, []int) {
	return file_COMMANDERBOXINFO_proto_rawDescGZIP(), []int{0}
}

func (x *COMMANDERBOXINFO) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *COMMANDERBOXINFO) GetPoolId() uint32 {
	if x != nil && x.PoolId != nil {
		return *x.PoolId
	}
	return 0
}

func (x *COMMANDERBOXINFO) GetFinishTime() uint32 {
	if x != nil && x.FinishTime != nil {
		return *x.FinishTime
	}
	return 0
}

func (x *COMMANDERBOXINFO) GetBeginTime() uint32 {
	if x != nil && x.BeginTime != nil {
		return *x.BeginTime
	}
	return 0
}

var File_COMMANDERBOXINFO_proto protoreflect.FileDescriptor

var file_COMMANDERBOXINFO_proto_rawDesc = []byte{
	0x0a, 0x16, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x45, 0x52, 0x42, 0x4f, 0x58, 0x49, 0x4e,
	0x46, 0x4f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x65, 0x6c, 0x66, 0x61, 0x73,
	0x74, 0x22, 0x7a, 0x0a, 0x10, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x45, 0x52, 0x42, 0x4f,
	0x58, 0x49, 0x4e, 0x46, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x02,
	0x28, 0x0d, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x02,
	0x28, 0x0d, 0x52, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
}

var (
	file_COMMANDERBOXINFO_proto_rawDescOnce sync.Once
	file_COMMANDERBOXINFO_proto_rawDescData = file_COMMANDERBOXINFO_proto_rawDesc
)

func file_COMMANDERBOXINFO_proto_rawDescGZIP() []byte {
	file_COMMANDERBOXINFO_proto_rawDescOnce.Do(func() {
		file_COMMANDERBOXINFO_proto_rawDescData = protoimpl.X.CompressGZIP(file_COMMANDERBOXINFO_proto_rawDescData)
	})
	return file_COMMANDERBOXINFO_proto_rawDescData
}

var file_COMMANDERBOXINFO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_COMMANDERBOXINFO_proto_goTypes = []any{
	(*COMMANDERBOXINFO)(nil), // 0: belfast.COMMANDERBOXINFO
}
var file_COMMANDERBOXINFO_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_COMMANDERBOXINFO_proto_init() }
func file_COMMANDERBOXINFO_proto_init() {
	if File_COMMANDERBOXINFO_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_COMMANDERBOXINFO_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*COMMANDERBOXINFO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_COMMANDERBOXINFO_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_COMMANDERBOXINFO_proto_goTypes,
		DependencyIndexes: file_COMMANDERBOXINFO_proto_depIdxs,
		MessageInfos:      file_COMMANDERBOXINFO_proto_msgTypes,
	}.Build()
	File_COMMANDERBOXINFO_proto = out.File
	file_COMMANDERBOXINFO_proto_rawDesc = nil
	file_COMMANDERBOXINFO_proto_goTypes = nil
	file_COMMANDERBOXINFO_proto_depIdxs = nil
}
