// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: CS_10020.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_10020 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginType *uint32 `protobuf:"varint,1,req,name=login_type,json=loginType" json:"login_type,omitempty"`
	Arg1      *string `protobuf:"bytes,2,req,name=arg1" json:"arg1,omitempty"`
	Arg2      *string `protobuf:"bytes,3,opt,name=arg2" json:"arg2,omitempty"`
	Arg3      *string `protobuf:"bytes,4,opt,name=arg3" json:"arg3,omitempty"`
	Arg4      *string `protobuf:"bytes,5,opt,name=arg4" json:"arg4,omitempty"`
	CheckKey  *string `protobuf:"bytes,6,req,name=check_key,json=checkKey" json:"check_key,omitempty"`
	Device    *uint32 `protobuf:"varint,7,opt,name=device" json:"device,omitempty"`
}

func (x *CS_10020) Reset() {
	*x = CS_10020{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CS_10020_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_10020) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_10020) ProtoMessage() {}

func (x *CS_10020) ProtoReflect() protoreflect.Message {
	mi := &file_CS_10020_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_10020.ProtoReflect.Descriptor instead.
func (*CS_10020) Descriptor() ([]byte, []int) {
	return file_CS_10020_proto_rawDescGZIP(), []int{0}
}

func (x *CS_10020) GetLoginType() uint32 {
	if x != nil && x.LoginType != nil {
		return *x.LoginType
	}
	return 0
}

func (x *CS_10020) GetArg1() string {
	if x != nil && x.Arg1 != nil {
		return *x.Arg1
	}
	return ""
}

func (x *CS_10020) GetArg2() string {
	if x != nil && x.Arg2 != nil {
		return *x.Arg2
	}
	return ""
}

func (x *CS_10020) GetArg3() string {
	if x != nil && x.Arg3 != nil {
		return *x.Arg3
	}
	return ""
}

func (x *CS_10020) GetArg4() string {
	if x != nil && x.Arg4 != nil {
		return *x.Arg4
	}
	return ""
}

func (x *CS_10020) GetCheckKey() string {
	if x != nil && x.CheckKey != nil {
		return *x.CheckKey
	}
	return ""
}

func (x *CS_10020) GetDevice() uint32 {
	if x != nil && x.Device != nil {
		return *x.Device
	}
	return 0
}

var File_CS_10020_proto protoreflect.FileDescriptor

var file_CS_10020_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x43, 0x53, 0x5f, 0x31, 0x30, 0x30, 0x32, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x62, 0x65, 0x6c, 0x66, 0x61, 0x73, 0x74, 0x22, 0xae, 0x01, 0x0a, 0x08, 0x43, 0x53,
	0x5f, 0x31, 0x30, 0x30, 0x32, 0x30, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x31, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67,
	0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x32, 0x12, 0x12, 0x0a,
	0x04, 0x61, 0x72, 0x67, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67,
	0x33, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x34, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x72, 0x67, 0x34, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x06, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4b,
	0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
}

var (
	file_CS_10020_proto_rawDescOnce sync.Once
	file_CS_10020_proto_rawDescData = file_CS_10020_proto_rawDesc
)

func file_CS_10020_proto_rawDescGZIP() []byte {
	file_CS_10020_proto_rawDescOnce.Do(func() {
		file_CS_10020_proto_rawDescData = protoimpl.X.CompressGZIP(file_CS_10020_proto_rawDescData)
	})
	return file_CS_10020_proto_rawDescData
}

var file_CS_10020_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CS_10020_proto_goTypes = []any{
	(*CS_10020)(nil), // 0: belfast.CS_10020
}
var file_CS_10020_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CS_10020_proto_init() }
func file_CS_10020_proto_init() {
	if File_CS_10020_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CS_10020_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CS_10020); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CS_10020_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CS_10020_proto_goTypes,
		DependencyIndexes: file_CS_10020_proto_depIdxs,
		MessageInfos:      file_CS_10020_proto_msgTypes,
	}.Build()
	File_CS_10020_proto = out.File
	file_CS_10020_proto_rawDesc = nil
	file_CS_10020_proto_goTypes = nil
	file_CS_10020_proto_depIdxs = nil
}
