// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: CS_33602.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_33602 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*WORLDTARGET_FETCH `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (x *CS_33602) Reset() {
	*x = CS_33602{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CS_33602_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_33602) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_33602) ProtoMessage() {}

func (x *CS_33602) ProtoReflect() protoreflect.Message {
	mi := &file_CS_33602_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_33602.ProtoReflect.Descriptor instead.
func (*CS_33602) Descriptor() ([]byte, []int) {
	return file_CS_33602_proto_rawDescGZIP(), []int{0}
}

func (x *CS_33602) GetList() []*WORLDTARGET_FETCH {
	if x != nil {
		return x.List
	}
	return nil
}

var File_CS_33602_proto protoreflect.FileDescriptor

var file_CS_33602_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x43, 0x53, 0x5f, 0x33, 0x33, 0x36, 0x30, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x62, 0x65, 0x6c, 0x66, 0x61, 0x73, 0x74, 0x1a, 0x17, 0x57, 0x4f, 0x52, 0x4c, 0x44,
	0x54, 0x41, 0x52, 0x47, 0x45, 0x54, 0x5f, 0x46, 0x45, 0x54, 0x43, 0x48, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x08, 0x43, 0x53, 0x5f, 0x33, 0x33, 0x36, 0x30, 0x32, 0x12, 0x2e,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62,
	0x65, 0x6c, 0x66, 0x61, 0x73, 0x74, 0x2e, 0x57, 0x4f, 0x52, 0x4c, 0x44, 0x54, 0x41, 0x52, 0x47,
	0x45, 0x54, 0x5f, 0x46, 0x45, 0x54, 0x43, 0x48, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
}

var (
	file_CS_33602_proto_rawDescOnce sync.Once
	file_CS_33602_proto_rawDescData = file_CS_33602_proto_rawDesc
)

func file_CS_33602_proto_rawDescGZIP() []byte {
	file_CS_33602_proto_rawDescOnce.Do(func() {
		file_CS_33602_proto_rawDescData = protoimpl.X.CompressGZIP(file_CS_33602_proto_rawDescData)
	})
	return file_CS_33602_proto_rawDescData
}

var file_CS_33602_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CS_33602_proto_goTypes = []any{
	(*CS_33602)(nil),          // 0: belfast.CS_33602
	(*WORLDTARGET_FETCH)(nil), // 1: belfast.WORLDTARGET_FETCH
}
var file_CS_33602_proto_depIdxs = []int32{
	1, // 0: belfast.CS_33602.list:type_name -> belfast.WORLDTARGET_FETCH
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CS_33602_proto_init() }
func file_CS_33602_proto_init() {
	if File_CS_33602_proto != nil {
		return
	}
	file_WORLDTARGET_FETCH_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_CS_33602_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CS_33602); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CS_33602_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CS_33602_proto_goTypes,
		DependencyIndexes: file_CS_33602_proto_depIdxs,
		MessageInfos:      file_CS_33602_proto_msgTypes,
	}.Build()
	File_CS_33602_proto = out.File
	file_CS_33602_proto_rawDesc = nil
	file_CS_33602_proto_goTypes = nil
	file_CS_33602_proto_depIdxs = nil
}
