// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.25.3
// source: FLEETTECH.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FLEETTECH struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId         *uint32 `protobuf:"varint,1,req,name=group_id,json=groupId" json:"group_id,omitempty"`
	EffectTechId    *uint32 `protobuf:"varint,2,req,name=effect_tech_id,json=effectTechId" json:"effect_tech_id,omitempty"`
	StudyTechId     *uint32 `protobuf:"varint,3,req,name=study_tech_id,json=studyTechId" json:"study_tech_id,omitempty"`
	StudyFinishTime *uint32 `protobuf:"varint,4,req,name=study_finish_time,json=studyFinishTime" json:"study_finish_time,omitempty"`
	RewardedTech    *uint32 `protobuf:"varint,5,req,name=rewarded_tech,json=rewardedTech" json:"rewarded_tech,omitempty"`
}

func (x *FLEETTECH) Reset() {
	*x = FLEETTECH{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FLEETTECH_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FLEETTECH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FLEETTECH) ProtoMessage() {}

func (x *FLEETTECH) ProtoReflect() protoreflect.Message {
	mi := &file_FLEETTECH_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FLEETTECH.ProtoReflect.Descriptor instead.
func (*FLEETTECH) Descriptor() ([]byte, []int) {
	return file_FLEETTECH_proto_rawDescGZIP(), []int{0}
}

func (x *FLEETTECH) GetGroupId() uint32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *FLEETTECH) GetEffectTechId() uint32 {
	if x != nil && x.EffectTechId != nil {
		return *x.EffectTechId
	}
	return 0
}

func (x *FLEETTECH) GetStudyTechId() uint32 {
	if x != nil && x.StudyTechId != nil {
		return *x.StudyTechId
	}
	return 0
}

func (x *FLEETTECH) GetStudyFinishTime() uint32 {
	if x != nil && x.StudyFinishTime != nil {
		return *x.StudyFinishTime
	}
	return 0
}

func (x *FLEETTECH) GetRewardedTech() uint32 {
	if x != nil && x.RewardedTech != nil {
		return *x.RewardedTech
	}
	return 0
}

var File_FLEETTECH_proto protoreflect.FileDescriptor

var file_FLEETTECH_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x46, 0x4c, 0x45, 0x45, 0x54, 0x54, 0x45, 0x43, 0x48, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x62, 0x65, 0x6c, 0x66, 0x61, 0x73, 0x74, 0x22, 0xc1, 0x01, 0x0a, 0x09, 0x46,
	0x4c, 0x45, 0x45, 0x54, 0x54, 0x45, 0x43, 0x48, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x65,
	0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0c, 0x65, 0x66, 0x66,
	0x65, 0x63, 0x74, 0x54, 0x65, 0x63, 0x68, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x74, 0x75,
	0x64, 0x79, 0x5f, 0x74, 0x65, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d,
	0x52, 0x0b, 0x73, 0x74, 0x75, 0x64, 0x79, 0x54, 0x65, 0x63, 0x68, 0x49, 0x64, 0x12, 0x2a, 0x0a,
	0x11, 0x73, 0x74, 0x75, 0x64, 0x79, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0f, 0x73, 0x74, 0x75, 0x64, 0x79, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x65, 0x64, 0x5f, 0x74, 0x65, 0x63, 0x68, 0x18, 0x05, 0x20, 0x02, 0x28, 0x0d,
	0x52, 0x0c, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x54, 0x65, 0x63, 0x68, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
}

var (
	file_FLEETTECH_proto_rawDescOnce sync.Once
	file_FLEETTECH_proto_rawDescData = file_FLEETTECH_proto_rawDesc
)

func file_FLEETTECH_proto_rawDescGZIP() []byte {
	file_FLEETTECH_proto_rawDescOnce.Do(func() {
		file_FLEETTECH_proto_rawDescData = protoimpl.X.CompressGZIP(file_FLEETTECH_proto_rawDescData)
	})
	return file_FLEETTECH_proto_rawDescData
}

var file_FLEETTECH_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_FLEETTECH_proto_goTypes = []interface{}{
	(*FLEETTECH)(nil), // 0: belfast.FLEETTECH
}
var file_FLEETTECH_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_FLEETTECH_proto_init() }
func file_FLEETTECH_proto_init() {
	if File_FLEETTECH_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_FLEETTECH_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FLEETTECH); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_FLEETTECH_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FLEETTECH_proto_goTypes,
		DependencyIndexes: file_FLEETTECH_proto_depIdxs,
		MessageInfos:      file_FLEETTECH_proto_msgTypes,
	}.Build()
	File_FLEETTECH_proto = out.File
	file_FLEETTECH_proto_rawDesc = nil
	file_FLEETTECH_proto_goTypes = nil
	file_FLEETTECH_proto_depIdxs = nil
}
