// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: P_PARTY_ROLE.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type P_PARTY_ROLE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tid          *uint32 `protobuf:"varint,1,req,name=tid" json:"tid,omitempty"`
	Bubble       *uint32 `protobuf:"varint,2,req,name=bubble" json:"bubble,omitempty"`
	SpeechBubble *uint32 `protobuf:"varint,3,req,name=speech_bubble,json=speechBubble" json:"speech_bubble,omitempty"`
}

func (x *P_PARTY_ROLE) Reset() {
	*x = P_PARTY_ROLE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_P_PARTY_ROLE_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P_PARTY_ROLE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P_PARTY_ROLE) ProtoMessage() {}

func (x *P_PARTY_ROLE) ProtoReflect() protoreflect.Message {
	mi := &file_P_PARTY_ROLE_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P_PARTY_ROLE.ProtoReflect.Descriptor instead.
func (*P_PARTY_ROLE) Descriptor() ([]byte, []int) {
	return file_P_PARTY_ROLE_proto_rawDescGZIP(), []int{0}
}

func (x *P_PARTY_ROLE) GetTid() uint32 {
	if x != nil && x.Tid != nil {
		return *x.Tid
	}
	return 0
}

func (x *P_PARTY_ROLE) GetBubble() uint32 {
	if x != nil && x.Bubble != nil {
		return *x.Bubble
	}
	return 0
}

func (x *P_PARTY_ROLE) GetSpeechBubble() uint32 {
	if x != nil && x.SpeechBubble != nil {
		return *x.SpeechBubble
	}
	return 0
}

var File_P_PARTY_ROLE_proto protoreflect.FileDescriptor

var file_P_PARTY_ROLE_proto_rawDesc = []byte{
	0x0a, 0x12, 0x50, 0x5f, 0x50, 0x41, 0x52, 0x54, 0x59, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x65, 0x6c, 0x66, 0x61, 0x73, 0x74, 0x22, 0x5d, 0x0a,
	0x0c, 0x50, 0x5f, 0x50, 0x41, 0x52, 0x54, 0x59, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52,
	0x06, 0x62, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x70, 0x65, 0x65, 0x63,
	0x68, 0x5f, 0x62, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0c,
	0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x42, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
}

var (
	file_P_PARTY_ROLE_proto_rawDescOnce sync.Once
	file_P_PARTY_ROLE_proto_rawDescData = file_P_PARTY_ROLE_proto_rawDesc
)

func file_P_PARTY_ROLE_proto_rawDescGZIP() []byte {
	file_P_PARTY_ROLE_proto_rawDescOnce.Do(func() {
		file_P_PARTY_ROLE_proto_rawDescData = protoimpl.X.CompressGZIP(file_P_PARTY_ROLE_proto_rawDescData)
	})
	return file_P_PARTY_ROLE_proto_rawDescData
}

var file_P_PARTY_ROLE_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_P_PARTY_ROLE_proto_goTypes = []any{
	(*P_PARTY_ROLE)(nil), // 0: belfast.P_PARTY_ROLE
}
var file_P_PARTY_ROLE_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_P_PARTY_ROLE_proto_init() }
func file_P_PARTY_ROLE_proto_init() {
	if File_P_PARTY_ROLE_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_P_PARTY_ROLE_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*P_PARTY_ROLE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_P_PARTY_ROLE_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_P_PARTY_ROLE_proto_goTypes,
		DependencyIndexes: file_P_PARTY_ROLE_proto_depIdxs,
		MessageInfos:      file_P_PARTY_ROLE_proto_msgTypes,
	}.Build()
	File_P_PARTY_ROLE_proto = out.File
	file_P_PARTY_ROLE_proto_rawDesc = nil
	file_P_PARTY_ROLE_proto_goTypes = nil
	file_P_PARTY_ROLE_proto_depIdxs = nil
}
