// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.25.3
// source: RANK_INFO.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RANK_INFO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Period       *uint32           `protobuf:"varint,1,req,name=period" json:"period,omitempty"`
	Rankuserinfo []*RANK_USER_INFO `protobuf:"bytes,2,rep,name=rankuserinfo" json:"rankuserinfo,omitempty"`
}

func (x *RANK_INFO) Reset() {
	*x = RANK_INFO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RANK_INFO_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RANK_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RANK_INFO) ProtoMessage() {}

func (x *RANK_INFO) ProtoReflect() protoreflect.Message {
	mi := &file_RANK_INFO_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RANK_INFO.ProtoReflect.Descriptor instead.
func (*RANK_INFO) Descriptor() ([]byte, []int) {
	return file_RANK_INFO_proto_rawDescGZIP(), []int{0}
}

func (x *RANK_INFO) GetPeriod() uint32 {
	if x != nil && x.Period != nil {
		return *x.Period
	}
	return 0
}

func (x *RANK_INFO) GetRankuserinfo() []*RANK_USER_INFO {
	if x != nil {
		return x.Rankuserinfo
	}
	return nil
}

var File_RANK_INFO_proto protoreflect.FileDescriptor

var file_RANK_INFO_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x52, 0x41, 0x4e, 0x4b, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x62, 0x65, 0x6c, 0x66, 0x61, 0x73, 0x74, 0x1a, 0x14, 0x52, 0x41, 0x4e, 0x4b,
	0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x60, 0x0a, 0x09, 0x52, 0x41, 0x4e, 0x4b, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x70,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x3b, 0x0a, 0x0c, 0x72, 0x61, 0x6e, 0x6b, 0x75, 0x73, 0x65,
	0x72, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x65,
	0x6c, 0x66, 0x61, 0x73, 0x74, 0x2e, 0x52, 0x41, 0x4e, 0x4b, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f,
	0x49, 0x4e, 0x46, 0x4f, 0x52, 0x0c, 0x72, 0x61, 0x6e, 0x6b, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e,
	0x66, 0x6f, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
}

var (
	file_RANK_INFO_proto_rawDescOnce sync.Once
	file_RANK_INFO_proto_rawDescData = file_RANK_INFO_proto_rawDesc
)

func file_RANK_INFO_proto_rawDescGZIP() []byte {
	file_RANK_INFO_proto_rawDescOnce.Do(func() {
		file_RANK_INFO_proto_rawDescData = protoimpl.X.CompressGZIP(file_RANK_INFO_proto_rawDescData)
	})
	return file_RANK_INFO_proto_rawDescData
}

var file_RANK_INFO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_RANK_INFO_proto_goTypes = []interface{}{
	(*RANK_INFO)(nil),      // 0: belfast.RANK_INFO
	(*RANK_USER_INFO)(nil), // 1: belfast.RANK_USER_INFO
}
var file_RANK_INFO_proto_depIdxs = []int32{
	1, // 0: belfast.RANK_INFO.rankuserinfo:type_name -> belfast.RANK_USER_INFO
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_RANK_INFO_proto_init() }
func file_RANK_INFO_proto_init() {
	if File_RANK_INFO_proto != nil {
		return
	}
	file_RANK_USER_INFO_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_RANK_INFO_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RANK_INFO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RANK_INFO_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RANK_INFO_proto_goTypes,
		DependencyIndexes: file_RANK_INFO_proto_depIdxs,
		MessageInfos:      file_RANK_INFO_proto_msgTypes,
	}.Build()
	File_RANK_INFO_proto = out.File
	file_RANK_INFO_proto_rawDesc = nil
	file_RANK_INFO_proto_goTypes = nil
	file_RANK_INFO_proto_depIdxs = nil
}
