// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.25.3
// source: REMAPCOUNT.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type REMAPCOUNT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChapterId *uint32 `protobuf:"varint,1,req,name=chapter_id,json=chapterId" json:"chapter_id,omitempty"`
	Pos       *uint32 `protobuf:"varint,2,req,name=pos" json:"pos,omitempty"`
	Count     *uint32 `protobuf:"varint,3,req,name=count" json:"count,omitempty"`
	Flag      *uint32 `protobuf:"varint,4,req,name=flag" json:"flag,omitempty"`
}

func (x *REMAPCOUNT) Reset() {
	*x = REMAPCOUNT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_REMAPCOUNT_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *REMAPCOUNT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*REMAPCOUNT) ProtoMessage() {}

func (x *REMAPCOUNT) ProtoReflect() protoreflect.Message {
	mi := &file_REMAPCOUNT_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use REMAPCOUNT.ProtoReflect.Descriptor instead.
func (*REMAPCOUNT) Descriptor() ([]byte, []int) {
	return file_REMAPCOUNT_proto_rawDescGZIP(), []int{0}
}

func (x *REMAPCOUNT) GetChapterId() uint32 {
	if x != nil && x.ChapterId != nil {
		return *x.ChapterId
	}
	return 0
}

func (x *REMAPCOUNT) GetPos() uint32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

func (x *REMAPCOUNT) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *REMAPCOUNT) GetFlag() uint32 {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return 0
}

var File_REMAPCOUNT_proto protoreflect.FileDescriptor

var file_REMAPCOUNT_proto_rawDesc = []byte{
	0x0a, 0x10, 0x52, 0x45, 0x4d, 0x41, 0x50, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x62, 0x65, 0x6c, 0x66, 0x61, 0x73, 0x74, 0x22, 0x67, 0x0a, 0x0a, 0x52,
	0x45, 0x4d, 0x41, 0x50, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x09, 0x63,
	0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x04,
	0x66, 0x6c, 0x61, 0x67, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66,
}

var (
	file_REMAPCOUNT_proto_rawDescOnce sync.Once
	file_REMAPCOUNT_proto_rawDescData = file_REMAPCOUNT_proto_rawDesc
)

func file_REMAPCOUNT_proto_rawDescGZIP() []byte {
	file_REMAPCOUNT_proto_rawDescOnce.Do(func() {
		file_REMAPCOUNT_proto_rawDescData = protoimpl.X.CompressGZIP(file_REMAPCOUNT_proto_rawDescData)
	})
	return file_REMAPCOUNT_proto_rawDescData
}

var file_REMAPCOUNT_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_REMAPCOUNT_proto_goTypes = []interface{}{
	(*REMAPCOUNT)(nil), // 0: belfast.REMAPCOUNT
}
var file_REMAPCOUNT_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_REMAPCOUNT_proto_init() }
func file_REMAPCOUNT_proto_init() {
	if File_REMAPCOUNT_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_REMAPCOUNT_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*REMAPCOUNT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_REMAPCOUNT_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_REMAPCOUNT_proto_goTypes,
		DependencyIndexes: file_REMAPCOUNT_proto_depIdxs,
		MessageInfos:      file_REMAPCOUNT_proto_msgTypes,
	}.Build()
	File_REMAPCOUNT_proto = out.File
	file_REMAPCOUNT_proto_rawDesc = nil
	file_REMAPCOUNT_proto_goTypes = nil
	file_REMAPCOUNT_proto_depIdxs = nil
}
