// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: SC_18002.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_18002 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score               *uint32       `protobuf:"varint,1,req,name=score" json:"score,omitempty"`
	Rank                *uint32       `protobuf:"varint,2,req,name=rank" json:"rank,omitempty"`
	FightCount          *uint32       `protobuf:"varint,3,req,name=fight_count,json=fightCount" json:"fight_count,omitempty"`
	FightCountResetTime *uint32       `protobuf:"varint,4,req,name=fight_count_reset_time,json=fightCountResetTime" json:"fight_count_reset_time,omitempty"`
	FlashTargetCount    *uint32       `protobuf:"varint,5,req,name=flash_target_count,json=flashTargetCount" json:"flash_target_count,omitempty"`
	VanguardShipIdList  []uint32      `protobuf:"varint,6,rep,name=vanguard_ship_id_list,json=vanguardShipIdList" json:"vanguard_ship_id_list,omitempty"`
	MainShipIdList      []uint32      `protobuf:"varint,7,rep,name=main_ship_id_list,json=mainShipIdList" json:"main_ship_id_list,omitempty"`
	TargetList          []*TARGETINFO `protobuf:"bytes,8,rep,name=target_list,json=targetList" json:"target_list,omitempty"`
}

func (x *SC_18002) Reset() {
	*x = SC_18002{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SC_18002_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_18002) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_18002) ProtoMessage() {}

func (x *SC_18002) ProtoReflect() protoreflect.Message {
	mi := &file_SC_18002_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_18002.ProtoReflect.Descriptor instead.
func (*SC_18002) Descriptor() ([]byte, []int) {
	return file_SC_18002_proto_rawDescGZIP(), []int{0}
}

func (x *SC_18002) GetScore() uint32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *SC_18002) GetRank() uint32 {
	if x != nil && x.Rank != nil {
		return *x.Rank
	}
	return 0
}

func (x *SC_18002) GetFightCount() uint32 {
	if x != nil && x.FightCount != nil {
		return *x.FightCount
	}
	return 0
}

func (x *SC_18002) GetFightCountResetTime() uint32 {
	if x != nil && x.FightCountResetTime != nil {
		return *x.FightCountResetTime
	}
	return 0
}

func (x *SC_18002) GetFlashTargetCount() uint32 {
	if x != nil && x.FlashTargetCount != nil {
		return *x.FlashTargetCount
	}
	return 0
}

func (x *SC_18002) GetVanguardShipIdList() []uint32 {
	if x != nil {
		return x.VanguardShipIdList
	}
	return nil
}

func (x *SC_18002) GetMainShipIdList() []uint32 {
	if x != nil {
		return x.MainShipIdList
	}
	return nil
}

func (x *SC_18002) GetTargetList() []*TARGETINFO {
	if x != nil {
		return x.TargetList
	}
	return nil
}

var File_SC_18002_proto protoreflect.FileDescriptor

var file_SC_18002_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x53, 0x43, 0x5f, 0x31, 0x38, 0x30, 0x30, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x62, 0x65, 0x6c, 0x66, 0x61, 0x73, 0x74, 0x1a, 0x10, 0x54, 0x41, 0x52, 0x47, 0x45,
	0x54, 0x49, 0x4e, 0x46, 0x4f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcc, 0x02, 0x0a, 0x08,
	0x53, 0x43, 0x5f, 0x31, 0x38, 0x30, 0x30, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x61,
	0x6e, 0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0a, 0x66, 0x69, 0x67, 0x68, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x16, 0x66, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x02, 0x28, 0x0d, 0x52, 0x13, 0x66, 0x69, 0x67, 0x68, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x66, 0x6c, 0x61, 0x73,
	0x68, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x02, 0x28, 0x0d, 0x52, 0x10, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x15, 0x76, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x72, 0x64, 0x5f, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x12, 0x76, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x53,
	0x68, 0x69, 0x70, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x11, 0x6d, 0x61, 0x69,
	0x6e, 0x5f, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x0d, 0x52, 0x0e, 0x6d, 0x61, 0x69, 0x6e, 0x53, 0x68, 0x69, 0x70, 0x49, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x65, 0x6c, 0x66,
	0x61, 0x73, 0x74, 0x2e, 0x54, 0x41, 0x52, 0x47, 0x45, 0x54, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x0a,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
}

var (
	file_SC_18002_proto_rawDescOnce sync.Once
	file_SC_18002_proto_rawDescData = file_SC_18002_proto_rawDesc
)

func file_SC_18002_proto_rawDescGZIP() []byte {
	file_SC_18002_proto_rawDescOnce.Do(func() {
		file_SC_18002_proto_rawDescData = protoimpl.X.CompressGZIP(file_SC_18002_proto_rawDescData)
	})
	return file_SC_18002_proto_rawDescData
}

var file_SC_18002_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_18002_proto_goTypes = []any{
	(*SC_18002)(nil),   // 0: belfast.SC_18002
	(*TARGETINFO)(nil), // 1: belfast.TARGETINFO
}
var file_SC_18002_proto_depIdxs = []int32{
	1, // 0: belfast.SC_18002.target_list:type_name -> belfast.TARGETINFO
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SC_18002_proto_init() }
func file_SC_18002_proto_init() {
	if File_SC_18002_proto != nil {
		return
	}
	file_TARGETINFO_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SC_18002_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SC_18002); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SC_18002_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_18002_proto_goTypes,
		DependencyIndexes: file_SC_18002_proto_depIdxs,
		MessageInfos:      file_SC_18002_proto_msgTypes,
	}.Build()
	File_SC_18002_proto = out.File
	file_SC_18002_proto_rawDesc = nil
	file_SC_18002_proto_goTypes = nil
	file_SC_18002_proto_depIdxs = nil
}
