// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: TECHSET.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TECHSET struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShipType *uint32 `protobuf:"varint,1,req,name=ship_type,json=shipType" json:"ship_type,omitempty"`
	AttrType *uint32 `protobuf:"varint,2,req,name=attr_type,json=attrType" json:"attr_type,omitempty"`
	SetValue *uint32 `protobuf:"varint,3,req,name=set_value,json=setValue" json:"set_value,omitempty"`
}

func (x *TECHSET) Reset() {
	*x = TECHSET{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TECHSET_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TECHSET) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TECHSET) ProtoMessage() {}

func (x *TECHSET) ProtoReflect() protoreflect.Message {
	mi := &file_TECHSET_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TECHSET.ProtoReflect.Descriptor instead.
func (*TECHSET) Descriptor() ([]byte, []int) {
	return file_TECHSET_proto_rawDescGZIP(), []int{0}
}

func (x *TECHSET) GetShipType() uint32 {
	if x != nil && x.ShipType != nil {
		return *x.ShipType
	}
	return 0
}

func (x *TECHSET) GetAttrType() uint32 {
	if x != nil && x.AttrType != nil {
		return *x.AttrType
	}
	return 0
}

func (x *TECHSET) GetSetValue() uint32 {
	if x != nil && x.SetValue != nil {
		return *x.SetValue
	}
	return 0
}

var File_TECHSET_proto protoreflect.FileDescriptor

var file_TECHSET_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x54, 0x45, 0x43, 0x48, 0x53, 0x45, 0x54, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x62, 0x65, 0x6c, 0x66, 0x61, 0x73, 0x74, 0x22, 0x60, 0x0a, 0x07, 0x54, 0x45, 0x43, 0x48,
	0x53, 0x45, 0x54, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x68, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x74, 0x74, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x65, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d,
	0x52, 0x08, 0x73, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
}

var (
	file_TECHSET_proto_rawDescOnce sync.Once
	file_TECHSET_proto_rawDescData = file_TECHSET_proto_rawDesc
)

func file_TECHSET_proto_rawDescGZIP() []byte {
	file_TECHSET_proto_rawDescOnce.Do(func() {
		file_TECHSET_proto_rawDescData = protoimpl.X.CompressGZIP(file_TECHSET_proto_rawDescData)
	})
	return file_TECHSET_proto_rawDescData
}

var file_TECHSET_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TECHSET_proto_goTypes = []any{
	(*TECHSET)(nil), // 0: belfast.TECHSET
}
var file_TECHSET_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TECHSET_proto_init() }
func file_TECHSET_proto_init() {
	if File_TECHSET_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TECHSET_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TECHSET); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TECHSET_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TECHSET_proto_goTypes,
		DependencyIndexes: file_TECHSET_proto_depIdxs,
		MessageInfos:      file_TECHSET_proto_msgTypes,
	}.Build()
	File_TECHSET_proto = out.File
	file_TECHSET_proto_rawDesc = nil
	file_TECHSET_proto_goTypes = nil
	file_TECHSET_proto_depIdxs = nil
}
