-- 0008_fleets_identity.sql
-- Milestone 6: fleets.id is inserted without specifying an id.

DO $$
DECLARE
  identity_flag text;
  default_expr text;
  seq_name text;
BEGIN
  SELECT is_identity, column_default
    INTO identity_flag, default_expr
    FROM information_schema.columns
   WHERE table_schema = current_schema()
     AND table_name = 'fleets'
     AND column_name = 'id';

  IF identity_flag IS NULL THEN
    RETURN;
  END IF;

  IF identity_flag <> 'YES' AND default_expr IS NULL THEN
    ALTER TABLE fleets
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;

  SELECT pg_get_serial_sequence(format('%I.%I', current_schema(), 'fleets'), 'id') INTO seq_name;
  IF seq_name IS NOT NULL THEN
    EXECUTE format(
      'SELECT setval(%L, COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM %I.%I',
      seq_name,
      current_schema(),
      'fleets'
    );
  END IF;
END
$$;
