package types

type SkinPayload struct {
	ID             uint32  `json:"id"`
	Name           string  `json:"name"`
	ShipGroup      int     `json:"ship_group"`
	Desc           string  `json:"desc"`
	BG             string  `json:"bg"`
	BGSp           string  `json:"bg_sp"`
	BGM            string  `json:"bgm"`
	Painting       string  `json:"painting"`
	Prefab         string  `json:"prefab"`
	ChangeSkin     RawJSON `json:"change_skin"`
	ShowSkin       string  `json:"show_skin"`
	SkeletonSkin   string  `json:"skeleton_default_skin"`
	ShipL2DID      RawJSON `json:"ship_l2d_id"`
	L2DAnimations  RawJSON `json:"l2d_animations"`
	L2DDragRate    RawJSON `json:"l2d_drag_rate"`
	L2DParaRange   RawJSON `json:"l2d_para_range"`
	L2DSE          RawJSON `json:"l2d_se"`
	L2DVoiceCalib  RawJSON `json:"l2d_voice_calibrate"`
	PartScale      string  `json:"part_scale"`
	MainUIFX       string  `json:"main_UI_FX"`
	SpineOffset    RawJSON `json:"spine_offset"`
	SpineProfile   RawJSON `json:"spine_offset_profile"`
	Tag            RawJSON `json:"tag"`
	Time           RawJSON `json:"time"`
	GetShowing     RawJSON `json:"get_showing"`
	PurchaseOffset RawJSON `json:"purchase_offset"`
	ShopOffset     RawJSON `json:"shop_offset"`
	RarityBG       string  `json:"rarity_bg"`
	SpecialEffects RawJSON `json:"special_effects"`
	GroupIndex     *int    `json:"group_index"`
	Gyro           *int    `json:"gyro"`
	HandID         *int    `json:"hand_id"`
	Illustrator    *int    `json:"illustrator"`
	Illustrator2   *int    `json:"illustrator2"`
	VoiceActor     *int    `json:"voice_actor"`
	VoiceActor2    *int    `json:"voice_actor_2"`
	DoubleChar     *int    `json:"double_char"`
	LipSmoothing   *int    `json:"lip_smoothing"`
	LipSyncGain    *int    `json:"lip_sync_gain"`
	L2DIgnoreDrag  *int    `json:"l2d_ignore_drag"`
	SkinType       *int    `json:"skin_type"`
	ShopID         *int    `json:"shop_id"`
	ShopTypeID     *int    `json:"shop_type_id"`
	ShopDynamicHX  *int    `json:"shop_dynamic_hx"`
	SpineAction    RawJSON `json:"spine_action_offset"`
	SpineUseLive2D *int    `json:"spine_use_live2d"`
	Live2DOffset   RawJSON `json:"live2d_offset"`
	Live2DProfile  RawJSON `json:"live2d_offset_profile"`
	FXContainer    RawJSON `json:"fx_container"`
	BoundBone      RawJSON `json:"bound_bone"`
	Smoke          RawJSON `json:"smoke"`
}
