package consts

const (
	// for protobuf.DROP_INFO{} ...
	DROP_TYPE_RESOURCE          = uint32(1)
	DROP_TYPE_ITEM              = uint32(2)
	DROP_TYPE_EQUIP             = uint32(3)
	DROP_TYPE_SHIP              = uint32(4)
	DROP_TYPE_FURNITURE         = uint32(5)
	DROP_TYPE_STRATEGY          = uint32(6)
	DROP_TYPE_SKIN              = uint32(7)
	DROP_TYPE_VITEM             = uint32(8)
	DROP_TYPE_EQUIPMENT_SKIN    = uint32(9)
	DROP_TYPE_NPC_SHIP          = uint32(10)
	DROP_TYPE_WORLD_ITEM        = uint32(12)
	DROP_TYPE_WORLD_COLLECTION  = uint32(13)
	DROP_TYPE_ICON_FRAME        = uint32(14)
	DROP_TYPE_CHAT_FRAME        = uint32(15)
	DROP_TYPE_EMOJI             = uint32(17)
	DROP_TYPE_LOVE_LETTER       = uint32(19)
	DROP_TYPE_SPWEAPON          = uint32(21)
	DROP_TYPE_META_PT           = uint32(22)
	DROP_TYPE_SKIN_TIMELIMIT    = uint32(23)
	DROP_TYPE_BUFF              = uint32(24)
	DROP_TYPE_COMMANDER_CAT     = uint32(25)
	DROP_TYPE_TRANS_ITEM        = uint32(100)
	DROP_TYPE_USE_ACTIVITY_DROP = uint32(1000)
	DROP_TYPE_RYZA_DROP         = uint32(1001)
	DROP_TYPE_WORKBENCH_DROP    = uint32(1002)
	DROP_TYPE_FEAST_DROP        = uint32(1003)
)
