package consts

const (
	MAIL_DEAL_CMDS_READ        = 1
	MAIL_DEAL_CMDS_IMPORTANT   = 2
	MAIL_DEAL_CMDS_UNIMPORTANT = 3
	MAIL_DEAL_CMDS_DELETE      = 4
	MAIL_DEAL_CMDS_ATTACHMENT  = 5
	MAIL_DEAL_CMDS_OVERFLOW    = 6
	MAIL_DEAL_CMDS_MOVE        = 7
)
